### ISSUE TITLE
Setting the Description and Keywords fields within Site Settings appears to change the Description and Keywords fields on every page

### ISSUE THREAD

**Issue by RockSolidSW** [dnnsoftware/Dnn.Platform#2119]
## Description 
Setting the Description and Keywords fields within Site Settings appears to change the Description and Keywords fields on every page

## Steps to reproduce
- Access Site Settings from the Settings, Site Settings area (off the Persona Bar)
- Populate the Description and/or Keywords fields
- Click Save

## Current result
The above steps will change the Description and Keywords fields for all of the pages within the site (although they do not appear to change values that were already set)

## Expected result
Do not change the Description and Keywords fields for the pages, just for the site itself (or if there is value here, maybe ask during the Save routine)

## Affected version

* [x] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

I have only had the opportunity to test within Safari.

* [ ] Chrome
* [ ] Firefox
* [X] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by moorecreative** [comment]
I may be missing your point... as in you might be describing that when you edit the Portal Site Settings meta information, you see it also change those settings within each Page (tab)'s Settings of meta... but I didn't get that from your description.

If you are describing what you see in the rendered code when browsing to Page X, Y and Z, that they display the same meta info that you entered into the Portal Site Settings, then that is core expected/correct behavior.

The Site Settings meta information is rendered for any page that does not have meta title and description. If a Page(tab) has a meta title and description entered for that page, then that page-level info will be rendered instead of the Portal-level backup/default meta.

**Comment by valadas** [comment]
I am assuming @moorecreative reply explains this and I am closing this issue as this is the expected behaviour
