### ISSUE TITLE
DNN failed to install

### ISSUE THREAD

**Issue by ac160006** [dnnsoftware/Dnn.Platform#2142]
## Description 
We're sorry. The following products have failed to install.
DNN Platform

## Steps to reproduce
Downloaded  DotNetNuke.exe  7/1/18  2:33 AM

## Affected version
Don't know.  I didn't check these.

* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

Opera ver. 53.0
[cantInstall.docx](https://github.com/dnnsoftware/Dnn.Platform/files/2153053/cantInstall.docx)

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by bdukes** [comment]
To save y'all from having to read through the Word doc, @ac160006 is having an issue with the Web Platform Installer, i.e. the Deploy package of DNN.  There's an error connecting to his local SQL Express database.

@ac160006, DNN provides a Deploy package which interfaces with Microsoft's [Web Platform Installer](https://www.microsoft.com/web/downloads/platform.aspx).  The functionality to locate and validate a database connection is not part of anything that DNN provides, but a piece of the Web Platform Installer itself.  If you're having issues, you can look for support from Microsoft on the Installer.

Alternatively, the DNN Community has been recommending [nvQuickSite](http://www.nvquicksite.com/) recently for a utility to quickly install DNN, so you might try that approach.

**Comment by ac160006** [comment]
Why did you close MY ticket.  It remains unsolved.

**Comment by bdukes** [comment]
@ac160006 I closed the ticket because, as far as I'm able to determine, it is not an issue with DNN itself.  I provided direction to where you could get support, and alternative approaches.  You may reopen the ticket if you feel there continues to be an issue that needs to be resolved in DNN, but we'll need more details to pinpoint that change might be needed.

**Comment by sholman** [comment]
Hi ac160006

This is likely because by default SQL Express installs in Windows Authentication Only mode. You need to right click on your Instance in SSMS, go to Properties, then to Security, and change the option to "SQL Server and Windows Authentication Mode", the restart your SQL services
![sqlexpress01](https://user-images.githubusercontent.com/885331/42665892-cecd4974-8680-11e8-9714-7c9592dd8b66.png)
