### ISSUE TITLE
File Management Issue: Unable to rename UPPERCASE file same name to lowercase.

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#2210]
## Description 
Error when trying to rename a file the same name but from UPPERCASE to lowercase due to using the same name.
## Steps to reproduce
1. open site assets and upload a file such as FILEEXAMPLE.png 
2. rename the file to the same filename but lowercase fileexample.png
## Current result
Error a file already exists with that name
## Expected result
ability to rename a file case sensitivity
## Affected version

* [x] 9.2

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
This is not Dnn specific, same happens in windows. I know for one that when this happens in windows, you need to rename it to something else, then rename it back with the original name but with the case you want. Windows file names are kinda half case sensitive, they display with a proper case but are treated case-insensitive otherwise, so you cannot rename by only changing the case.

**Comment by valadas** [comment]
Closing this issue as per previous comment, this is a filesystem limitation and not a Dnn issue.
