### ISSUE TITLE
Google reCaptcha Integration for dnn login/registration captcha replacement

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#2282]
## Description of problem
Google reCaptcha Integration for dnn login/registration captcha replacement

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
I have implemented reCaptcha in the Form&List and Feedback modules. For each, there is a setting to enter the public and private key. If this is implemented into the platform, it would be nice to have some api modules can use so that users only have one place to enter those keys and reuse reCaptcha in multiple places. It could be a replacement to DnnCaptcha.

**Comment by thabaum** [comment]
this would also be great to add to DNN Events as well as an option for allowing users to post events to be verified.

I agree with your idea as well I think it would be very nice and straight forward to be able to add to a module without having to key each module.  Great idea :)

**Comment by trouble2** [comment]
Would be good to also make it optional in the login and registration for DNN as well. (I believe there already was a setting somewhere for the DNN captcha, but reCaptcha would be better...)
So the keys would then have to be set in host or portal settings (portal would override the host, just like the SMTP settings do/did)

**Comment by valadas** [comment]
I might actually have some ideas for this to make it a reusable control that would use the host or site google api key, then it would have options for the mode to use, such as recaptcha, nocaptcha or invisible captcha, etc. But we need to be very careful specially in the context of login so that this falls back to allow login in case there is any problem (servers that cannot connect to the internet, failure at google, api changes on google side, etc.). I am assigning this to Dnn 10 but we will see if time permits to do a proper implementation. The login form may also need some revamp for this to work and display properly.

**Comment by valadas** [comment]
I am closing this one since nobody submitted a PR for it. Thinking more about it, it would create a dependency on an external service and this is something we try to avoid in the core. But since authentication is an extension point I guess a better solution would be to implement this as a 3rd party authentication solution that would be optional.

**Comment by thienvc** [comment]
Extent as CaptchaProvider
