### ISSUE TITLE
Email not sent when user is "authorized"

### ISSUE THREAD

**Issue by rmanjoney** [dnnsoftware/Dnn.Platform#2338]
## Description of bug
On a site with User Registration set to "Private", an email is not sent out when the admin authorizes the user.

## Steps to reproduce

1. Site setup for Private registration (Persona -> Settings -> Security -> Member Accounts -> Registration Settings
2. User registers. Email is received by both user and site admin.
3. Site admin authorizes user, either via the "authorize" link, or via Persona -> Manage -> Users -> User -> Authorize User

## Current result
User does not receive confirmation email that he's been authorized

## Expected result
User should receive confirmation email that he's been authorized.

## Affected version

* [x] 9.2.1

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
Just tried this out on 9.4.0 RC and having a slightly different issue, I the the password reset email instead of the authorized email:

Dear xxxxxxx,

You have requested a Password Reset Token from My Website, but Your account is pending approval.

Password can be reset after account is approved.

Sincerely,
My Website

*Note: If you did not request a Password Reset Token, please disregard this Message.

**Comment by valadas** [comment]
I can no longer reproduce in 9.6.2, closing this issue, if you can still make it happen please comment.

![image](https://user-images.githubusercontent.com/6371568/88693908-dcd45f00-d0cd-11ea-91d9-65d515962a28.png)
