### ISSUE TITLE
DNN logo at the bottom of the install page animates in and out continually

### ISSUE THREAD

**Issue by OllyHodgson** [dnnsoftware/Dnn.Platform#2346]
## Description of problem
This one is super low priority. On the install page, there is a DNN logo which fades in and out throughout the install. I believe on Evoq, several images are used here to highlight features. On Platform, it's just the same DNN logo animating over and over and over.

## Description of solution
If there's only one image there, don't animate it. Either hide it completely or keep it static.

## Description of alternatives considered
Go the Evoq route: Add several images and cycle throught them to show off features. But honestly I think it'd be better just to hide it. Keep the screen simple.

## Screenshots
![image](https://user-images.githubusercontent.com/437224/46141915-39a22c80-c24d-11e8-941f-27a2797c65d1.png)

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

**Comment by sleupold** [comment]
maybe we should use the option to highlight newest features in DNN Platform during install :)

**Comment by valadas** [comment]
I was thinking of some banners with links to some info:
* Whats new in this release
* Extensions Catalog (collection of open source modules)
* Dnn documentation
* Where to get help (dnnsoftware.com Q&A)
* Link to dnn store
* Fork us on Github

Giving that the installation got a lot quicker in recent versions, this would have to continue animating after the steps are complete and the Visit Your Site button shows.

And I guess there should be some config file so it can be easy to customize for platform and evoq, that file could contain: image and url.

The url should open in a new tab obviously.

Maybe we could consider having a larger image if we make that into banners that contain text and redesign the position of it on the install page...

**Comment by ohine** [comment]
My vote is to remove it, the reason why it's not working is the website it's looking for doesn't exist. I've asked for it to be restored numerous times.

If we want to keep it, I can setup a new site on azure through the foundation and we can add banners at anytime. We will need to submit a pull request to update the URL the installer is using to fetch banners.

**Comment by valadas** [comment]
Why not use local images. We could have a InstallerBanners folder with images? But I don't really care if that is removed all together, the install is so quick now anyway. Time could be invested in putting the suggested items in the default site template instead of this. Users will see that more than the installer and can return to it as they evaluate the platform.

**Comment by VashJuan** [comment]
Looking at the code a bit:
Currently every 5 seconds it brings up the logo, with no link.

If the number of banners is set; then it pulls the banners from 
http://cdn.dnnsoftware.com/installation/Banner1.aspx and clicking that links to
http://www.dnnsoftware.com/installation/Banner1.aspx

The CDN links currently fail for me. 

At www:
Banner1.aspx redirects to http://www.dnnSoftware.com/evoq-free-trial
Banner2.aspx redirects to http://www.dnnSoftware.com/resource/webinars
Banner3.aspx redirects to http://store.dnnSoftware.com/
Banner4.aspx and 5 give me a 404 error.

Like Daniel has suggested, these could be redirected to something useful. I'd say:
- Docs
- GitHub catalog
- Store

But this then becomes more of a thing for the Awareness committee and DnnSoftware.ORG, right?! Can we come up with a quick fix, recognizing the other may be months away?

**Comment by hismightiness** [comment]
I have a lot of experience working with that from our time with Hotcakes.  I think we should keep it, but move the banner location to DNNSoftware.org.  This would allow us as a community to do the same things it was originally intended for.  We can promote DNN events, news, and features.  Due to the amount of time most installs take, I don't think we should ever have more than 3 banners though.  We can of course provide access to the appropriate people so that the banners are maintainable.  

The script is fairly simple, but it needs to be updated a bit to be more flexible.  It simply cycles through the given domain and folder for images that match the expected naming convention (mentioned earlier).  It has a default image and domain name as well.  If no images matching the pattern are found at the expected location, it simply cycles through the default image.  Otherwise, it cycles through the images that are found.  However, the last time I looked, it didn't have a way to specify different URLs/landing pages for each banner image.

**Comment by valadas** [comment]
I agree with a max of 3, on DNNSoftware.org we can then have some landing page, kinda getting started page with more things and links to stuff.

**Comment by sleupold** [comment]
When implementing an improved solution, please don't forget that a number of servers (especially in companies) are not allowed to retrieve content form outside the company's network, please make sure it contains valuable information for those "offline" scenarios as well.

**Comment by mitchelsellers** [comment]
I agree with @sleupold having the installer make remote calls to load content should really be discouraged, or it needs to be disclosed for those that are working in sensitive environments

**Comment by hismightiness** [comment]
I think we should still retain the remote content, but those are great points by Mitch and Sebastian.  This should be updated to notify the viewer that the content is coming from DNNSoftware.org.  

In addition, logic should be in place to let them know that the content was unable to be displayed if DNNSoftware.org is not accessible.  

In this latter instance, should we have default content?  Perhaps promoting community areas/features such as the forums, documentation, etc.?

**Comment by mitchelsellers** [comment]
@hismightiness For certain government agencies, it would need to be stopped BEFORE it tries to actually go out.  This is part of the big deal with the Upgrade Service that requires some agencies to modify the default install template to turn it off by default.  Just my $0.02.
