### ISSUE TITLE
Web.config on fresh install should include MIME map for woff2 fonts

### ISSUE THREAD

**Issue by OllyHodgson** [dnnsoftware/Dnn.Platform#2408]
## Description of problem
Certain themes bundle webfonts in a variety of formats. If IIS isn't configured correctly they return a 404 error. If you're hosting DNN on an Azure App Service the web.config file is the _only_ way this can be achieved.

## Description of solution
Include appropriate mime maps on the fresh unmodified web.config file. I believe we already handle `.svg` and `.woff` this way, so adding a new one seems like it ought to be fairly straightforward:

```
<system.webServer>
    <staticContent>
        <remove fileExtension=".svg" />
        <mimeMap fileExtension=".svg" mimeType="image/svg+xml" />
        <remove fileExtension=".woff" />
        <mimeMap fileExtension=".woff" mimeType="font/woff" />
        <remove fileExtension=".woff2" />
        <mimeMap fileExtension=".woff2" mimeType="font/woff2" />
    </staticContent>
</system.webServer>
```

## Screenshots
If applicable, provide screenshots to help explain your problem and/or feature.
![image](https://user-images.githubusercontent.com/437224/47150790-997d7780-d2cf-11e8-9ca4-5cfe20a5daf9.png)

## Additional context
As far as I can tell, recent versions of IIS / Azure App Services handle `.eot` and `.ttf` font files without issue.

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser
Any .woff2 supporting browser.

* [x] Chrome
* [x] Firefox
* [x] Safari
* [ ] Internet Explorer
* [x] Edge

**Comment by sleupold** [comment]
I submitted a PR for this last year, but unfortunately, it didn't get merged.

**Comment by valadas** [comment]
Any opinions on also doing it during upgrades?

**Comment by sleupold** [comment]
IMO it would be beneficial for all (existing and new) sites, I don't see a risk of breaking anything.
Be aware, however, the file extension might already be present (and use a different mime type, as the suggested mime types changed during the past years)

**Comment by mikesmeltzer** [comment]
While the Mime Types listed in this issue are quite common and should probably be included by default.. 

I think that extension developers (skins, modules, etc.) need to get into the process of including these types of changes within their install packages so that on extension install the site is updated accordingly.  

I don't think this will necessarily happen but we should be mindful of what is added to the core so that we do not create unnecessary dependencies, expectations or just have additional items setup because someone might use them.  IMO we should only have what's required by the default installation setup and then extensions add / change config as they are needed.

**Comment by OllyHodgson** [comment]
The built in Xcillion theme references at least one .woff2 file (the glyphicons font), so I think it makes sense for DNN to support it by default.

**Comment by bdukes** [comment]
I think @mikesmeltzer's point is that the Xcillion theme package should add `woff2` support if it needs it, rather than putting it into the core.

**Comment by sleupold** [comment]
I agree with @bdukes

**Comment by mikesmeltzer** [comment]
Yep, that's exactly what I was meaning.




That being said, is there anything else in the core that uses those resources?




Get Outlook for Android







On Thu, Oct 18, 2018 at 12:30 PM -0300, "Sebastian Leupold" <notifications@github.com> wrote:












I agree with @bdukes

**Comment by sleupold** [comment]
one Scenario: editors might want to use a font (like fontAwesome) in module templates without the need to edit web.config manually.

**Comment by OllyHodgson** [comment]
Point taken that the theme packages perhaps ought to add support for any MIME-types they add. This is where things get fuzzy though, because Xcillion effectively appears to be part of core :smile: Is the process for theme packages to add this stuff documented anywhere?

Mind you, any theme which uses Boostrap/Foundation/any web fonts would need to make sure it includes support for a variety of MIME types (svg, ttf, eot, woff, woff2). Feels like it'd be simpler all around to just include the common ones in the core platform.

Finally, @sleupold had a pull request to add .woff2 to https://github.com/dnnsoftware/Dnn.Platform/blob/development/DNN%20Platform/Library/Services/FileSystem/FileContentTypeManager.cs. Does this code allow .woff2 files to be properly handled when served from a DNN folder provider?

**Comment by OllyHodgson** [comment]
It turns out the `.woff` and `.svg` MIME types are added to `web.config` as part of the Personabar installation (they're in the [Dnn.PersonaBar.UI extension](https://github.com/dnnsoftware/Dnn.AdminExperience/blob/development/Library/Dnn.PersonaBar.UI/Dnn.PersonaBar.UI.dnn#L63)). They aren't a part of core. My theme framework of choice ([nvQuickTheme](https://github.com/nvisionative/nvQuickTheme)) now [includes the config for `.woff2` etc in its manifest](https://github.com/nvisionative/nvQuickTheme/blob/master/manifest.dnn#L70).

The only remaining question is should we add the `.woff2` mime type to [FileContentTypeManager.cs](https://github.com/dnnsoftware/Dnn.Platform/blob/development/DNN%20Platform/Library/Services/FileSystem/FileContentTypeManager.cs)? (It's still not clear to me what that's used for)

**Comment by sleupold** [comment]
@OllyHodgson AFAIK you need adding a type to FileContentTypeManager.cs to be able to include it in an installable package.

**Comment by OllyHodgson** [comment]
@sleupold I'm not sure I understand :smile: I can install a theme with .woff2 files, even though FileContentTypeManager.cs doesn't include them. 

Is it that if the file type is not specified in FileContentTypeManager.cs, you need to specify a mime type in the `<component type="Config">` section of the extension's manifest file?

**Comment by Accuraty** [comment]
Quick questions: should it be 

<mimeMap fileExtension=".woff2" mimeType="application/font-woff2" />   
 
or is this one somehow better?

<mimeMap fileExtension=".woff2" mimeType="font/woff2" />

**Comment by valadas** [comment]
I think a quick fix would be to add it to the default theme and bumping it's version, it will fix existing sites on upgrade and be applied on new installs as well. Assigning this to 9.4.1

**Comment by valadas** [comment]
wofff2 is now part of a 9.6.2 install, not sure how, but I guess by a theme update.
![image](https://user-images.githubusercontent.com/6371568/88691934-7a7a5f00-d0cb-11ea-86ab-1e33532a7dba.png)

closing this issue but feel free to comment if there is more to it.

**Comment by jeremy-farrance** [comment]
Suggestion, thinking out loud...

Leaving this here for future reference. What we need is to be able to account for older versions of IIS. WOFF2 is there for us nowadays in IIS 10 and later. You can read a lot about it here in [this article from 2016](https://weblog.west-wind.com/posts/2016/jan/25/fontawesome-fonts-and-mime-types-in-iis-and-other-web-servers).
 
Instead of debating this we should keep things simple. Once a mime type becomes pervasive and popular enough and it not yet in a version of IIS, DNN should be adding it, where it is missing, back to the oldest supported version of IIS.
 
This doesn't need code or any complex solution (IMHO). We should just simply do something like this, [Mozilla has a list of common mime types here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types). If we support DNN on a version of IIS (7+ at this time, right?) that does not include any of the common ones Mozilla lists, those (hopefully few) should be added. This would/will make life MUCH easier for administrators, hosters, developers, etc. I know I have lost a few hours over the years on these issues, and an approach like this seems easy to follow and implement moving forward. 
 
Maybe there is a downside that I don't see?

**Comment by Timo-Breumelhof** [comment]
I know old issue, but still.
The woff-2 MIME type definition currently in web.config does not work anymore.
IMO we should support these font MIME types by default and use the ones in the list @jeremy-farrance mentioned.

Re-open or new issues? @valadas

**Comment by jeremy-farrance** [comment]
Thanks for the reminder, I hope its worth mentioning, I now maintain my own list and keep it up to date with notes specific to DNN (that work for us as an agency).
[https://www.accu4.com/H2R2S/IIS-Notes-and-Reminders](https://www.accu4.com/H2R2S/IIS-Notes-and-Reminders)

**Comment by valadas** [comment]
@david-poindexter is working on a new theme and we should probably handle it in that new one

**Comment by david-poindexter** [comment]
I agree and this is already handled in the new DNN 10 theme (currently on a forked branch).  I propose we go ahead and close this issue in light of that.

**Comment by Timo-Breumelhof** [comment]
ok thanks @david-poindexter
