### ISSUE TITLE
RFC: Removal of Documentation from DNN.Platform

### ISSUE THREAD

**Issue by mitchelsellers** [dnnsoftware/Dnn.Platform#2451]
## Description of problem
Currently the size of the DNN.Platform repository, without looking at GitHistory is approximatley 422.9 MB in size.

Of this, 286.8MB of the size are items contained inside of the /Documentation folder.  This folder has not been updated in more than 4 years.  

It would be highly beneficial for builds, clones, and other management to remove this dead weight from the DNN Platform Repository, as other documentation efforts are underway.

## Proposed Solution
Deletion of the Documentation folder would reduce the code-file size of the project by more than 60% which would improve the build time.  Change history would allow historical access to this.

## Proposed Solution Option 2
Move the Documentation to a "Legacy Documentation" repository and then remove the contents from the dnn.platform repository.

**Comment by EPTamminga** [comment]
I am in favour of Solution #2.

**Comment by OllyHodgson** [comment]
I have questions:

1. Given the timelapse since the documentation was updated, is the contents relevant to the current version of the product?
2. Are there any rough timescales before we can see or start contributing to the replacement documentation? 

Lets not _delete_ this one if it if it's going to be a useful reference to the people building out the new stuff. If it's causing issues, by all means move it to another "legacy" repository. Given the lack of decent DNN documentation available right now, I'm loathe to _delete_ any of it!

**Comment by valadas** [comment]
> Given the lack of decent DNN documentation available right now, I'm loathe to _delete_ any of it!

I totally agree with that, I would wait for decent and "contributable" documentation before moving any of it, and I would definitely not delete it, just move and and keep a link to it or something.

**Comment by ohine** [comment]
Well, removing it won't free up any space due to git. We will need to figure out how to trim our history at some point in the future....

I vote for a # 3 solution, move it off to a github pages site.

**Comment by mitchelsellers** [comment]
@ohine The history would still be there so the size of the .git file would be still including this, but the actual /documentation folder would be 288mb smaller, which is a sizeable change.  I like the idea of doing GitHub pages with this, which is nothing more than a new Repo with Pages enabled.

Secondary question - If we do this, should we be adding a warning that the content was not updated since 2014?

**Comment by donker** [comment]
> Well, removing it won't free up any space due to git. We will need to figure out how to trim our history at some point in the future....

Together with other discussions around project organization we may well trigger a complete reset for the project so we could start with a clean history, moving all legacy stuff to archived repos.

**Comment by iJungleboy** [comment]
@ohine I wouldn't put it into github pages, because it's not really relevant any more and putting it there gives it the appearance of being used. 

I'm fully in favor of #2 - just put it into a separate repo and let in rot, in case someone wants to pick something up from there.

**Comment by mtrutledge** [comment]
I would prefer option #2. It doesn't have to be a completely separate repo. It can just be an archived_documents branch. Either way, it doesn't matter. As long as we are moving it somewhere and mark it for deletion once the new documentation efforts are fully in place.

**Comment by nvisionative** [comment]
I am in favor of #2 and since it is legacy docs I see no reason to delay this for any new documentation efforts.  We already have the DNN Documentation center (which is more current than the repo documentation).  And we have dnnapi.org.  I am not a fan of confusing with a new GH Pages implementation.
