### ISSUE TITLE
RFC: Evoq Becomes a Suite of Extensions

### ISSUE THREAD

**Issue by hismightiness** [dnnsoftware/Dnn.Platform#2537]
## Description of Problem
Right now, when people install Evoq or Platform, they potentially see a completely different product name and/or version. This creates a multitude of problems, including: 

* Issues receiving timely support from ecosystem vendors
* Accidental upgrades to wrong DNN products
* Not knowing what version of DNN someone is actually on
* Not knowing if the current version matches security reports
* Versions and releases are dependent upon the community and DNN Corp development timelines and resources matching with each other
* Evoq makes core code changes to DNN, making it impossible for customers to make their own decision about how and which DNN-based product they want to use

## Proposed Solution Option 1
DNN Corp needs to work on and release Evoq as it's own suite of extensions the same way the rest of the ecosystem is required to do this same kind of product development.  The next release of Evoq will then follow its own timeline and version number sequence.  It will also remove it's core code changes from DNN Platform, including core UI items that are only for Evoq.  DNN Platform and Evoq can then each work independently and better serve their target audiences.  

## Proposed Solution Option 2 (If Needed, repeat for more)
There is not another solution.

## Alternatives Researched
There are no alternatives.

## Affected version

* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

**Comment by VashJuan** [comment]
I'm not as concerned that we tell Corp what to do. I do think customers need a clear understanding of tiers of product and that Community shouldn't be hidden, but proudly held up by Corp. 

Just as Corp should promote the Community product, so we should promote the higher tier products: we aid each other! It took me years (even as a long time user/observer) to understand what Evoq was - and I still can not articulate the value add - which is sad.

That said it should always be clear what a site is running - and maybe not spread out into 3 places like it is in the Personna bar:
- Clicking on top DNN icon
- Settings | Servers
- Setting | About

Having Evoq as a (high-end!) extension does make sense to me though.

**Comment by hismightiness** [comment]
From the very beginning, Evoq being a suite of extensions on top of DNN is what was said and "sold" to the community externally by DNN Corp.  If this was ever the truth, it would be perfectly fine and fantastic, even.  I can tell you after having been on the inside as a DNN Corp employee in the past, this is how it was trained and explained to employees internally as well.  However, this has never been the case.  Even back in DNN 5.xx days when it was DNN Professional (not yet called Evoq), it was already changing the core of DNN, causing many of the concerns outlined in the RFC.  You can't simply uninstall Evoq like you can with any other extension that's acting as a responsible member of the ecosystem.  And when it's installed, it's completely unclear what DNN you have installed.  It's no longer DNN.  It's Evoq with a DNN logo.  The entire user experience is blurred.  It would be far simpler if it were changed completely.  Instead, it's only changed just enough to confuse all stakeholders.

**Comment by thabaum** [comment]
I agree there has to be some major changes in things such as the login system and what features are working normally and up to speed with simple features with the social modules DNN CE has.  They have not been touched since it was installed.   Any community edition with open source of a platform with these features would of been enhanced by now but since Evoq keeps throwing a bunch of breaking changes the entire community is in chaos it feels.  Although things have been getting better... the login/registration system is old looking along with the themes.  I still can't get the facebook/google authentication systems going even with version 9.3RC.  I highly doubt EVOQ has these issues and we as an open source community need a solid foundation to grow support that does not make us left in the dark plagued with problems when EVOQ wants to do a core change.  It would be AWESOME if DNN Corp would put the EVOQ core for the CE and allow modules and more features to be unlocked as you purchase upgrades.

From what I understand if you quit paying the yearly subscription you lose all your features... so you pay $30k or whatever for a year and if you cant foot the bill the following year you loose access to all the modules/features you had, not just the ability to upgrade and get support.  That scared me away from buying it or I would of bought the EVOQ social for a year, and if they had some reasonable renewal fee I would still be paying them money.  Instead I am here looking for ways to help this project and understand what I can do to make this along with some other paid and developed modules do the job.  There is no pricing/features table to look at only a way to contact them so they can give you a sales pitch.  It is a poor business model in my opinion but it must be working and they must be living pretty fat off of the clients it currently has.  At the same time I get it... money is money, time is money.  I just can't believe they would leave this so upside-down for so long with a button to upgrade to EVOQ as this platform is not doing any upselling for community users.  Wordpress is beating this old dog down and it will only keep relevant if DNN Corp spends a lot on advertising because the core power users that talk the CMS up are talking it down right now.  This has to be hurting sales as it's tough to grow a site with users when they get slow login page, can't use social authentication systems...  I can't even figure out if anyone else has the FB or Google authentication systems working with DNN CE to know if I am going crazy or wasting my time trying to set all different settings in facebook app to make it work.  Just some feedback on my end I am all for making DNN CE a winning solution to help grow users into an EVOQ environment.  EVOQ does contain features that I desire even in the Basic version but I have had to spend a few years to figure out a few of them even exist.  Most people administrating a DNN site or any CMS site dont want to fuss with github support tickets... they want to work and spend time growing the site.   I am happy after 1 year of no ability to allow users to register I finally can after the last release... that simply blew me away as I know no one is actually using DNN CE as a production site because if anyone here actually did they would of caught that bug right away and got the army on it.

I suggest everyone developing here to put up a DNN CE site for growing a community for some hobby topic just to see what is actually needed to keep the our sites running.   Not just running some script that does a bunch of tests which is great but also having a community CE site.   Heck why dont we put up a site called www.dnnce.com that is strictly focused on the DNN CE and runs the latest release to ensure it is working as planned and all features included in the package function well.   If an issue happens we will immediately be able to all verify and look for a solution and help plan ahead.  I would love to know who is trying to work on what issues so I don't do work that has already been done.  I did that trying to figure out the username || email statement for registration creating a pull request on something that was already fixed trying to resolve something.  Waste of time...

**Comment by VashJuan** [comment]
Good comments, but dnnce.com is too close to dunce.com!

**Comment by thabaum** [comment]
I feel like a dunce after spending time trying to figure out a role I can play to help here.  I am still here, I am not a quitter! GO TEAM!!!

**Comment by hismightiness** [comment]
FYI - This RFC is not at all meant to be a product comparison or bashing of any kind.  It would be super helpful to all stakeholders if we only focus on what it would take and mean to make these changes and/or if there are different changes to be made.

For example:

- Is there any benefit to the ecosystem as a whole if we did nothing and left the current breaking changes as-is?
- What would be the effort/road map to make these changes if we decided they were necessary?
- How are the concerns in this RFC impacting you, if at all?  
- Do you feel that there is anything missing or misrepresented in this RFC?

I look forward to helping us continue this dialog in as much of an objective manner as possible.  :)

**Comment by thabaum** [comment]
Sorry to make things sound like I am venting on anyone or any topic if I do sound that way.  I am just trying to give some feedback and support for DNN CE to help me out for when I make the move to EVOQ which I will eventually I feel for a project of mine.  I just dont have confidence in things right now as the foundation is very shakey.  I switched from PHP focus to .NET 10 years ago with a secure app to build in mind.  DNN CE has been a great CMS for basic websites... but since the Active Modules purchase DNN CE was suppose have gained social features, but instead the ones that have been added are very basic and hardly supported.  

My community I spent years building is flat out dead from version 9 upgrade.  I am grinding along hoping to see light at the end of the tunnel but the light just seems like its the train coming the other way.   I have to make a major decision in the next month or two whether to stay in this grind or move on like I did away from PHP and into something else.  I agree something needs to be done here is all I am trying to say and maybe my thoughts might hit someone that works for DNN Corp has been pretty unfair to everyone in my opinion here who spend money in the DNN store and looking to upgrade to EVOQ.  I dont know if I can support a company with such disregard much longer...

**Comment by sleupold** [comment]
>           Good comments, but dnnce.com is too close to dunce.com!

There is no DNN CE anymore, there is DNN Platform as open source product, maintained by the community, and there are Evoq Extension Suites, built on top of it. Although we are very glad for all development contributions from DNN Corp to the platform, we need to make sure, Evoq does behave like all other extension suites, allowing to decide your own, whether you want to run on Platform or add an Evoq suite on top, or not. Of course, if you cancel your Evoq subscription, you might loose the content, stored by the extensions and you need to migrate this content to a different solution (which is not always trivial).

**Comment by sleupold** [comment]
one of the main tasks would be using a dedicated namespace and code for HTML Pro module, allowing an easy downgrade.

**Comment by valadas** [comment]
In the spirit of cleaning the backlog I am closing this issue because it is not right now anything actionable and is more of a discussion. I would suggest moving that discussion to the forums.

**Comment by hismightiness** [comment]
Doesn't closing it only ensure that nothing actionable doesn't occur and/or takes longer?

**Comment by valadas** [comment]
Well, in my opinion that is not for us to do right? If I am wrong and this is something the community can do, then yes, but I don't see how we could do that and for that reason I think this is only a discussion and not an actionable item on our part in this repository? But correct me if I am wrong.
