### ISSUE TITLE
Default Page caching provider is not initialized on install

### ISSUE THREAD

**Issue by EPTamminga** [dnnsoftware/Dnn.Platform#2577]
## Description of bug
Since DNN 9.x (?) there is a host setting for **Page Output Cache Provider**. This setting is not initialized during a new installation.

## Steps to reproduce
List the steps to reproduce the behaviour:
1. Create a clean install
2. Goto Host - Settings - Servers - ServerSettings - Performance
3. Scroll down to 'Page Output Cache Provider'
4. The field is not initialized

## Current result
Empty value

## Expected result
PageCaching set to 'MemoryOutputCachingProvider' by default

## Screenshots
![image](https://user-images.githubusercontent.com/5859855/52221890-7d174200-28a2-11e9-8d77-c8a5252d3887.png)

## Affected version

* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer
* [X] Edge

**Comment by EPTamminga** [comment]
Pull request fo fix created
PR #2579

**Comment by EPTamminga** [comment]
@nvisionative: Shouldn't we optimize performance by default?
What sort of confusion can arise?

**Comment by nvisionative** [comment]
In this case, no.  This setting alone doesn't do the full job of Page Output Caching.  Each page has its own setting for this.  

![screencapture_ 2019-02-04 02 17 pm _2155](https://user-images.githubusercontent.com/4568451/52231512-2a309100-2888-11e9-80d6-b5527c710ce9.jpg)

Implementing this causes a "mysterious nightmare" for administrators and opens up a whole can of worms from a support and training perspective.  We are very particular on which sites we utilize this feature on, due to the complexity.  

Did you know that **Clear Cache** does not in fact clear cache used via this feature?  Therefore, basic content editing becomes much more of a chore and is confusing for the inexperienced.

**Comment by bdukes** [comment]
From what I can tell, that host setting has no effect.  It sets the _PageCaching_ host setting, which is only referenced by [`Host.PageCachingMethod`](https://github.com/dnnsoftware/Dnn.Platform/blob/f809dd77ed8a03f38087735c86d842a1edbd7df8/DNN%20Platform/Library/Entities/Host/Host.cs#L875-L886), a property which is not referenced anywhere in the project.  As far as I can tell, only the page-level setting is used.

**Comment by mitchelsellers** [comment]
I can confirm what @bdukes mentions.  It seems to me that this used to be called "Default Page Output Cache Provider" or something.  It was used to allow on a page-by-page basis to opt-in, but not explicitly set it to a particular provider.

As-is, this setting has no impact on performance.

**Comment by EPTamminga** [comment]
Thank you for the investigation and explanation. 
I will close the issue and cancel the PR.
