### ISSUE TITLE
Error during site installation of 9.3 rc2

### ISSUE THREAD

**Issue by abukres** [dnnsoftware/Dnn.Platform#2604]
Using cloned repo of 9.3 rc2. During installation of dnn, I get this error:
 27% ERROR occured - Installing Provider - DNNConnect.CKEditorProvider_01.00.04_Install.zip

clicking on the log button, I get this:
03/02/2019 06:33:11 [ERROR] DotNetNuke.Services.Upgrade.Upgrade Install aborted - The module being installed is not compatible with this version of DNN. An upgrade to version 7.4.0 is required.

**Comment by ohine** [comment]
Are you generating the package yourself from the cloned fork?

**Comment by abukres** [comment]
> Are you generating the package yourself from the cloned fork?

I am doing nothing other than compiling the solution and running it.

**Comment by ohine** [comment]
Try running the following from a powershell window. 

./build.ps1 -Target BuildAll

I’ll post the full command we are using to generate the RC2 build when I get back to my desk, as you need to target the release branches in Admin Experience, React.common and CK editor to get things packaging completely from a fork.

**Comment by abukres** [comment]
The source.zip and cloned repo both give the same error. I am not forking anything. dnn 9.2.2 works fine. 9.2.2 and the rc all use version 1.00.04 of the provider so something in this rc broke something and the installer now is broken.

Your command gives a 'Access to the path 'tools' is denied error'. I am not sure what the command is supposed to be doing.

**Comment by ohine** [comment]
Sorry, I mistook cloned as forked, that's my fault. 

The reason you're getting this error is because the source code needs to have it's version set, which Cake currently is doing in our devops workflow with the `GitVersion` cake target. 

If you want to produce your own installation or upgrade package and not use the official one, you'll need to run the following. 

`.\build.ps1 -Target BuildAll -ScriptArgs '--CkBranch="release/9.3.0"','--CdfBranch="dnn"','--CpBranch="release/1.7.0"'`

This will fetch the external extensions, set the correct version on all 50+ projects, compile, and should give you a nearly identical set of build artifacts to our official RC2 release.

As for the permissions error creating the tools folder, you will need to make sure the user running the command has write/delete permissions over the (sub)folder(s) you selected to store the source. 

We are currently working on updating the documentation to make sure people can compile and install locally as well as from our official packages. If you still run into more issues, let us know we we are happy to help!

**Comment by abukres** [comment]
Errors and errors. I am an admin on my machine. I am sorry but I have no time to chase down these issues. 
I am just going to use 9.2.2 for now. Hopefully in the future your releases work.

**Comment by nvisionative** [comment]
@abrukes there are multiple packages (install, upgrade, etc) for testing this release candidate.  Please use them.  There is no need to clone the repo and build the project locally in order to test the release candidate.

**Comment by abukres** [comment]
@nvisionative I want the full source because I am looking at the core code. I am not testing the rc. I expect all releases to compile and run properly. If 9.2.2 works and unless you guys made a breaking change to the build, I expect the rc to work as well. Take my issue here as a signal that the source release is broken and needs to be fixed.

**Comment by ohine** [comment]
@abukrea do you have any details on these errors? V9.2.2 and V9.3.0 are packaged nearly identically. The only real change between the two is how we are setting the version, in v9.3.0 we are using GitVersion. I’m guessing since the source zip isn’t connected to git it’s having a hard time detecting the current version.

**Comment by abukres** [comment]
@ohine   I deleted all the rc stuff from my machine. I am using 9.2 until the release of 9.3.  I don't know what source isn't connected to git means. The cloned repo had the same issue.

**Comment by valadas** [comment]
@ohine it looks like this build ps1 script should do every tep now and the only small issue is some case sensitive issue you told me. Are we near being able to publish how to build in the readme file, do you need my help on something ?

**Comment by valadas** [comment]
Also, I am closing this issue since it is pretty much the same as #2120 so let's have only one to manage. @abukres please follow the linked issue for a resolution on this matter. Thanks.
