### ISSUE TITLE
RFC: System changes username in a database when "Use Email Address as Username" is enabled

### ISSUE THREAD

**Issue by mikebigun** [dnnsoftware/Dnn.Platform#2621]
## Description of bug
When `Use Email Address as Username` is enabled, on a first login it authorizes user with email and replaces username with email address in database. Due to this username gets lost. After disabling this setting we are unable to use username anymore cause it was replaced in db. 

## Steps to reproduce
1. Log in with username: host 
2. In the Settings> Security>Registration Settings enable `Use Email Address as Username` 
3. Log out 
4. Log in with the email address associated with host and log out 
5. Try to login with username: host - not able to do it anymore 
6. Log in with the email address, disable the above option 
7. The username now is the same with the email address 
8. Try to change the username from email to host again - appears a message like the changes were saved but nothing happens 
9. Now you can only log in with the email address as it is set as a username

## Current result
When `Use Email Address as Username` is enabled, it changes username name in database and overwrites it with email address. Due to this, username gets lost and we can't reset it back to use username as login. 

## Expected result
When `Use Email Address as Username` is enabled, we should not be allowed to use username on login, only email address is allowed to be used.
When `Use Email Address as Username` is disabled, system should not authorize us with email address, only username is allowed.
It is important that we should not replace username in database. No data should be lost. 

## Affected version

* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

**Comment by thabaum** [comment]
Most all modern sites use email address along with phone number and/or username as well to allow users to log into the website.  I believe there is also an issue with using the unique email address only setting in web.config as this can only be applied to the DNN instance and not the portals or portal groups if added in the future.  You may wish to allow more users to register on seperate websites with seperate credential settings + profiles if you have this setting set no one can do this, however it would be nice to have this settting only applied for each portal or site group.  Because each portal is seperate a unique email for the single site portal only instead of for the entire DNN instance.  

With respect to this issue I have noticed this problem since using and it allowing email address as a username.  This issue has always been a topic of discussion with some of the things that happen when changing this setting back and forth cause.  

Another issues that is related is if you have another user with the email address already created and had the setting to allow users to have more than one email address while using username then switch to email as username... and back again that should mix things up while the setting to allow and not allow duplicate email addresses.  Then it really buggers up switching these settings around.

I believe there are also many topics about re-writting the DNN login module to be "modern" and this should be considered part of that topic with a solution that can cure all. Two way authentication and allowing other devices to connect using pin codes to approve them to be allowed to use the website.  

I would imagine being able to successfully switch these settings around with out bad issues or if there is a bad issue that could happen a warning is set to let you know you can't change back once you set a certain setting.

It would be nice to group all these topics/issues related to logging into DNN into one ticket for each set of suggestions to read up on anyones ideas and use the best approach that would work well and get all hands on deck to make it tight and right for todays world as each quality visitor is going to be using this part of the platform each and every visit first.  It should be one of the best experiences for users and administrators setting up the website.

**Comment by valadas** [comment]
This is totally worth discussion to agreement and then documented and writing tests and then stick to that decided behavior. There has been multiple small changes here and there not considering some use cases, let's do this right this time ;)

**Comment by mitchelsellers** [comment]
Lets add this to the agenda for discussion at the TAG meeting on 8/13

**Comment by valadas** [comment]
Merged
