### ISSUE TITLE
Update README.md to include links to Dnn.Releases.Archive repos

### ISSUE THREAD

**Issue by david-poindexter** [dnnsoftware/Dnn.Platform#2737]
## Description of problem
Currently, there are no links in the README to the **DNN Releases Archive** repositories.  This would be super helpful in pointing people on how to find older releases of DNN. 

## Description of solution
Add new section specifically for **DNN Release Archives**.  This section would contain a clear and concise list of all DNN Releases Archive repositories.

## Description of alternatives considered
n/a

## Screenshots
n/a

## Additional context
@dnnsoftware/approvers please assign this issue to me.  I'll submit a PR for it.  Thanks!

## Affected version
* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
I am closing this issue since:

1. I have updated all the links in the wiki suggested upgrade path to those archives instead of codeplex
2. The PR got cancelled since we don't want to suggest installing those old releases except as steps during the upgrade process to the current release
3. There is this issue in the docs project https://github.com/DNNCommunity/DNNDocs/issues/287
