### ISSUE TITLE
Digital Asset Module - Refresh button unhides "Action" menu

### ISSUE THREAD

**Issue by JaySMa** [dnnsoftware/Dnn.Platform#2790]
![Sub Folder 2](https://user-images.githubusercontent.com/11575998/57731260-46eb1a80-7668-11e9-9adc-3add9cf89d49.PNG)
![Root Folder 1](https://user-images.githubusercontent.com/11575998/57731261-46eb1a80-7668-11e9-82e3-8e85bd4c9ca1.PNG)

## Description of bug
Installed latest DNN version. 9,3.2.24

On a page, have the Digital Asset Management module on a single page.  Un-Authenticated users can view one folder and view the files within that folder; that's all.

When visiting the page, the refresh button is shown and when an unauthenticated user clicks on Refresh, the "Actions" menu appears.

I've also noticed that switching from the Root folder to a sub-folder causes the "Action" menu buttons to appear as well.

It makes it appears as though they can upload new files, create new folders, and the final button is disabled. But when they attempt this, it reports that they don't have permissions to upload, create, etc.

## Steps to reproduce
Log into the system as SU.
1.  Go to Site Assets and create a "Documents" folder and a "All Users" sub folder.
1.a.  Assign "All Users" browse and open permissions for both folders.
2.  Create a new page, assigned view for All users to see the page and add the "Digital Asset Management" module to the page
3.  In settings, configure set view condition for filter by folder and set to the newly created document folder, and include subfolders (show folder structure).  Update module.
4.  Logout of the system.
5.  Visit the page and click on either the sub-folder or the refresh button and "Actions" menu appears when technically, it shouldn't.

## Current result
Occurs with fresh installed DNN 4.3.2.24 version.

## Expected result
If the user doesn't have permissions to upload new files, create new folders, etc., these buttons shouldn't appear no matter what happens.

## Affected version

* [x] 9.3.2
* [?] 9.3.1
* [?] 9.2.2
* [?] 9.2.1
* [?] 9.2
* [?] 9.1.1
* [?] 9.1
* [?] 9.0

## Affected browser
* [X ] Chrome
* [X] Firefox
* [X] Opera
* [ ] Safari
* [X] Internet Explorer 11
* [ ] Edge

**Comment by JaySMa** [comment]
I discovered another issue which appears to be a permissions issue.

I have a "Document" -> "Child" -> "HR" folder layout configuration.

"Document" has "All Users" Browse Files in Folder and Open Files in Folder permissions.
"Child" has "All Users" with no permissions assigned to the folder; "Child Website Access" role has Browse Files in Folder and Open Files in Folder permissions.
"HR" has "All Users" with no permissions assigned to the folder; "Child HR Web Access" role has Browse Files in Folder and Open Files in Folder permissions.

Yet as an administrator, from within the Digital Asset Manager I can get the URL for a file within this HR folder, then go to another browser, enter the URL as an unauthenticated users and the file is loaded within the browser.  Uh, WHAT??!

Should it not be blocked for being viewed since I'm an unauthenticated user for which I don't have access to it's "HR" folder?   This is a MAJOR permissions issue.

**Comment by JaySMa** [comment]
Two weeks without any confirmation of this occurring with others or if this issue is going to be fixed.

**Comment by valadas** [comment]
The folder permissions for standard folders are only for the file manager. Unless you use a secure folder provider, any file that can be served by the web server (mime type) will be accessible by it's url. This is not Dnn specific, if you put files on a web server that can be served, they will be served. 

You can create secure folders
![image](https://user-images.githubusercontent.com/6371568/58607234-ca158e80-826c-11e9-8187-f0dc8814cad0.png)

And they will appear in the list with a small shield icon which will use special urls to serve them such as
http://dnn940alpha.localtest.me/LinkClick.aspx?fileticket=ZTqMZbptYpg%3d&portalid=0&timestamp=1559188174085
But keep in mind that anyone with that url will also be able to get the file, it is just more improbable to guess that url, a little like when you share a document using google drive or some such.

**Comment by JaySMa** [comment]
Originally this isn't the issue, but the issue with secure folder types is that the documents aren't indexed then with secure folders.  Need security where anonymous users don't have access to the files in folder (which DNN isn't accomplishing) and also ability for those authenticated with the system to search through indexed internal documents looking for certain criteria.

The original issue is that with the Digital Asset Module will show the Action menu (when a user doesn't have access to create or upload) when switching to sub-folders, etc.  This too is an issue.

**Comment by valadas** [comment]
> the issue with secure folder types is that the documents aren't indexed then with secure folders

If you mean indexed by search engines, that is correct, if they are secure they should not be indexed.
If you are talking about Dnn search, as far as I know the platform does not index files, only pages and modules that implement the search interface. (By default, pages, users and journal entries). If you use Evoq or a third party indexer, this may be different.

> Need security where anonymous users don't have access to the files in folder (which DNN isn't accomplishing)

It is not Dnn that does not accomplish this, on any hosting if you put files with a file type that is served, the file will get served. When using a secure folder, the files you save get a .resources extension appended to their file name making them not "servable" with default file types. Then to access them, you get a fileticket witch consists of a 12 characters base64 string I believe. This represents about 4 billion billions values. If you have a million secure files, it is still 1 in 4 million billions possibilities before hitting a valid id. This is pretty secure for web use IMO. If you need higher security for those files, then maybe you need a custom module or other means of distribution. Also, the folder visibilities can be set on the folder level settings in the permissions tab (right click on a folder name), if you make it not visible to all users, then it will not show until logged in into a role that has view permission on it

As for the action buttons, you are right, they should not show, there are plans to revamp this module and this needs to be fixed in those plans.

**Comment by sleupold** [comment]
AFAIK, DNN search does index files, but only properties, not the content (EVOQ feature)

**Comment by valadas** [comment]
I don't even think it indexes files (I am talking about the Dnn search)

![image](https://user-images.githubusercontent.com/6371568/58692029-b6952100-835b-11e9-85f6-be1c6029ac49.png)

**Comment by david-poindexter** [comment]
With the focus on a new file manager (currently under development by @donker and @valadas), we'll go ahead and close this issue.  Thanks guys!
