### ISSUE TITLE
Remove or update logo in distribution

### ISSUE THREAD

**Issue by Roylej** [dnnsoftware/Dnn.Platform#2837]
I suggest updating or removing the logo.gif file from the distribution. Example here:
https://www.dnnsoftware.com/images/branding/logo.gif

## Description of solution
Update to current branding or remove entirely.

## Description of alternatives considered
Alternative is to leave it as is. However it cheapens the brand and provides a vector for hackers.
## Screenshots
See kink above.

## Additional context
It's been reported by me many times over the past few years.
## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x ] 9.1
* [x ] 9.0
And previous versions.

## Affected browser

ALL browsers
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by MaiklT** [comment]
Thank you John for pointing out this - but this old logo could also lead astray the hackers as they try to hack a DNN 5.x site :-)
No, back to serious: that should really be deleted, as it is an excessive disclosure about the system - and when I may give my two cents, I would also remove the copyright message and the default keywords ("dnn", "dotnetnuke") by design.

**Comment by mitchelsellers** [comment]
It looks like this file is not referenced anywhere else in the solution, so it should be safe to remove.

**Comment by nvisionative** [comment]
I will happy take assignment of this issue and process a PR.  Thanks for finally reporting it here @Roylej
