### ISSUE TITLE
Please show all tabs when add a existen module

### ISSUE THREAD

**Issue by ufoloko** [dnnsoftware/Dnn.Platform#2838]
## Description of problem
When you have some tabs with child tabs, and root tab is disabled (main menu for example). when you want to add an existent module from any of those child tabs, in tabs tree is not showed. This because parent tab is disabled.

- To replicate create a page(menu), and then create a child page(submenu), and place some content. Html module for example
- Disable main page(menu)
- Create an additional page(location is not important)
- In this additional page, try to add an existent module from submenu. You will not be able to navigate to that submenu. Only option is to search submenu, but can be a problem if you have some pages with same name, in different parents.

## Description of solution
In other modules, you always show all tabs, ignoring disable state, this should be the same for "add existent module" function.

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser
All browsers

**Comment by valadas** [comment]
This issue duplicates #2594 and should be fixed by #2811 , if you can reproduce after 9.4.0 is release, please open a new issue. 9.4.0 is currently available as a release candidate that is not meant for production, if you do test with that RC, please take precautions (backup and local testing only, etc.)
