### ISSUE TITLE
Suppressing JQMIGRATE warnings when running DNN Platform

### ISSUE THREAD

**Issue by mikebigun** [dnnsoftware/Dnn.Platform#2855]
## Description of Problem
Running DNN Platform, there is a bunch of warnings in dev console displayed. They comes from JQMIGRATE script dedicated to ensure backwards compatibility when using newer version of Jquery. All warning are about compatibility of the latest JQuery 3.2.1. and other 3rd party JQuery libraries like JQuery UI 1.1.2.1 and etc. 
Alerts will be annoying until latest jquery will not be supported by all dependent scripts. Afterwards, they also should be updated in Platform.

Here I would like to get community vision on this and discuss whether we can suppress such warnings or not.

![image](https://user-images.githubusercontent.com/22524011/59758368-75c36480-9296-11e9-92e5-77a2cb91accc.png)

## Proposed Solution
More details about migration settings available at https://github.com/jquery/jquery-migrate

There is a `jQuery.migrateMute` setting available to suppress warnings. Console appears clear when enabling `mute` migration. See below:

![image](https://user-images.githubusercontent.com/22524011/59763966-6ac30100-92a3-11e9-8ad4-279b0b311eee.png)

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

**Comment by valadas** [comment]
I think muting it would be a big no in my opinion, we should analyse each of those warnings and at least use the newer api that does not trigger that warning or even better start rewriting what we can to not need jQuery where not absolutelly required. I am assuming a lot just uses jQuery 'because we can' and can be done very easily using normal javascript. I would like to dive into this for Dnn10 but if any PR comes in for 9.4.1, I think that would be welcome too.
