### ISSUE TITLE
Sitemap.aspx should use the 'industry standard' sitemap.xml

### ISSUE THREAD

**Issue by trouble2** [dnnsoftware/Dnn.Platform#2863]
## Description of problem
The default format for the sitemaps I believe is sitemap.xml and not .aspx
Even though it works under the aspx extension I think:
- it 'exposes' the technology used by the cms, so might even be considered a security issue
- the format of the document is xml, so the extension should be the same
- it is the 'industry' standard, so why should DNN behave differently....

## Description of solution
Create a handler for this.
I think Sacha Trauwaen has a good solutions in his OpenUrlRewiter I'm sure he's willing to cooperate: 
https://github.com/sachatrauwaen/OpenUrlRewriter/tree/master/Services/Sitemap
https://github.com/sachatrauwaen/OpenUrlRewriter/

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1

**Comment by sleupold** [comment]
this might be a performance issue, as .xml files are not necessarily processed by .Net

**Comment by mitchelsellers** [comment]
Please note, for any security concerns, they should NOT be addressed in the public GitHub repository for privacy concerns.

However, regarding this issue, yes the usage of SiteMap.aspx does disclose a bit about the technology stack, there are hundreds of other things that we cannot control that also expose the technology stack.   (Client Resource Management, Injected URL's, ViewState, etc.)

Changing to a handler that responds to sitemap.xml is a large breaking change, and introduces a performance hit and environment requirement for URL handling that we most likely do not want to undertake.

According to [SEO Moz](https://moz.com/blog/xml-sitemaps), one of the best sources for information on SEO issues, indicate that it is a standard practice to use a dynamically generated sitemap, and that it is totally acceptable to be a non XML extension.

The DNN Platform properly sets the response type and content and has a suggested hint in the robots.txt file to properly identify the URL.  

I do not suggest we change at this time due to the impact to the performance, existing installations, and the fact that we do meet accepted standards.

**Comment by thienvc** [comment]
You can fix custom sitemap.xml by IIS UrlRewrite, add to web.config:
<rule name="SiteMap" enabled="true" patternSyntax="Wildcard" stopProcessing="true">
          <match url="*sitemap.xml" />
          <action type="Rewrite" url="{R:1}sitemap.aspx" appendQueryString="true" />
        </rule>

**Comment by thienvc** [comment]
You can fix custom sitemap.xml by IIS UrlRewrite, add to `web.config:`
```
<rule name="SiteMap" enabled="true" patternSyntax="Wildcard" stopProcessing="true">
          <match url="*sitemap.xml" />
          <action type="Rewrite" url="{R:1}sitemap.aspx" appendQueryString="true" />
        </rule>
```

**Comment by mikesmeltzer** [comment]
@thienvc There isn't currently a dependency on the IIS UrlRewrite Module in DNN Platform. Introducing this would create a new dependency which I don't feel would be a good thing (I widely use that module btw, it's great!). That being said, for those who want to modify the URL in custom solutions, this sounds like a good approach.

@trouble2, given @mitchelsellers info regarding the current implementation meeting accepted standards and moving away from it would cause large breaking changes, can this item be closed?

**Comment by valadas** [comment]
I am closing this issue in the spirit of cleaning the backlog as per the previous comments
