### ISSUE TITLE
Location of 'Use Email Address as Username' setting

### ISSUE THREAD

**Issue by trouble2** [dnnsoftware/Dnn.Platform#2864]
## Description of problem
I was looking for the setting 'Use Email address as username'. 
And I found it under 
Security > Member accounts > Registration settings

So, I think logging in with my email address does not necesarily has anything to do with 'registration settings' so I would expect this to be under 
'Login settings' since this has more to do with loging in....

## Description of solution
Move the setting to Login settings

## Description of alternatives considered
Another option might be Security > Member accounts > Member management

## Additional context
Perhaps even consider setting this option to ON by default, since for a lot, if not most systems use email address as username nowadays....

## Affected version
* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1

**Comment by sleupold** [comment]
this is questionable, as it affects registration as well - whether a username needs to be chosen or not. There are arguments for both sections (but we should not duplicate the setting without need). Maybe a hint or a link would help?

**Comment by mitchelsellers** [comment]
This setting is under registration settings, due to the fact that we are defining how a user registers.  When this setting is turned on you are stopping the collection of a unique username, so it is truly a registration setting.

If the underlying behavior was different, it could make sense at Login, but since the setting changes the information collected at registration that is why it is located where it is.

**Comment by valadas** [comment]
Closing this issue since this is by design and as per previous comments
