### ISSUE TITLE
Some special characters cannot be used in passwords

### ISSUE THREAD

**Issue by fablaser** [dnnsoftware/Dnn.Platform#2867]
## Description of bug
When a user tries to change his password and it's mandatory the use of special characters, he cannot use "-" and "_".

## Steps to reproduce
1) You set these parameters in web.config:
minRequiredPasswordLength="8" minRequiredNonalphanumericCharacters="1" 
2) Try to change password to Banana_009. 
3) Repeat the password. 
4) You will see all checks green. The suggestions will say: "At least 8 characters - ok", "At least 1 non alphanumeric characters - ok"
4) Click on Change Password
5) After postback you will see an error saying that new password does not meet minimum requirements.

if you choose Banana.009, it will be accepted.

## Current result
Password not accepted

## Expected result
Password should be accepted

## Affected version
* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2

## Affected browser
Browser independent.

**Comment by sleupold** [comment]
please check the value of passwordStrengthRegularExpression in your web.config file (see documentation at https://docs.microsoft.com/en-us/dotnet/api/system.web.security.membership.passwordstrengthregularexpression?view=netframework-4.8

**Comment by fablaser** [comment]
Hello Sebastian, 
it seems that this parameter is missing in all my DNN instances. Should it be set?
Thanks

**Comment by valadas** [comment]
By default the system enforces at least 7 characters which all need to be alphanumeric, this can be overriden by adding that regular expression linked.

**Comment by dsjak-shie** [comment]
Hi @valadas , @sleupold, @fablaser ,

I ran into this same issue and think it is still applicable and that it should not have been closed. Can it be re-opened?
See here a screenshot of my membership provider configuration:
![image](https://user-images.githubusercontent.com/44951819/67762012-d4ee6e00-fa1a-11e9-8e36-c812237c719d.png)

As you can see I'm enforcing the use of capital letter and a number through the passwordStrenghtRegularExpression attribute. Furthermore I'm enforcing the use of at least 1 non alphanumeric character with the minRequiredNonalphanumericCharacters attribute.

With this configuration I'm supposed to be able to use the Banana_009 password, because an underscore is a non alphanumeric character. But it's not accepted. If I replace the underscore with a *,  so it becomes Banana*009, the password does get accepted.

Please re-evaluate this issue.

Kind regards,

Derek

**Comment by valadas** [comment]
@dsjak-shie can you please open a new issue following the issue template and including the affected version, thanks.

**Comment by dsjak-shie** [comment]
Hi @valadas, no need. I just saw that this issue was fixed in the following PR. https://github.com/dnnsoftware/Dnn.Platform/pull/3059

**Comment by valadas** [comment]
Awesome!
