### ISSUE TITLE
How do you uninstall theme?

### ISSUE THREAD

**Issue by mtran21** [dnnsoftware/Dnn.Platform#2871]
## Summary
Unable to remove/uninstall theme

## Extended description
I am not able to uninstall theme that is not using by my site.

## Steps to reproduce (if necessary)
List the steps to reproduce the behavior:
1. Go to 'Settings'
2. Click on 'Extensions'
3. Scroll down to 'Select theme'
4. No garbage can icon to delete.

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x ] Chrome
* [ x] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
When the delete icon is not present, it is usually because it is used somewhere.

To list all your pages with their theme assignments you can to to SQL Console and enter this script:

SELECT TabID, PortalID, TabName, TabPath, SkinSrc, ContainerSrc
FROM {databaseOwner}{objectQualifier}Tabs
ORDER BY SkinSrc

This will list you all pages ordered by the skin (theme) path, if you see it used there somewhere, then you have a clue which page is using it and can go change that before uninstalling the theme.

If there is a lot of them and need a script to automate that, let us know. You could basically remove all instances of that theme name for nothing using a single update statement

**Comment by mtran21** [comment]
> When the delete icon is not present, it is usually because it is used somewhere.
> 
> To list all your pages with their theme assignments you can to to SQL Console and enter this script:
> 
> SELECT TabID, PortalID, TabName, TabPath, SkinSrc, ContainerSrc
> FROM {databaseOwner}{objectQualifier}Tabs
> ORDER BY SkinSrc
> 
> This will list you all pages ordered by the skin (theme) path, if you see it used there somewhere, then you have a clue which page is using it and can go change that before uninstalling the theme.
> 
> If there is a lot of them and need a script to automate that, let us know. You could basically remove all instances of that theme name for nothing using a single update statement

Thank you, your script helped me find out which page or portal is using the theme. I am now able to delete to theme.
