### ISSUE TITLE
Breaking changes in RazorEngine

### ISSUE THREAD

**Issue by alenxmedia** [dnnsoftware/Dnn.Platform#3042]
## Description of bug
Changes to RazorEngine in v9.4.0 created some breaking changes when processing and rendering razor template. I have created and attached sample module to demonstrate this issue. This sample is working in all previous versions lower than 9.4.0.
I know there is already open issue: https://github.com/dnnsoftware/Dnn.Platform/issues/2997
But that did not solve this problem.
 
[TestRazorModule_1.0.0_Install.zip](https://github.com/dnnsoftware/Dnn.Platform/files/3671410/TestRazorModule_1.0.0_Install.zip)

## Steps to reproduce
List the steps to reproduce the behavior:
1. Install the provided sample module.
2. Put sample module on the page.
3. Check Admin logs for errors.
4. You can examine the sample module source code.

* [ x] 10.0.0 nightly build
* [ x] 9.4.1 nightly build
* [ x] 9.4.0 latest supported release

**Comment by valadas** [comment]
@ahoefling is this the kind of example you where looking for? I am no Razor expert, but this looks like it should work, there are a couple of typos but they are consistent...

**Comment by david-poindexter** [comment]
There is a great deal of information in the associated PR (https://github.com/dnnsoftware/Dnn.Platform/pull/2998).  Perhaps that will be of some help?

**Comment by alenxmedia** [comment]
@david-poindexter @ahoefling @valadas  Yes I have looked at PR(#2998) and PR(#2997). 
This module  example works on previous versions (v9.3.2 and lower). There was breaking change in 9.4.0. and this does not work anymore.

**Comment by Inka2015** [comment]
Yes we have the same problem with razor, eny solution?

**Comment by mitchelsellers** [comment]
@alenxmedia Thank you so much for submitting this example it helps us get a better understanding of what is happening here, and how we might address this.  There are a few thoughts, I'm also going to have @ahoefling review this as well.

1. For Dependency Injection to be working, we do need a default constructor for objects so that we can properly create using Activator.CreateInstance<T>.  We can look at a workaround for this, but long-term this is something that we will need to address.

2. This usage technically is not a supported usage of the Razor process.  You are using the DNN Razor Pages Engine as a templating system.  This is a bit of an API issue as this is not a recommended pattern, but the actual engine class was marked "Public" rather than "Internal" so it was possible for you to do this.  Given that you are not using any of the DNN features with this view, it would be recommended that you actually use the regular RazorEngine directly from ASP.NET rather than using the DNN one.  This actually benefits you greatly as there is a LOT of overhead with the DNN Razor Engine

We will continue to work on this to figure out the best route forward for 9.4.x, as well as the future versions of 10.x.  It is possible that we will have to drop Dependency Injection support for Razor3 in 9.4.x to accomodate this.  We will update ASAP

**Comment by donker** [comment]
The fix is pretty simple: add a parameterless constructor to any class that is used as T for DotNetNukeWebPage<T>. I did this in my own work and the rest worked exactly as before.

**Comment by iJungleboy** [comment]
Please note that I might just have had a similar issue with Dynamically Compiled WebApi Controllers. These are of course not in the DI catalog, so they cannot be activated with `Globals.DependencyProvider.GetService(type)` since they have never been registered. My issue was #3045 and the solution I found was to then create an instance and just ensure that anything it depended on could be generated from the DI. This is the code that fixes the WebApi Controller, maybe something similar will help here:
```
using DotNetNuke.Common;
using System;
using System.Net.Http;
using System.Web.Http.Controllers;
using System.Web.Http.Dispatcher;
using Microsoft.Extensions.DependencyInjection;

namespace DotNetNuke.Web.Api
{
    public class DnnHttpControllerActivator : IHttpControllerActivator
    {
        public IHttpController Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType)
        {
            // first try to just get it from the DI - if it's there
            return (IHttpController) Globals.DependencyProvider.GetService(controllerType) ??
                   // If it's not found (null), then it's probably a dynamically compiled type from a .cs file or similar
                   // Such types are never registered in the DI catalog, as they may change on-the-fly.
                   // In this case we must use ActivatorUtilities, which will create the object and if it expects 
                   // any DI parameters, they will come from the DependencyInjection as should be best practice
                   (IHttpController) ActivatorUtilities.CreateInstance(Globals.DependencyProvider, controllerType);
        }
    }
}
```

**Comment by ahoefling** [comment]
The use of the DNN Razor Engine directly is not a supported use. In the `View.ascx.cs` the Razor Engine is invoked directly which is intended to be used by DNN internals and not 3rd party modules.

Here is the code snippet in question
```
var headerRazorEngine = new DotNetNuke.Web.Razor.RazorEngine(ControlPath + "RazorTemplate.cshtml", ModuleContext, LocalResourceFile);
```

A simple fix that @mitchelsellers mentioned is using the ASP.NET Webpages Razor 3 engine which is what the `DotNetNuke.Web.Razor.RazorEngine` uses as it's razor implementation. 

If you want to go a DNN Module path, I would advise converting your module from Web Forms to MVC Module or a DNN Razor 3 Module (However, the Razor 3 module pattern is deprecated for removal in DNN 11.0)

**Comment by alenxmedia** [comment]
Thank you all for your time and responses.
Solution from @donker worked.

**Comment by david-poindexter** [comment]
I'll go ahead and close this issue since it seems to be resolved, but feel free to re-open if there is something actionable to be done.  Thanks!
