### ISSUE TITLE
DAM: Can't change folder type from standard to secure

### ISSUE THREAD

**Issue by kurtwilbies** [dnnsoftware/Dnn.Platform#3060]
## Description of bug
Can't change folder type form standard to secure in the Digital Asset Management Settings page.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Add DAM to a page
2. Click on settings gear
3. In Settings page, go to DAM settings tab and Scroll down to folder type and choose 'secure' as folder type
4. Save 
5. Reopen and you'll see that nothing is changed.

## Current result
See step 5

## Expected result
Dropdownlist value => secure

* [x] Chrome

**Comment by valadas** [comment]
@kurtwilbies was this tested in 9.4.1 ?

**Comment by kurtwilbies** [comment]
Ys. I tested this with the latest RC, 9.41.

**Comment by mitchelsellers** [comment]
I think this might need some additional validation, as I believe the issue is actually that the type is editable.  In prior versions, and for many reasons it might not be possible to switch a folder type once it is created.

For example, changing from Standard -> Azure isn't supported as the files have no way to get to Azure as they should, and all existing links would be broken.

Additionally, the concept of moving from Standard -> Secure would be greeted with the same limitation, how do all existing files get modified, and what about all broken links to existing resources.

**Comment by valadas** [comment]
I agree with @mitchelsellers on this being by design, changing folder types after their creation is not supported.

Also, the settings is to select the default folder type for new folders created within the module as explained in the label, this would not change anything until you actually create new folders.
![image](https://user-images.githubusercontent.com/6371568/66250573-982ca100-e712-11e9-98bc-3f345494b7d2.png)

Also, the dropdown saves for me in 9.4.1 so I cannot reproduce.

If your issue is that it does not save, then please check for errors in the browser console, the Admin Log or in the /Portals/_default/logs folder and open a new issue with those details or anything you may think would be different than a standard installation / environment since I cannot reproduce this. Thanks.
