### ISSUE TITLE
UX: The HTML Editor Manager doesn't fit in the Personabar

### ISSUE THREAD

**Issue by OllyHodgson** [dnnsoftware/Dnn.Platform#3065]
## Description of problem
The CKEditor configuration is obviosuly designed to be hosted on its own full-size page (a lot like the current File Manager). It's being loaded into an 800px wide iframe where it's very squashed. Users sometimes have to "double-scroll" (scroll the iframe, and an overflow box within it) to reach some very important functionality.

## Description of solution
Rebuild the management interface as a proper PersonaBar extension, so it fits and works correctly on this page. Ideas for saving space include making the sidebar collapsible, and putting the icon legend into help bubble, as per other "help" items. If possible, make it "responsive", so it adapts to fit a variety of screen sizes.

## Description of alternatives considered
1. Restyle the current interface to work a bit better in the constrained space. This feels a bit like 'polishing a turd' though.
2. Make the PersonaBar wider for this page (like the current Content > Pages interface). This feels like a short term solution, and doesn't fit well with the goal of making PersonaBar work nicely on mobile.

## Additional context
The HTML editor config manager is easy to use. 
It's styled to match the rest of the PersonaBar. 
It physically fits into the space provided for it.

## Additional context
I'm guessing this would need to accommodate HTML editor providers other than the default?

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

**Comment by valadas** [comment]
Additionally we should ensure the popup.ascx theme template is used regardless of the "enambe popups" setting, see https://github.com/DNN-Connect/CKEditorProvider/issues/130

**Comment by OllyHodgson** [comment]
@valadas Should that be a separate (related) issue?

**Comment by valadas** [comment]
Hmm, well yes and no, the problem here is the popup theme and the problem there is responsiveness... Sooo

**Comment by thabaum** [comment]
I was actually working on the CSS to make more use out of persona bar pages and responsiveness by screen size.  It just feels like some CSS should cure things.  Similar I think to the issue with the mobile login and normal login pages style differently but in modern browsers they really should be identical with some CSS changes for the different possible screen size views as needed to make things flow in the best possible way.  
I had moved a lot of CSS once experimenting with the personabar and making it 100% width.  I was also made the bar on the left smaller.  It would be nice to be able to dock it top bottom left right :).
I think everything should be one responsive design, no need for a mobile template and a desktop template anymore although still useful feature potentially if you really need full control of those situations.  Less theme files to manage is a bonus.
Would CSS fix here do the trick possibly if it was introduced to the entire persona bar.  
Maybe this is something for version 10 allowing some wiggle room for solution that might help cure the issue here as well as adjusting HTML editor and persona bar templates to work responsive in all currently known situations?
