### ISSUE TITLE
"Copy Permissions to Descendant Pages" Does Not Work

### ISSUE THREAD

**Issue by pjones235** [dnnsoftware/Dnn.Platform#3102]
## Description of bug
When I click "Copy Permissions to Descendant Pages" on a given page, and then click save, it does not copy the permissions and apply them to the descendant pages. This is about as straightforward as could be of an issue. This is on a fresh install of 9.2.2

## Current result
Page permissions are not copied to descendant pages.

## Expected result
I'd expect page permissions to be copied to descendant pages when I click "Copy Permissions to Descendant Pages".

## Affected version

* [x] 9.2.2

**Comment by valadas** [comment]
Yeah, after re-discussing this, the currently pre-saved permissions could be already different than the child pages and well there is no quick way to know if the button will or will not create a change. I think this is by design as it is rights now. Basically if you change permissions you need to save that before applying them to the descendants.
