### ISSUE TITLE
9.4.1 - Database prefix field is gone from installation wizard

### ISSUE THREAD

**Issue by lisaied** [dnnsoftware/Dnn.Platform#3131]
## Description of bug
9.4.1 - Database prefix field is gone from installation wizard.

## Steps to reproduce
List the steps to reproduce the behavior:

## Current result
Explain what the current result is.

## Expected result
Provide a clear and concise description of what you expected to happen.

## Screenshots
If applicable, provide screenshots to help explain your problem.

## Error log
Paste the error log that is related to this issue.

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [ ] 10.0.0 nightly build
* [ ] 9.4.1 nightly build
* [ ] 9.4.0 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
This is now by design, it was there in a time where hosting databases was way more expensive and this was a way to host multiple Dnn instances on a single database. This was discussed in the Technology Advisory Group and it was commonly agreed that in 2019, this is causing more issues than it solves today. For that reason it was removed from the install wizard. Note that this does not affect upgrades and that we are still testing for upgrades from versions with it (ObjectQualifier)

**Comment by lisaied** [comment]
Thanks @valadas, is it noted in release notes?

**Comment by valadas** [comment]
Looks like the issue did not get labelled Noteworthy so was not included in the release notes unfortunately, the original issue is here https://github.com/dnnsoftware/Dnn.Platform/issues/2657
