### ISSUE TITLE
DI stopped working after 9.4.0 update

### ISSUE THREAD

**Issue by jsbsantos** [dnnsoftware/Dnn.Platform#3140]
Hello.

I have updated a project that was using DNN 9.3.2 to 9.4.0 and my site has blown up with errors on all MVC controllers.

I tracked the problem to the dependency resolver not being able to resolve a dependecy. This is the constructor for one of the controllers that has stopped working.

`public DefaultController(ITabService tabService)
`

I am using simple injector as dependency manager and have so in the past with no problems. The code for my simple injector container registration is this:

```          
Container container = new Container();
container.Register<ITabService, TabService>(mixedScopeLifestyle);
container.Verify();
DependencyResolver.SetResolver(new SimpleInjectorDependencyResolver(container));
GlobalConfiguration.Configuration.DependencyResolver = new SimpleInjectorWebApiDependencyResolver(container);
```

From what I can tell, the new DNN 9.4.0 has introduced it's own DI and my guess is that it's messing with my implementation. 

Is this expected behavior? I saw no mention of this issue anywhere.

**Comment by bdukes** [comment]
@jsbsantos, yes, as far as I understand it, there can only be one resolver, and your resolver is being replaced by DNN's resolver.  You'll want to migrate your service registration code to happen inside an [`IDnnStartup`](https://github.com/dnnsoftware/Dnn.Platform/blob/cb5c2d05e3f0d54ebc0dd68a03b8ff708bae4c46/DNN%20Platform/DotNetNuke.DependencyInjection/IDnnStartup.cs) implementation.  So the above would be transformed into something like this:

```
public class Startup : IDnnStartup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddTransient<ITabService, TabService>();
    }
}
```

**Comment by jsbsantos** [comment]
Thanks for the answer but those aren't good news for me since I am using simple injector interceptors and other functionalities.

Simple injector's docs have a section on how to integrate with IServiceCollection: https://simpleinjector.readthedocs.io/en/latest/servicecollectionintegration.html. I tried what they suggest and it doesn't work.

Migrating to DNN DI is far from being the ideal solution. Will it support all the features I am using from simple injector? 

This seems to be a change that should have been explained in the release noted (it's just a line saying DNN now has DI, at least here on github) and have better documentation.

**Comment by bdukes** [comment]
@jsbsantos I'm sorry this is causing you trouble.  There's some documentation in the associated pull request #2774, as well as some documentation on the blog of the developer who contributed the feature, @ahoefling, starting with [DNN Dependency Injection: .NET Core](https://www.andrewhoefling.com/Blog/Post/dnn-dependency-injection).

@ahoefling @mitchelsellers any thoughts about supporting [decorators](https://simpleinjector.readthedocs.io/en/latest/aop.html) in DNN's DI or overriding the DI system with a third party?

**Comment by mitchelsellers** [comment]
I think that we can investigate any further enhancements for the management of DI as a whole, as long as it continues to align with our process to move forward.

DI has never been supported, or recommended, practice in the DNN world.  So for that, I'm sorry @jsbsantos that we have broken your implementation.  We did as much as we could with publicizing these changes, including a very long RC process.

I'll let @ahoefling chime in when he has a moment on options

**Comment by ahoefling** [comment]
@jsbsantos I'm sad to hear that you are running into problems with this. I have provided very detailed documentation on PR #2774 as well as a blog series that documents how to use the new Dependency Injection System
- [DNN Dependency Injection: .NET Core](https://www.andrewhoefling.com/Blog/Post/dnn-dependency-injection)
- [DNN Dependency Injection: MVC Modules](https://www.andrewhoefling.com/Blog/Post/dnn-dependency-injection-mvc-modules-constructor-injection)
- [DNN Dependency Injection: SPA & Web API Modules](https://www.andrewhoefling.com/Blog/Post/dnn-dependency-injection-spa-web-api-modules-constructor-injection)
- [DNN Dependency Injection: Razor3 Modules](https://www.andrewhoefling.com/Blog/Post/dnn-dependency-injection-razor3-modules-constructor-injection)
- [DNN Dependency Injection: WebForms Modules](https://www.andrewhoefling.com/Blog/Post/dnn-dependency-injection-webforms-modules)

I don't think those will really help since your project is using SimpleInjector, and I want to help to solve this problem with minimal changes to your code.

@mitchelsellers @bdukes 
I believe the appropriate solution is going to be extending our current Dependency Injection implementation to allow developers to use the container of their choice. As I type this a million edge cases come to mind that can cause a lot of damage. Since DNN is a platform of many extensions from various sources we could never guarantee they are all using the same IoC Container. So we have a few options

- Create a mechanism built into DNN that allows host users to select the type of IoC container they want to use. Most containers support the ASP.NET Core interface we are using. A downside to this approach is module vendors could very easily start conflicting with each other making common modules incompatible, which would be very bad
-  Allow module vendors to define their own IoC container which will register an additional custom container into DNN resolver. This would allow a module vendor to user their Dependency Injection using their own container. A downside to this is managing more than 1 container can get messy. As well as providing module vendors the ability to use their own container will start to increase the memory footprint of DNN

Adding decorator support for AOP style programming really opens up a large list of problems for the platform to support. I really like the technology, but I think the only way we can hook into it is if we can leverage the ASP.NET Core recommendations by Simple Injector, and if that works then great. But we can't forget about the side-effects and concerns that may introduce explained above.

(looking forward to further discussion on this)

**Comment by jsbsantos** [comment]
Thanks for the answers guys.

@ahoefling I've read the blog posts regarding DI but those were not helpful as my use case is different. I'm glad to hear you're open to look into this issue.

I understand the implications of what I am asking, but if there's a way to allow developers to choose their DI container, that would be great for us. I'm not sure how that would work though, because I don't know the specifics of DNN implementation, and I share your concerns that managing more than one DI container is troublesome and could be messy and generate higher memory footprint. 

Also, I would like to understand why the [SimpleInjector integration with ServiceColletion](https://simpleinjector.readthedocs.io/en/latest/servicecollectionintegration.html) isn't working. It seems like it should work, but it doesn't.

**Comment by ahoefling** [comment]
@jsbsantos 
Let's see what we can do to solve this problem, it will be a feature request and not necessarily a bug so depending where we land this might be something that doesn't get merged until 10.x. If we can add support to this without making any breaking changes with minimal risk I will push to get it in 9.x (all depends on the final solution we land on).

I have read through the [SimpleInjector](https://simpleinjector.readthedocs.io/en/latest/servicecollectionintegration.html) documentation you shared several times, and even pulled their codebase that is being used for the `ServiceCollection` Extension method. At first glance this looks like something that should work, but I think I might know where DNN is running into problems.

As a general rule DNN should support `IServiceCollection` extension methods like this in the `IDnnStartup` as these are the recommended extension points in the library which will simplify the .NET Migration. 

# My Working Theory
I believe we just haven't implemented support for what you are requesting, as all module patterns strictly use constructor injection. In the module pipeline we manually resolve the dependencies and construct the Controller for example. 

I think we may be able to solve this problem, but I am going to need more information

# What I Need
I need you to provide me a working code sample of the problem you are seeing with SimpleInjector which is not a code snippet here. I need an installer file so I can install it in a DNN website and the solution of demo project. If you can provide details on the features you are expecting to work as well and what isn't working now.

With that code sample, I can really investigate and research to provide appropriate recommendations

**Comment by ahoefling** [comment]
@jsbsantos 
It looks like we may have 2 concepts being mixed here (which is okay), and it will help me understand the appropriate fix if you explain a little bit more. In your initial code snippet there are 2 separate DependencyResolvers you set with the container:

```c#
DependencyResolver.SetResolver(new SimpleInjectorDependencyResolver(container));
GlobalConfiguration.Configuration.DependencyResolver = new SimpleInjectorWebApiDependencyResolver(container);
```

The first statement is used for assigning the DependencyResolver for MVC and the 2nd is for assigning the DependencyResolver for Web API. While the concepts are similar they are different and if you are using both modules it will be helpful to know.

- [StackOverflow Article](https://stackoverflow.com/questions/15494920/what-is-the-difference-between-dependencyresolver-setresolver-and-httpconfigurat) on Topic

Granted in a solution such as DNN it is perfectly fine to mix MVC and Web API (not implying anything negative by the statement).

This information is important to know since any fix will require updating both implementations of the DNN Module Pattern

**Comment by jsbsantos** [comment]
@ahoefling that's great news. 

I am using both MVC modules and Web API, that's why I am registering the container twice (one statement for each). I will provide you with a code sample on monday when I get back to work if I can't get it sooner.

Thanks for the helping me trying to sort this out.

**Comment by ahoefling** [comment]
I'm not going to be able to look at this until sometime next week at the earliest, so don't feel rushed.

In an ideal world you should never have to manually configure the containers like you did here. The DNN DI System should just pick it up and all you should worry about it registering the dependencies. The reason why your stuff isn't working is the container never gets registered correctly with DNN and by the time the `IDnnStartup` executes it is too late.

I have been going back and forth in my head on how to verbalize the biggest problem here. Consider a DNN solution with 20 modules and each module wants to use it's own Container. This will create significant management problems for the platform. 

I'm wondering if we add a Container Provider framework to the platform that is conceptually similar to the Authentication Providers, where someone can define what Container they want to use from a PersonaBar configuration screen. A problem with this approach would make it incompatible with other modules. **This is not an ideal solution, but wanted to document some thoughts**

### Module Specific Containers
Maybe we could create module specific containers, which is something I have considered recently. But this is complicated since you have a suite of modules and we would need the container to be registered to each of those modules.

@bdukes @mitchelsellers 
What are your thoughts on creating containers that could be used in 1 or more modules to handle this use case?

This really may be something we can't or is too complicated to support (full transparency)

**Comment by bdukes** [comment]
I think it's definitely worth investigating if we can integrate module-specific containers, but it probably ends up being a lower priority than some other work, e.g. Razor Pages support.

**Comment by valadas** [comment]
@jsbsantos Any news, is there some actionable thing to do with this issue or is this resolved?

**Comment by jsbsantos** [comment]
Hello.

I'm sorry about the time it took me update the issue but it's finally here. I have not resolved the issue in a satisfactory way, but I worked something out that was a compromise. 

I ended up removing the dependencies from my constructors and using the `DependencyResolver` class to get them instead:
`DependencyResolver.Current.GetService<ITestInterface>();`

This is not ideal but it was a temporary (i hope) compromise to our problem.

I hope this helps us move forward to find a solution to this problem.

I am attaching to this issue a test project that you can use to test the problem and an implementation of the simple injector. To run this, add the following line to the web.config file:
```
  <system.webServer>
    <modules>
      <add name="DependencyInjection" type="TesteSimpleInjector.SimpleInjector.SimpleInjectorHttpModule, TesteSimpleInjector" preCondition="managedHandler" />
...
    </modules>
...
  </system.webServer>
```

* [TestModule_00.00.01.00_Install.zip](https://github.com/dnnsoftware/Dnn.Platform/files/3893036/TestModule_00.00.01.00_Install.zip)
* [TestModule.zip](https://github.com/dnnsoftware/Dnn.Platform/files/3893037/TestModule.zip)
* [TesteSimpleInjector.zip](https://github.com/dnnsoftware/Dnn.Platform/files/3893040/TesteSimpleInjector.zip)
* [TesteSimpleInjector_DLL.zip](https://github.com/dnnsoftware/Dnn.Platform/files/3893046/TesteSimpleInjector_DLL.zip)
