### ISSUE TITLE
Cannot change sending email address from host@change.me

### ISSUE THREAD

**Issue by worldheadquarters** [dnnsoftware/Dnn.Platform#3168]
## Description of bug
On a new install of DNN 9.4.1 
The SMTP Server settings test sends an email with the return address as host@change.me instead of the email address configured for the super user account.

## Steps to reproduce
List the steps to reproduce the behavior:
On the personna bar:
Enter the appropriate email address for the superuser in the profile.

1. Go to 'servers : server settings : SMTP server'
2. Enter the appropriate information for your mail server
3. Click on 'Test SMTP Settings.'

## Current result
All emails sent have  host@change.me as the sender

## Expected result
Return address should be that of the duperuser (or perhaps another designitated actual address).

 may be helpful for resolution.

## Affected version
[X] 9.4.1  only one tested

## Affected browser
Not a browser issue

**Comment by valadas** [comment]
Hmm, just gave it a try, so 2 things:

1. The host email is the one in the UI to set the host settings, there could be multiple host users so the one used for the test email is the one in the email UI and not the actual email of any of the host users.
2. If you enter the settings and test right away, it uses the previously configured email, if you save and re-test then it picks it up. Keeping this issue as an improvement to use the one in the field instead of the previously saved one...

**Comment by worldheadquarters** [comment]
It is actually somewhat confusing, as I was not sure what the sending or destination addresses are supposed to be.  I assume the sending address  would be the one in the UI and the recipient address would be the address in the user profile of the user initiating the test.  (which seems to work, but the "from" field in the message source  is still host@change.me, even after saving, clearing the cache,  logging out and re-trying it. 

MIME-Version: 1.0
Sender: "World Headquarters" <admin@worldheadquarters.xyz>
From: host@change.me
To: jimb@empulse.net
Reply-To: host@change.me
Date: 18 Oct 2019 22:14:11 -0700

The little popup info box always says that the sender is host@change.me and i cannot find any place to change that.

**Comment by sleupold** [comment]
registration emails are sent from the admin account specified in Site Settings. if you left default values within the DNN install wizard, the first account will get assigned this email address in his user account.

**Comment by worldheadquarters** [comment]
I changed the email address in all the appropriate places.  In the message source of emails that were sent, as illustrated above, the email actually gets sent, but in the the message source"From" and  "reply to" do not change.  I do not see anywhere in "site settings" to specify an admin account for the site (Was this setting accidentally left out of the UI?).  Anyway, on this site (which I am using only for testing and theme development) there is only one account - Host.

**Comment by thabaum** [comment]
> . I do not see anywhere in "site settings" to specify an admin account for the site

![image](https://user-images.githubusercontent.com/13577556/67623688-26a9b500-f7dd-11e9-9ff4-42e14ffebe43.png)

this is related to my previous issues.  I have been giving thought and under Host settings you can supply an email.

I think an email account to be used should not be set to an admin account for registrations... then you have to make a separate admin account which I feel is a security risk as you use this only to set the email to be used for registrations as you may have another account that you like to use for communication as a moderator or administrator of the website instead of the one used for example noreply@domain.com or accounts@domain.com when the admin uses admin@domain.com or user@someotherdomain.com.

It has been an issue forever in my book and I must not be communicating it well enough although I keep trying.  I can probably find at least 10 posts related to SMTP and email accounts... I wonder how EVOQ handles this as I bet customers complained about it there as well but it got fixed.

**Comment by thabaum** [comment]
> Keeping this issue as an improvement to use the one in the field instead of the previously saved one...
@valadas 
can you do this for PORTAL settings as well as HOST settings?  Portal settings is missing this field.

**Comment by sleupold** [comment]
when you are specifying the "primary administrator" in site settings, the email address in his user account is used as sender.

**Comment by worldheadquarters** [comment]
Thanks to thabaum, I did find the setting in SECURITY.   In this installation, there is only one user, "superuser", but the "from" and "reply to" are still "host@change.me" although the email address associated with the superuser account is different.

**Comment by thabaum** [comment]
I feel the pain and I believe I have found the issue. I am trying to find out how to exactly get the email settings and so on.  While I am doing that I am also seeing where the hostEmail settings are set and setting these up to be used.  But I believe @valadas is working on something as well not sure getting used to putting things together here but I believe i have a few changes that can help in mind.

**Comment by thabaum** [comment]
Going forward if the PR is accepted you should be able to create a portal admin account that uses it's account for sending the mail.  Then create a second admin account to test sending emails to that you can edit the email address for that account to whatever you like for testing purposes.  The email will get sent to the current user with the test smtp request.

I would like to add an option to "Use Username for Sender Address".  And then maybe a way for controlling the email used for communications in one location if more are to be used to separate the types of notifications.   IE one from account verification might be different from the one you wish to use for a forum or for a newsletter.

It would be cool to be able to label and put an email address into the database and then a feature in modules could be to select which site email address to use for sending each type of notification.

A little much for now so much to chew on...  Security Administrator email to the SMTP area we could at least  put a help note letting administrators know to set the administrator email used for the portal under Security for the end user.

**Comment by valadas** [comment]
Merged
