### ISSUE TITLE
Update to latest json.NET version 12 from 10

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3199]
## Description of bug
Latest installations  of DNN show version 10 from 2017 installed.  I feel it should be upgraded to 12 to get latest bug fixes.
 
https://github.com/JamesNK/Newtonsoft.Json/releases

**Comment by bdukes** [comment]
I believe we're looking at updating dependencies in DNN 10 (since a major version upgrade could include a breaking change)

**Comment by mitchelsellers** [comment]
100% agree this would be a good item to review for 10.x

**Comment by sleupold** [comment]
Still an issue for DNN 10

**Comment by jeremy-farrance** [comment]
This issue needs to be re-opened or re-entered. The list of new features in Newtonsoft Json v11 and v12 are both amazing and useful and v13 released a few weeks ago. If it is already planned and/or taken care of for Dnn v10, then it can stay close, but otherwise this seems important.

Also, issue #3994 should be taken in to account since it looks like some PB extensions need their dependencies/bindings cleaned up.

**Comment by bdukes** [comment]
Yes, we plan to tackle this for v10

**Comment by OnesimusUnbound** [comment]
Version 13 is the recommended version as previous versions have security vulnerabilities. See https://github.com/JamesNK/Newtonsoft.Json/issues/2459

**Comment by bdukes** [comment]
Fixed via #5168
