### ISSUE TITLE
Ability for host to switch editing sites for areas that hold persona bar portal settings similar to Settings => Site Settings

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3246]
**Problem:**
A host account has to log into each portal to setup each SMTP portal from **Settings => Servers => Server Settings => SMTP Server**

 to Settings => Site Settings => SMTP Settings.

**Solution**
Security, SEO, Vocabularies, Connectors and Server for Portal SMTP Settings persona bar pages all have the same ability to choose a portal to configure with the Edit Site: host feature.

![image](https://user-images.githubusercontent.com/13577556/68270792-6eb5ac80-0013-11ea-837f-f3561a8036e2.png)

**Comment by mitchelsellers** [comment]
As much as I want to support this change, there are some serious security considerations here, as in the site configuration really needs to know if it is configured, however, all of this configuration information if set at the host level, should be considered confidential.  I think this would almost need a setting value to "allow designation at portal level" and would need to simply note "Already Configured at Host Level" or otherwise.  As we cannot show this information otherwise.

**Comment by valadas** [comment]
Well, the wiring should already be there since admins can already change that in the current module. I think the idea would be to move the admin part only to site settings and leave the host part where it is... But I agree we should not display the host settings and we need to let the admin know that filling that information will override the host settings for his site.

**Comment by mitchelsellers** [comment]
I do not believe that Administrators can set this value currently.  @thabaum correct, that is the reason for logging this issue right?

**Comment by thabaum** [comment]
![image](https://user-images.githubusercontent.com/13577556/68268454-1a0e3380-000b-11ea-8e87-b55c8c89abd5.png)

This being added to the pages such as SMTP Portal Settings, Security Settings and so on possibly?

**Comment by thabaum** [comment]
@mitchelsellers I am viewing this from a host account perspective, but not sure how the administrators accounts act.  I have not really looked at that as I am not sure if that is allowed or not.

**Comment by thabaum** [comment]
I suppose the ability to switch sites for the host on all the pages similar to site settings but also for Security, SEO, Vocabularies, Connectors and Portal SMTP Settings.  

Global is something that only a host should set and allowing a portal to have it's own settings that if turned on will allow a site administrator to set it would be a bonus.

**Comment by valadas** [comment]
Correct.

As a host, if you have 10 sites to set the smtp settings for (say you want different settings for each site), you need to:
1. Login as host
2. Go to servers => SMTP settings
3. Switch to site mode
4. Enter the info, test, save
5. Navigate to another portal
6. Login again because your authentication token is not valid for that domain
7. Rinse and repeat because it will not remember where you where.

Moving the site stmp settings would prevent those multiple logins and navigations since you can just change the site dropdown to view and edit the config site by site without any navigation/login 10 times.

---------

From an admin perpective, they can already view the Server menu => SMTP settings but they do not see the global setting, only this site smtp settings.

So for admins it would not change much but would save time for multi-tenant hosts to configure each site quicker. And semantically, it is both a site and host setting, smtp server lives both in HostSettings and in PortalSettings.

**Comment by valadas** [comment]
And just for completion the host settings are a fallback if the data does not exist on the portal level. So you just need to not display those fallback values to admins (as it is already the case now, we just need to keep that same security behaviour).

**Comment by thabaum** [comment]
I just tested and as a administrator I can edit the SMTP server settings.

**Comment by thabaum** [comment]
Sorry for the change you can switch it back if needed but I thought this would cover more issues being filed.

**Comment by thabaum** [comment]
OK made some final changes to the issue for clarity.

**Comment by valadas** [comment]
It would be a massive undertaking to wire that feature into every persona bar module. I think it makes sense to move some portal specific settings into the site settings module like the site smtp configuration, but it would be a lot of work for not much serious use case. Like making the pages module act the same makes no sense, you want to be on the actual site if you gonna work on pages.

I am not saying it is impossible but just unrealistic that someone would work weeks and weeks on this for free. As titled now, I highly doubt someone will pick it up.

**Comment by thabaum** [comment]
I suppose I meant just the ones I outlined for setting up and managing portal settings, nothing more.

**Comment by thabaum** [comment]
I will let you doctor up what I put for the feature idea to something practical.

**Comment by bdukes** [comment]
In DNN 8, admin users had no access to SMTP settings, even when configured in "Site" mode instead of "Host" mode.  A host user could set different SMTP configurations for each site, but the admin user wasn't able to view or edit that.  @mitchelsellers @ashishpd any idea whether that was an intentional change in DNN 9, to allow admins access to SMTP settings?

**Comment by thabaum** [comment]
I think this can get worked on one page section at a time add what is needed to site settings for an admin and what is needed for a host to control what the admin can or cannot see in respect to these settings.  Maybe a host only / admin eyeball like in registration settings for user profile.  Same type of feature for each feature the host is to control for each site.  And maybe a different color when administrator is enabled to see those settings so you are more alerted as a host who has what features enabled to allow modifying site settings.
