### ISSUE TITLE
Using React and other libraries for best practices DNN 10

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3263]
I am looking for some clarity on what to use for UI and other common things that maybe changing to keep things more ran in the core of the DNN Platform and less dependent on outside resources.

I would love to understand this fully so I can focus on what is needed in this respect to work solely with the DNN CE platform.  

An example is the issue with bringing the site groups module over to the persona bar.  I am hoping to know what are currently primary tools you know you can use in your developer tool set ahead of time that are most future proof.

**Comment by valadas** [comment]
Currently we have to deal with what's there and we just maintain it with the resources we have. Working with the persona bar now needs knowledge of node modules, webpack, React and Redux. Something very hard to teach in one issue like this. Now most of the common components are mainly wrappers for other publicly available react components which have their own dependencies so we get in a sub-dependencies hell and I do hate this. But it works and we maintain it for now. I would welcome any effort that reduces the amount of dependencies we have but this issue is a way too much wide net to be actionable.

**Comment by thabaum** [comment]
Great thanks.  Not looking for lessons or tutorials as much as just a good foundation to learn upon that will handle most all tasks.  React and Redux are two areas I was not sure of as I heard React is something you would look to be removing from persona?  But maybe I miss read.  I will research each one this helps clear my learning path.  I just dont want to use React and learn it finding out a year later to use some other resource.

This was the help I was looking for.  Unless someone has a little more to help cover what is to be used commonly in DNN.  So I suppose i was wondering if I should be using React or shy away from it as much as I can.  Sounds like using React is a must.  I am new to React so this will be fun :)

**Comment by valadas** [comment]
Unfortunatelly we do not have a great tutorial that covers everything. You have to dig into the code and trace and understand how things are wired up, the namespaces are mostly a good indication of what does what. If you have any specific you cannot find, feel free to comment but other than that, it is mainly digging around, the code itself has good comments in most areas (still needs improvements though).

As for React, this is what we have and we have to maintain it. I personally would love to have less dependencies on frameworks but for now with the resources we have, React is still around for quite some time :) Still a good thing to know about since it is basically modern javascript and jsx, something that for sure is a good thing to know even out of the react context.
