### ISSUE TITLE
requiresUniqueEmail="true"  will not allow you to register on two separate sites using same email

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3264]
## Description of bug

If you have two sites on one instance of DNN and use unique email you cannot register using the same email address on another site.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Create two sites
2. Set the web.config to requiresUniqueEmail="true" 
3. Try registering on both sites using the same email

![image](https://user-images.githubusercontent.com/13577556/68522139-c3983380-025c-11ea-89e7-b2c7734bdb8e.png)

## Current result
Error showing the email is already in use which would be odd for someone that has not used the site.

## Expected result
Ability for each user to register and log in into each site independently even when Unique Email is set.  Unique email should be per portal or portal group scope.

## Screenshots
If applicable, provide screenshots to help explain your problem.

## Error log
Paste the error log that is related to this issue.

## Additional context
Unique email should be a configurable setting for host, portal and site group.
Upgrading from DNN 9.4.0 to 9.4.2 went well so far things are working normal.  Was able to create this second site to test this and the email verification which worked great I am excited.  This issue and 2FA using email are my last main concerns.  UI for login and registration forms can be adjusted some as well.  Thank you!

## Affected version

* [ ] 10.0.0 alpha build
* [ ] 9.4.2 alpha build
* [ ] 9.4.1 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
This is currently by design since user accounts are instance-wide and users are only mapped to this or that portal. This has implications with multiple parts of the platform:
1. Requiring unique emails
2. Current inability to have the same user info for a different user on another portal.
2. Using emails as usernames
3. Portal groups
4. Switching any of the previous options on and off (and all possible combinations)

Dnn was built for multi-tenant way back then with even such options as hosting multiple instances of Dnn in the same database (using objectQualifier). It also had options for hosting multiple unrelated sites to kinda use Dnn as a hosting platform under a single instance.

Now this kind of setup was for in a time where server resources where very expensive (multiple databases and low ram/cpu cores, etc.) In this day and age, things have changed and we no longer recommend this kind of setup.

I for one use one Dnn instance per site unless it is some sort of micro-site setup where I know they are tightly related and knowing the limitations for user accounts and knowing that I could not upgrade Dnn or any module without affecting all those sites. This is the main reason I would never have two unrelated sites under the same instance.

I would personally welcome a change in this limitation but not at the cost of a huge breaking change or performance hit...

If you do have ideas on making this happen respecting those conditions, please open a new issue with something along the lines of "Allowing independent accounts per site" or some such.

**Comment by thabaum** [comment]
1.  Huge breaking change potentially but might be something that just allows you to use the old way... or go with the new of things.  That all depends how deep it can be thought about I suppose and how far it needs to go along with what would be allowable on a version change.  Feeling things out here.

The issue is the scope needs changed in a couple areas to make this happen.  And leaving things as is... is actually part of the solution.  For host level control for the entire DNN instance this is good. 

Possible solution?

Users are objects, portals are objects.  You would make a relationship between the two each with a foreign key to the other if I remember but I need to refresh here a little beyond my recent studies to get that all correct but just thinking this is a relational database schema and if you can make a switch that allows emails to be duplicated but each portal should have its own users. 
It is really messed up in my opinion I am seeing some very fugly things going on here IMO and a breaking change is a fixing change if that really needs thought of here.  

I was thinking more like adding a feature than changing things.  A new mode for portals that make them unique and separated more from other portals using the database and some UI controls with the logic as a tool to get it done if desired.   If site groups gets added it would need to link those sites up to unique emails allowed and if you have 10 site groups a person can register 10 times on 10 sites with Site Settings Unique Email setting.  The primary site of the site group would control these settings in a way as well.

I am really trying to dream up solutions that can keep things as is and allow you to choose.  It is one way or the other if you like... or even make another way just patch in here away you go.

**Comment by valadas** [comment]
I agree with the idea but this would be a massive change and need extensive review/testing on the actual changes. This connects with soooo much stuff like modules APIs, import/export, profiles, profile localization, site groups, stored procedures, sql views, admin modules, etc. I am sure I am forgetting some. The thing is, this is a massive undertaking that will need a big contribution and very extensive review/testing. Until we see the code that makes it happen it is hard to give a yes or no on it moving in.

There is a free sites group module at https://github.com/SCullman/Connect.Sitegroups it needs help making it work past Dnn 9.3 though, this is on my very long todo list.

Yes Dnn can support a huge lot of sites, I would'nt say I recommend it though :) It forces all of them to be on the same Dnn version and modules versions and god know that testing an upgrade on 4000 sites involves a huge lot of testing and if for some reason it breaks 2-3 sites, then you need to revert those 4000 sites.
