### ISSUE TITLE
how to build TaskScheduler.Web in webApps?

### ISSUE THREAD

**Issue by mnouraei** [dnnsoftware/Dnn.Platform#3268]
How to build TaskScheduler.Web in webApps?

**Comment by valadas** [comment]
If it is for debugging, then:

You will need to install node https://nodejs.org/en/
Then yarn https://yarnpkg.com/en/

Then in any of the folders that have a package.json in those webApps, you can run
`yarn webpack` which will give you a liveserver on some port like 8085 or some such (indicated when you run the command). Then what I find the easiest is to go to a local running site and edit the javascript that loads the real bundle so that it loads that version coming from the live-server.

From there it is quick to change something and test right away.

It is a bit outdated and if you find contradictions, prioritize what is written than what I say in the video (for instance AdminExperience was recently merged into this repository), but here is an example of that process : https://www.youtube.com/watch?v=oBhDqiQ9vOk&list=PLIx1M8IdVvqZ0bnODGqJyxvONNPj5BzMP&index=6

The other videos in that playlist also have to good info, but videos are hard to maintain, so any conflicting info you see, do not trust the video... :)

**Comment by mnouraei** [comment]
@valadas Thank, i add new custom control to in [`Dnn.React.Common\src`](https://github.com/dnnsoftware/Dnn.Platform/tree/development/Dnn.AdminExperience/Dnn.React.Common/src) and run script `yarn run build`.
How can I use it now?

**Comment by mnouraei** [comment]
and other question:
I need to enter moment-Jalali from https://www.npmjs.com/package/moment-jalali to convert date to Jalali date(persian date).
How does this work?
