### ISSUE TITLE
RFC: Connect GitHub Discussions with dnncommunity.org Forum Discussions

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3279]
## Description of Problem
The community that uses the forums and not github as much are not as connected to the discussions that are currently being discussed here.

## Proposed Solution Option 1
RFC types of discussions that get posted  should also put up a topic located in the forum with a new GitHub RFC category for them to be posted in. A link to the GitHub RFC issue along with a short description of the issue if not the full PR in the post. 

This can be an optional but recommended thing to do...

## Proposed Solution Option 2 (If Needed, repeat for more)
A way this automatically happens would be plus.  When an RFC is created a link to the forum post is made and a forum post with a link to github along with the RFC.  Dreaming :)

**Comment by valadas** [comment]
I think issues can be linked into the forums and ideas can live on the forums only until someone actually indicates interest in implementing them. It would move discussions in a place made for discussions and clean our actionable items backlog here and help move faster on items ready to implement.

Don't get me wrong, there are a lot of great ideas in here but they often are just a huge idea and not something a developer is ready to pick and do. Moving those in here only when someone actually indicates they will be developing them would save us a lot of management/triage time.

Ideally I would love to make a module in the community site a bit like UserVoice where people can search or create new ideas, vote for their top choices (like a 5 limit per user) so we also get a view of what people want the most, etc. But that won't happen from my part until next year, soooo in the meantime I would not mind at all if some large ideas get discussed in the forums instead of here.

**Comment by thabaum** [comment]
For now I am proposing a GitHub forum category for helping with getting RFC information from the community.  This is another Request for Comments on getting something together to help move discussions where they need to be and to help include everyone in the discussions.  

I am thinking more of getting people on github to comment but still allowing some comments that get posted on the forum get reflected by others noticing someone said it on the forum and quote them on github.

**Comment by thabaum** [comment]
I think I have an idea:

![image](https://user-images.githubusercontent.com/13577556/68628540-bdd96280-0495-11ea-9b7b-0b81d95f9533.png)

  A "Support" area in the forums for troubleshooting and add
--------------Community Support---------------
- General Support  ( Sooo much of this flooding "General Discussions"
- GitHub Issues

And use this area to also to help with community support and the GitHub PR and RFC posts and even explain how-to processes.
