### ISSUE TITLE
Mobile Friendly Textboxes

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3283]
DNN needs to be mobile first with desktops still in focus but phones and tablets are used the most these days.  

![image](https://user-images.githubusercontent.com/13577556/68717269-2f2f1900-055b-11ea-8db8-91962bd93de1.png)

Labels should go inside the text boxes to save valuable screen space.   The entire approach of the Admin Experience could be enhanced with this as well.  Making it easy to admin from a phone.  Persona bar could shrink.  

But really for the user forms such as login registration and profile fields they can all use a fixer upper to where the label for the textboxes is inside the textbox.

Is this a little too forward looking for DNN?

**Comment by mitchelsellers** [comment]
The primary use of a placeholder text or labels inside of the textboxes is not WCAG compliant without JS or other Trickery.  We have a requirement to retain WCAG compliance for UI patterns.

Additionally, again, for these items, we would need a scope/area/module to be updated for this to be managed.

**Comment by thabaum** [comment]
JS is a part of DNN right?  so this is what we need then.  

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_placeholder

looking at this example... what does DNN need to do this?

**Comment by thabaum** [comment]
I feel a breaking change here...  but I am dreaming of Version 11 right now being in good shape. If we can get this in v10 I would be excited.

Let me know what we can do for what version. We should try to make it happen.

**Comment by OllyHodgson** [comment]
@thabaum Forgive me if you already understand this, but placeholders and labels serve very different purposes. The label is to tell you what the input box is for (e.g. `<label>Email address</label>`), whereas the placeholder might give you an example of the content to put in the box (e.g. `<input type="email" placeholder="example@example.com">`). Placeholder in particular has its own set of accessibility issues, especially when developers try to use it as a label!

> Labels should go inside the text boxes to save valuable screen space.

I'd argue this is a stylistic choice. We should make it so theme developers can do this relatively easily, but I don't think it needs to be forced on everyone. I think there's two ways to approach it: Firstly, make sure the HTML structure of components like the standard login control lends itself to this sort of styling. Secondly, make those components templatable (e.g. using Razor), so theme developers can really go wild with their customization.

**Comment by thabaum** [comment]
Thanks for the clarity.  I suppose labels can just go away in my opinion for the common forms like the login form, and just use placeholders. At least for a mobile device maybe as screen gets bigger add the labels.

Like the "Search" area you dont need a label there, just a placeholder that says search.  It is the only place I think that does it.  I was just shooting for more of it across the board.  Labels in admin area are ok or places that need more explaining seems like the right place to put those.

DNN sites are the only sites I can find alive today that use labels on registration and login.  This I am sure will change by v11.

Thanks for the explanation every little bit helps me out here :)

**Comment by valadas** [comment]
labels are a must for screen readers. The way material-design implements it is they move the label visually inside the fields but there is still a label. But this is an opinionated style choice. I do not disagree on the fact that it both looks nice and saves screen real-estate for sure, but it would be a massive undertaking to implement everywhere and not break themes and third party modules that used the "recommended and never announced as deprecated" UX/UI patterns https://uxguide.dotnetnuke.com/

I think for any major style changes planned for future releases that could be a breaking change, we need a complete solution ready and submitted and we need a clear document to announce that change for third parties to be ready for them... I am not against progressive enhancements if they do not break existing implementations but it is very hard to approve or decline an overall idea like this without an actual working implementation as a PR to test...

I for one am against breaking changes unless they are absolutely required. If someone does want that look, this could be done on the theme level, we already have a wrapper around the lable and field, making the wrapper position:relative and the label position:absolute, one could place the label visually inside the field without a change in the markup or classes...

This is very quick and dirty but shows the overall idea:
Go to https://uxguide.dotnetnuke.com/UIPatterns/SimpleFormDemo.html and in the css pane, add the following:
```
.dnnFormItem {
    position: relative;
}

.dnnFormItem .dnnTooltip{
    position:absolute;
    left:0;
    top:0;
    width: auto;
    margin-left:15px;
}
```

And you now have your labels inside the field without a markup change.
![image](https://user-images.githubusercontent.com/6371568/68876961-45f87b80-06d3-11ea-94ea-129715cbc753.png)

I guess my point is this is an opiniated style and because of that it should be part of the theme, not something Dnn enforces. What Dnn needs is to provide just enough class names or ids to be able to select any element using specificity, keep on providing what is required at the markup level (like not removing the labels) and let the style be a theme thing. Sure we can change that on the theme level though, but many modules are in use today that are not expecting this kind of change. I for one try to isolate my modules styles as much as possible from the rest of the environment (default.css and theme), but this can't be said for many modules in use today.

**Comment by thabaum** [comment]
` I for one try to isolate my modules styles as much as possible from the rest of the environment (default.css and theme), `

This is what I found many modules developers doing and it leads to an inconsistent style of your themes... and a lot of work for a user to deal with, and support tickets trying to fix the issues.

I am really for simplicity.  And I do not want to put PR's together that are going to break anything.  As you shown a label can go in a text box.  Maybe something needs to be able to turn off that help box and turn it into a help tool tip for hover only.  

I am very forward looking with my issues/ideas looking on to .NET Core and trying to use this version and next to make things look very understandable and easy to work with for everyone.

I get a lot of updates or trying to fix a module and lose my CSS changes... over and over having to reset them while working on a site.   I hate the fact module developers are not consistent with DNN but understand why... dnn can change and break things.  But I see a lot of CSS from module developers writing over the basic themes and skins making thins a pain in the but for people like me that dont have the time to study everyones different approaches and styles everytime I see something out of place with the theme.  

I just simply start removing classes and colors from the CSS mod devs give me... and things work and look great.   It makes me laugh because if you go from a dark theme to a white theme and want to allow users to switch around the modules wont switch with it... get white text on white backgrounds and dark text on dark backgrounds.  Off tipic a little.  

On those examples... when you type in those text boxes do those labels go away?

**Comment by valadas** [comment]
> This is what I found many modules developers doing and it leads to an inconsistent style

The thing with styles is that they are always an opinion. There  as a lot of effort creating the Dnn UX/UI in hopes everybody would adopt that and we would have all modules follow the pattern. Now module vendors who did not like that opinion did their things and those who did follow now have outdated looking module because well, styles and trends change...

This is why I do not believe the platform should enforce styles, it should just provide what is required for a theme or module developer to have what they need to style it.

> On those examples... when you type in those text boxes do those labels go away?

This was a very quick and dirtty example, changing one element positioning/size depending on the focus state of another requires some javascript and is one of the main reasons where material-design weights about twice as big as bootstrap and bootstrap is about 10 times as big as a solution with plain css without js, etc.

Now as a theme developer some want a lot of design/animations/interactions and are less worried about the theme weight, some prefer a more static thing with a fast response, no dependencies, higher pagespeed. So this boils down to the theme preferences IMO.

**Comment by OllyHodgson** [comment]
> Thanks for the clarity. I suppose labels can just go away in my opinion for the common forms like the login form, and just use placeholders for special areas that need them. At least for a mobile device maybe as screen gets bigger add the labels.
> 
> Like the "Search" area you dont need a label there, just a placeholder that says search. It is the only place I think that does it. I was just shooting for more of it across the board. Labels in admin area are ok or places that need more explaining seems like the right place to put those.

As I said, they're different things for different purposes. As @valadas says, your users need you to label your input boxes. Remember that some people cannot see the screen at all, let alone realize it's a search box at first glance - for those people the screen is usually read aloud. We already know we have blind users who really struggle with DNN 9.x - so we absolutely cannot make things worse for them in a default installation 🙂 

If you really can't use a `<label>` element, you should use either another element (and link it to the `<input>` using the `aria-labelledby` attribute) or use the `aria-label` attribute (e.g. `<input aria-label="Search keywords">`).

All of which adds up to making these things (login controls, search controls) templatable 😄

**Comment by david-poindexter** [comment]
This is a great conversation.  However, it is very broad in nature and would be best handled elsewhere (e.g., dnncommunity.org forums).  Issues here on GitHub need to:

* follow the issue template format
* be specific (only one issue/enhancement/help item per issue)
* be actionable

This issue meets none of these criteria and therefore, we are going to close it.  Feel free to create a new issue that follows the above criteria.  We will try to do a better job moving forward to keep our issue backlog clean, concise and actionable.  Thanks!
