### ISSUE TITLE
Upgrades do not use SSL if SSL is enabled on the site

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3286]
## Description of bug
upgrade does not use SSL if SSL is enabled 

## Steps to reproduce
List the steps to reproduce the behavior:
1. upgrade.wizard without putting in HTTPS for the address
2. You will be directed to a non SSL page

## Current result
page directs to a non-ssl page

## Expected result
if the site has SSL enabled the upgrade wizard should use SSL since it is asking for credentials.

**Comment by david-poindexter** [comment]
@thabaum - this is an implementation issue rather than a bug in DNN Platform.  

Moving forward, would you mind asking questions on dnncommunity.org forums for clarity and education prior to opening GitHub issues?  It is vital to our continued success that issues opened on GitHub are clear, accurate and actionable.  Thanks!

**Comment by thabaum** [comment]
trying to use the forums more... I just feel if you have SSL enabled DNN should use it.  I always accidently miss that it is non-SSL makes me upset, change my password and stuff :) wish this was fixed but I guess I will just talk about it.

I wish there was a setting to make all pages SSL enabled.  I know the file manager is getting redone so I wont go there.  

I type in the upgrade url and it gives me a non-SSL page... bugs the hell out of me for years now.  No worries I can go rant about it on the forums :)

**Comment by david-poindexter** [comment]
@thabaum there is a distinction in DNN between SSL being **Enabled** and **Enforced**.  Also, most implementations utilize a CDN or IIS to handle an automatic redirect from HTTP to HTTPS.

You do bring up a good point about being able to manage each page's SSL settings in a more global fashion.  That would make a worthy "issue" in my opinion, but please keep the scope light and succinct so that someone can easily understand the enhancement idea and hopefully submit a pull request for it.

Thanks!

**Comment by valadas** [comment]
There was an RFC #2808 open since may, lots of discussions/ideas but no contribution came in. This is also something very complex because of different setups, one can have SSL redirect in IIS, others may have SSL termination on a reverse proxy or load balancer, a specific page needs to not be enforced because of some service or iframe, lockout possibility if the certificate fails, needing to install before setting up ssl, etc. It is complex for sure.

Another thing that comes to mind is that the install/upgrade wizard is kinda different than the rest of Dnn pages, it does not go through the same pipeline that would allow Dnn itseft to enforce it and may need to be done only in IIS.

The only way currently I see the upgrade using ssl is to enforce https redirection at the iis level like this https://stackoverflow.com/questions/9823010/how-to-force-https-using-a-web-config-file

But that could not work if the ssl termination is not in IIS and the communication is only encrypted between the outside world and the load balancer and is http internally... Something that is unfortunately common.
