### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3291]
Is there a way we can have a place for known issues and what version of DNN release they are associated with with possible resolutions, or is there one already?  Maybe on DNNDocs possibly?

![image](https://user-images.githubusercontent.com/13577556/68883676-5c4c0a80-06c6-11ea-86c0-6d05129dfb31.png)

I have this issue with one I cannot delete I need to sift through the issues to find the resolution.

**Comment by valadas** [comment]
Search github issues? Am I not understanding the question correctly?

**Comment by thabaum** [comment]
Well, to resolve this issue Brian put up a way to fix the issue of not being able to uninstall a persona bar item... i will dig it up in a few.  Can we put helpful stuff like this that resolves issues like the persona bar modules not being uninstalled during upgrade and other issues so we can reference these before putting up an issue request.

**Comment by david-poindexter** [comment]
@thabaum here is the basic flow:

* "Issues" are reported via GitHub  
* "Issues" are fixed via "Pull Requests"
* "Pull Requests" are merged into "Branches" that then become "Releases"
* "Release Notes" reference all "Issues" that are addressed for that "Release"

That said, it seems you are having an issue deleting an Extension within DNN.  If you are referring to **Dnn.PersonaBar.TaskScheduler**, trust me in saying you don't want to delete this.  It is a vital DNN feature that cannot be deleted.

Moving forward, please understand that this GitHub repository is not a **Help Desk**.  It is for reporting single, manageable, specific bugs or enhancements.  It would help our team a lot if you could post these types of questions on the [DNN Community forums](https://dnncommunity.org/forums) instead of here on GitHub.  Thanks so much!

**Comment by thabaum** [comment]
![image](https://user-images.githubusercontent.com/13577556/68885792-b64ecf00-06ca-11ea-82da-49e59c6a6b36.png)

All of the persona bar modules are in one package now I thought...

**Comment by thabaum** [comment]
This is a known issue... where do i find it?  Or I can simply put up an issue... this was for "Help" as this is what I selected.  And it is with GitHub help IMO.

![image](https://user-images.githubusercontent.com/13577556/68885973-029a0f00-06cb-11ea-8262-fcd9b7a5dd64.png)

**Comment by thabaum** [comment]
Lets get one thing clear... i am not here to bs

**Comment by david-poindexter** [comment]
@thabaum no problem - I didn't mean to upset you.  We will discuss in more detail on our call in a few minutes.  ;-)

**Comment by thabaum** [comment]
Cool no worries just want to be sure I am trying to address issues here, discussions on forums and dnndocs for the how to stuff that is involving with DNN and help keep issues from coming up again and again... so this was the "Help" request and I felt it would be good to speak about it here.  It will all pan out eventually so it is very clear where we should post things.  I understand the clutter and I have no problem having PR's refused or discussions closed.
