### ISSUE TITLE
Stopping Localize Content for no standard pages

### ISSUE THREAD

**Issue by arminrahimian** [dnnsoftware/Dnn.Platform#3300]
## Description of bug

1. When you start Localize contents, and there is some Disable pages or no standard pages like URL pages, Localize not finish and stop  and you should localize pages manually one by one.

2. If you have some modules that they checked for "view in All pages", they will duplicated in Default languages and need to delete all duplicated modules.

3. The Link of Logo of Second Language will Redirect to Default Language HOme page. It's Wrong, It should Redirect to Home of Current Same Language.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to 'Settings'
2. Click on 'Languages'
3. Add your New Language
4. Active "Users May Choose Interface Language"
5. Active "Allow Content Localization"
6. Click on "Enable Localized Content" to Start Action to create and generate all pages in new language
7. If you had "Disable Root Item Pages" include some pages inside or some sample URL pages (No-Standard page) you will see the progress will stop and not been complete and no show any error message also and you will confuse that what's happen.

## Current result
The result is, some pages localized already but other pages not. localized content progress not completed and some pages that localized, had problem for some modules duplicated because they are "view on All pages" modules.

## Expected result
Provide a clear and concise description of what you expected to happen.

## Screenshots
If applicable, provide screenshots to help explain your problem.

## Error log
Paste the error log that is related to this issue.

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version
DNN 9.4.1

* [*] 9.4.1 latest supported release

## Affected browser

* [* ] Firefox

**Comment by valadas** [comment]
I cannot reproduce this on 9.4.2, can you explain what you mean by "Disable Root Item Pages"

Also this issue is a bit broad and has 3 separate things to it.
1. The logo redirecting to the wrong language (I cannot reproduce)
2. Localization of url pages, this is expected behaviour in order to localize the page name and settings per locale.
3. Display module on all pages: I had no duplications, this was also reported in #2426 and we never got clear steps to reproduce this issue, to be honest I had this issue on some old sites but could never reproduce accurately, so must be some data inconsistency or the module was displayed on all pages + some other independent instances or some such, but nothing we could accurately reproduce and make it an actionable item.
4. "Users May Choose Interface Language" this is a known issue currently as the language switcher was never built into the persona bar. See #3100 

For easier management can you for each of those 4 items:
1. Search if there is already an existing issue.
2. Open a separate issue just for one thing at a time
3. Make sure it can be reproduced on 9.4.2 clean site or a clean install from previous upgraded to 9.4.2, sadly if that cannot be reproduced in such fashion, it is something with that specific site that will need more digging into the cause and finding how to make it happen from scratch.

**Comment by arminrahimian** [comment]
When I tell "Disable Root Item Pages" I mean for example I have "Service" page name in menu root item. and there is 4 different page names under this "service" page like "Service name 1" and "Service name 2" ... up to 4.
So I don't want the Root Item can click by users. so I will go to pages and I will Disable this page. then you will see this Item UN-clickable but sub pages Clickable.
If you had some pages like this, when you start "Localized content"... It will Stop and could not localized these disable pages.

1. 
for next question. About click on logo in one second Language For example "English" as a second and not default language, then redirect to wrong URL in Default language for example "Farsi" as a Default Language. If you want change default English language to another language you need change "Default Alias" to "Farsi" for example. Also we have Alias Fa-IR to "Farsi", both are Farsi. and the En-US is for English only. In this case you will see that wrong url redirection effect.

2. 
I had 55 pages for localized content, but after localized only 6 pages, it was STOP and never progress complete and I create all localized pages manually one by one. I think the because I had several pages with External URL (not standard page) or Disabled root item pages.

3. 
Display module in all pages was duplicated in Default language not in new language. my default language was not English. it was "Farsi" and then I create second language for English.

**Comment by Timo-Breumelhof** [comment]
@arminrahimian Please split this up in separate issues an post links here.
I have had the issue with the logo before.
Both times it was a DB issue. How that issue was created I don't know TBH.
