### ISSUE TITLE
Login redirect in ssl offloading scenario issue(mixed content)

### ISSUE THREAD

**Issue by lnu** [dnnsoftware/Dnn.Platform#3312]
## Summary
In an ssl offload scenario, after login the user is redirected to http instead of https.

## Extended description
We have a dnn instance running behind an F5 reverse proxy. The f5 takes care of the ssl and the communication between the f5 and the dnn server is in http. The SSL Offload Header Value parameter is set and everything works as expected excepted except one scenario. If we go to another page than the home page and try to login, we have a mixed warning content error. When I check in the devtools, I see the 302 redirect but with a location starting with http:// instead of https://

## Steps to reproduce (if necessary)
List the steps to reproduce the behavior:
1. Go to a page other than the home page
2. Click on login
3. Type the username and password
4. Click login
4. Check the console and see the mixed warning content.

## Current result (if necessary)
302 with a location starting with http://

## Expected result (if necessary)
302 with a location starting with https://

## Screenshots (if necessary)
![dnnlogin](https://user-images.githubusercontent.com/1829553/69129188-32bc2600-0aae-11ea-8fc4-ea288eb34859.gif)

## Affected version

* [x] 9.3.2

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
I do not have a proper environment to test this but I have been told two things.

1. It should work if you setup the sll offloading header, see https://www.dnnsoftware.com/docs/administrators/troubleshooting/ts-mixed-content-ssl.html the screenshot shows Evoq but this also applies to platform and the screenshot does not show the field, here is another screenshot more representative to where to put it:
![image](https://user-images.githubusercontent.com/6371568/69129710-f8866080-0a7c-11ea-8a5f-f541d61d0966.png)

2. Disabling popups is a workaround for this and another place (can't remember now) where ssl offloading does not work unless you have that header setup... There is no UI to change this setting but you can open the sql sonsole in the persona bar and run the following:
```
UPDATE {databaseOwner}[{objectQualifier}PortalSettings]
SET SettingValue = 'False'
WHERE SettingName = 'EnablePopUps' and PortalID = 0
```
replacing 0 with your PortalId, if you want that on all your portals, then skip the `and PortalID = 0` part

Another workaround is to create your own login page (can be called logon or sum such) then place a login module on it (and other content if you so wish) and after that go to `Site Settings` => `Site Behaviour` and set the `Login Page` to your new logon page (only pages that have a login module show in that list), be careful to not delete that login module or you might get locked out and need some more sql to fix :)

So, let us know if the ssl header fixes the issue, then this works by design, if not we can troubleshoot further..

**Comment by mitchelsellers** [comment]
Right now, the best recommendation for this is to make a custom login page, rather than using the automatic page.  This is a limitation of the PopUp control and behavior of the site.

**Comment by thabaum** [comment]
is there any documentation that can be used to follow for future reference on this topic?

Possibly in the troubleshooting area something for this could be included for the work around?  It would help out those in need until it can be resolved.

**Comment by valadas** [comment]
@mitchelsellers for triage, is this a bug or some limitation we cannot get around? Does this work with the ssl offload header and just needs better documentation? What do we do with the issue basically? :)

**Comment by mitchelsellers** [comment]
@valadas Thi sis the same limitation as we have already tracked, with regards to requiring a custom login page for SSL to work.  (Also applies to offloading.)

**Comment by lnu** [comment]
@valadas The Ssl offload header value is set and it's working fine except for the login popup(and only a page different than the home page)

**Comment by valadas** [comment]
Ok, cool so it is not just having the ssl offload header, I gonna make this issue a bug then...
