### ISSUE TITLE
Form Messages are not using 100% of screen

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3387]
## Description of bug
form messages can only expand to 980px

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to a page that has administrator only form message

## Current behavior
for high resolution screens this message is not expanding across the window.

## Expected behavior
The message area uses all of the allowed space.

## Screenshots
If applicable, provide screenshots to help explain the bug.
![image](https://user-images.githubusercontent.com/13577556/70355667-8f963b00-1827-11ea-89d0-c60f1ac4a50b.png)

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version

* [ ] 10.0.0 alpha build
* [ ] 9.5.0 alpha build
* [ ] 9.4.3 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by bdukes** [comment]
I think this is an intentional design decision to restrict the form messages from growing too large.  If you want them to be 100% in your site, you can override the styles via your theme or the site's stylesheet (i.e. `portal.css`).  My opinion would be that this is _not_ a bug/defect and should remain as-is.

**Comment by thabaum** [comment]
ok no worries just looked odd on the form.  Felt like it should use the full screen or space allowed in the skin template instead of cutting itself off.

**Comment by valadas** [comment]
Well, this is certainly an opiniated thing but I think the default of 100% and people can override it if they want is better than a fixed default and people can make it otherwise. 100% is certainly more consistent IMO Very ofter with css frameworks, the forms measure like around 1050px wide with the default 980px it looks like it is just missing a little bit... I marked is as an enhancements and approved the PR but if there is traction to not merge that, please comment...

**Comment by valadas** [comment]
PR merged
