### ISSUE TITLE
Not all module versions change in upgrade from 9.3.0 to 9.4.4 version

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3389]
## Description of bug
The module version for the following are at 9.3.2 instead of following the current version number:

- Authentication
- Registration
- Search Results
- Users and Roles
- View Profile

## Steps to reproduce
List the precise steps to reproduce the bug:
Upgrade from version 9.3 to current 9.4.3+

## Current behavior
Not all modules are changing version to match the platform version

## Expected behavior
DotNetNuke module versions change with the platform version.

## Screenshots
If applicable, provide screenshots to help explain the bug.
![image](https://user-images.githubusercontent.com/13577556/70394976-2ccfab80-19af-11ea-8e7d-724a512269b4.png)
![image](https://user-images.githubusercontent.com/13577556/70394980-35c07d00-19af-11ea-9abb-f0c9d664f0e8.png)
![image](https://user-images.githubusercontent.com/13577556/70394986-43760280-19af-11ea-8ab8-510d12714586.png)

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.

## Additional context
Not sure if this is right or not so this issue can be closed if it is an expected result.

## Affected version

* [ ] 10.0.0 alpha build
* [ ] 9.5.0 alpha build
* [ ] 9.4.3 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
I still see this in current pre-release for 9.5.0

@donker I though this was resolved as part of another issue with the versioning and build reorganization. I remember we had a talk about what was and what was not handled by manifests... I remember there was a piece of sql to handle those, was that a one time thing or do we have a broken piece that ran in 9.3.2 and stopped running after that ?

This is only a style issue because those packages are built-in and not really module packages that need to run on upgrades. In other words, everything still works fine, it just is inconsistent display...

Another idea that comes to min is maybe simply displaying current Dnn version for those that have no manifests... I am not sure if there is a way to find that out in the list though...

**Comment by mitchelsellers** [comment]
Adding to this, it also appears that this is the case for all of the default SkinObjects they are pinned at Version 9.3.2.

**Comment by valadas** [comment]
Yes, pretty much everything that has no manifest but is still registered as an extension. @donker I remember a PR of yours regarding this, could we call that SP upon each dnn upgrade maybe?

**Comment by david-poindexter** [comment]
Is this still a valid issue?  I seem to remember some build enhancements that addressed this, but need confirmation.  CC @valadas

**Comment by valadas** [comment]
There was a PR for this, but it is not working on each version, still needs some work... 
![image](https://user-images.githubusercontent.com/6371568/84094552-1096e080-a9cb-11ea-8069-8088ab4360fc.png)

**Comment by valadas** [comment]
This was resolved in 9.8.x as part of another issue about this.
