### ISSUE TITLE
.net core 3.1 support

### ISSUE THREAD

**Issue by j209** [dnnsoftware/Dnn.Platform#3428]
Hi
any plan for .net core 3.1 and blazor  support?

**Comment by mitchelsellers** [comment]
We are working towards an eventual goal for .NET Core support, however, it is quite a distant item at this time due to the fact that the main technology (WebForms) is not supported on .NET Core 3.1.

We are working to clean and reshape API's etc to start a transition in the next few major releases.

(Closing this issue as we have other issues to track this)
