### ISSUE TITLE
"portalSettings no null" issue on SourceCode package 

### ISSUE THREAD

**Issue by dhrumit001** [dnnsoftware/Dnn.Platform#3498]
Hello sir,
i  downloaded code SOURCE CODE from https://www.dnnsoftware.com/ which is version 9.1.1
after download i open code in vs2017, and run successfully 2 step(db install) in 3 step i got error like 
"portalSettings is null". if i download INSTALL PACKAGE it's working find but issue on Source code package

please help
Thanks

**Comment by EPTamminga** [comment]
www.dnnsoftwarecom is **not** the location for the source of DNNPlatform. 

The DNNCommunity, the community for open source DNNPlatform, took control of the DNNPlatform source code about 2 years back.

This GitHub repository is the only up to date resource for the source code of DNNPlatform. If you want to do source code manipulations, use the GitHub principles for Fork and local Clone of repositories.

For installing DNN there is **no need** to do anything with source code. Just go to the releases tab of this repo and download an install pack of DNNPlatform.

**Comment by dhrumit001** [comment]
Hii EPTamminga,
Thank you for your answer,
i tried to download latest DNN 9.4.4 version and same got same error as i posted above .
please help

Thanks

**Comment by sleupold** [comment]
I strongly suggest using install package and follow install instructions. Source code is only needed for contributing to the Open Source DNN Platform, not for running the site or developing extensions.

**Comment by EPTamminga** [comment]
@dhrumit001 
### Go here: https://github.com/dnnsoftware/Dnn.Platform/releases
and download this:

![image](https://user-images.githubusercontent.com/5859855/72616238-cb4c1680-3936-11ea-89d7-0947baa41cb4.png)

And you should ready to go,

## DO NOT DOWNLOAD THIS:
![image](https://user-images.githubusercontent.com/5859855/72616262-db63f600-3936-11ea-9798-43971561e783.png)

Since that zip is only for back-up/archive purposes and not for development.

If you want to do development (which is only needed of you want to contribute as open source volunteer, follow the Git(Hub) way of working: fork, clone.

**Comment by dhrumit001** [comment]
@EPTamminga ,@sleupold

Thanks for your valuable reply..

**Comment by valadas** [comment]
Awesome, I am closing the issue as it is not an actionable thing for development on our side. This does not mean that the discussion is blocked, so feel free to comment if you run into issues after this, we will the participants will still be notified about your comment.
