### ISSUE TITLE
Getting nuget.tragets not found issue on DNN 9.3.2 Source code

### ISSUE THREAD

**Issue by dhrumit001** [dnnsoftware/Dnn.Platform#3508]
## Description of bug
Provide a clear and concise description of the bug.

## Steps to reproduce
List the precise steps to reproduce the bug:
3. Scroll to '....'

## Current behavior
Explain the current behavior.

## Expected behavior
Provide a clear and concise description of the expected behavior.

## Screenshots
If applicable, provide screenshots to help explain the bug.

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version

* [ ] 10.0.0 alpha build
* [ ] 9.5.0 alpha build
* [ ] 9.4.4 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by dhrumit001** [comment]
Hello sir, 
i downloaded DNN 9.3.2 source code version but it's getting me error like .nuget\nuget.targets not found in VS 2017
please help

![image](https://user-images.githubusercontent.com/11158042/72718577-364a5700-3b9c-11ea-89f8-16c4d25e5f06.png)

**Comment by valadas** [comment]
Sorry, this issue is lacking details to understand, please open a new issue and explain each and every step you took to get into that problem.

Also, you do not need the source to use Dnn, you can get the releases from this page https://github.com/dnnsoftware/Dnn.Platform/releases download the install package or the upgrade package, the source package listed there is not to be used, unfortunately github auto-generates it.

If you do need the source to submit a pull request or other reasons, then you would first fork this repository, then clone it to your local machine your git.
If you do need the source for such purposes, please explain your intetions too in that new issue and we can further assists knowing what you need to do.
