### ISSUE TITLE
Ability to install multiple modules at once.

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3551]
## Description of problem
Installing a module creates an application pool recycle downtime period.  Installing more than 1 module takes a bit of time.

## Description of solution
Create a solution that allows installing multiple modules at one time to limit the number of times the website needs to be recycled.  When installing modules you can drop one or more module and auto accept terms and conditions to allow the installation of new and upgraded modules to complete in one installation process with one application pool recycle.

## Description of alternatives considered
Using the install folder method works however it would be nice to be able to install a package of packages possibly.  Zip all of the modules together into one zip with the other module zip files and install them.

## Screenshots
Allow dropping zip files with multiple module installer packages here or allow dropping them one at a time populating a list below and allowing you to set the order of them here with a table you can drag to the number the order of module installation or on the next step 2 of 5 make an additional step to do so and select check box for auto complete installs remaining steps and install all modules or something to that effect...  

![image](https://user-images.githubusercontent.com/13577556/74056815-8a747a00-4997-11ea-8af6-dc1b86d7a0d6.png)

## Additional context
It would also be nice to be able to check box select modules and uninstall more than one at once to limit the app pool recycles and make it faster/easier to cleanup a DNN installation of old modules.  If an error occurs skip that installation complete the ones that don't fail installing and uninstalling.  Maybe module creators can group modules together by installation order id to install or uninstall groups of modules that are dependent on each other.  I generally try to name them in an order that allows the important updates first.  Maybe you can order them in the installation/uninstallation process so that it wont fail if you wish to do this process on multiple.  After you select or drop and drag go each package to install/uninstall the user can then go to the next form or section that displays modules selected to order them so they wont fail due to dependency issues.

I would have asked for feature to "Manage" multiple modules however just being able to install is a great leap forward for me.  Uninstall and potentially update all that have update services would be a great future feature after at least the installation of more than one module enhancement is added to the DNN platform.

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
Soo, what hooks up the contents on the zip and makes it an extension is the manifest. The manifest is validated at step 1. A manifest can include multiple packages, each package can be a module, a theme, a library, and so on, all possible extension types. So it is possible right now to install many packages at once, but it needs to be done at the manifest level. 

I am closing this issue for now since it is already possible. Now I understand the request here is more to install multiple modules from different vendors at once, this would be a bit complex to batch since one may install dependencies the other does not like and there would need to be an order of operations involved, etc. For instance, module A installs EF 6 and module B installs EF 5. If they run alphabetically, you get an EF5 binding but module A will fail, so we need to install B before A, but we still need a restart to read the dll version to know about this.

I am closing this issue for now but if anyone has a plan an intention to implement this, please comment and I will be happy to reopen.
