### ISSUE TITLE
Add Back Admin Only Lock Icon on Page Manager

### ISSUE THREAD

**Issue by cklenk** [dnnsoftware/Dnn.Platform#3573]
## Description of problem
Previous older versions of dnn used to have an icon (lock) picture that would show up if the page was marked as admin only. This was super helpful for sites that had a lot of pages. The new page manager in dnn 9.4.4 does not have such icon. So you waste a lot of time to go to each page and check the permissions.

## Description of solution
Add lock icon back next to page to signal admin only.

## Screenshots
![image](https://user-images.githubusercontent.com/12185742/74750822-5a9c6080-523a-11ea-85b6-4dcb58af2de4.png)
Screenshot of what it used to do on dnn 8

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by sleupold** [comment]
still open

**Comment by jeremy-farrance** [comment]
Still needed.

**Comment by cklenk** [comment]
This would be great. Thank you!

**Comment by cklenk** [comment]
still open

**Comment by cklenk** [comment]
Reopen please.

Thanks
Cameron

**Comment by valadas** [comment]
Since this is an open-source project, it is maintained for free by developers that invest their free time generously.

We implemented stalebot to help us keep our backlog current, for bugs a simple mention that it is still reproducible on the latest version or ensuring there are very clear steps to reproduce is key to keeping the issue rolling.

For features and improvements, they will only happen if a developer decides to contribute the code change. For non-developers, one way to push such issues forward could be to sponsor a developer.

With this in mind, does anyone have the intention to work on this item in the next months?
