### ISSUE TITLE
Custom Page Stylesheets load before skin.css

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3611]
## Description of bug
Provide a clear and concise description of the bug.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. create a page.css file with the following css
`.navbar .brand {max-width:50px;}`
2. Upload the file to site root directory
3.  Add the stylesheet to custom stylesheet for the page settings
4.  refresh the page

## Current behavior
No change to logo size which is set by skin.css

## Expected behavior
Logo is resized to 50px

## Screenshots
If applicable, provide screenshots to help explain the bug.
![image](https://user-images.githubusercontent.com/13577556/75833290-70973e80-5d6d-11ea-83ac-24972b51e34d.png)

## Error information
n/a

## Additional context
Page.css loads before all other stylesheets.  I believe it should load after Portal.css in load order or after framework

![image](https://user-images.githubusercontent.com/13577556/75833927-64ac7c00-5d6f-11ea-8146-b5c21aa61b40.png)

https://www.dnnsoftware.com/wiki/dotnetnuke-stylesheets-explained 

File order here says Portal.css loads last nothing about defaultpriority and that framework is default.css

The order is actually
- page.css
- default.css (framework)
- admin.css
- feature.css
- ie.css
- module.css
- resource.cee
- skin.css
- container.css
- specific container.css
- portal.css
- styles set with defaultpriority 

![image](https://user-images.githubusercontent.com/13577556/75833710-b43e7800-5d6e-11ea-91bd-aa8e86cf74b7.png)

This is just one example of how default, skin, container, module and framework take priority over page.css

It is a bit confusing and either adding a priority for page.css such as defaultpriority or loading it after Portal.css loads in default.aspx should resolve this issue. 

Community can close this issue if it is not a change desired however I believe there is more concern than being noted for this one file's load order.  Loading the page custom style sheet first is what is happening currently.  I understand there are a number of way to look at this.  This is a more specific issue than my last issue dealing with only the page.css loading first when I believe it should load somewhere after Portal.css loads.

On top of that Custom Page Stylesheets are not documented. 

## Affected version

* [x ] 10.0.0 alpha build
* [ x]  9.5.1 alpha build
* [x ]  9.5.0 latest supported release
* [ x]  9.4.4 

## Affected browser

* [ x] Chrome
* [x ] Firefox
* [ x] Safari
* [ x] Internet Explorer 11
* [ x] Microsoft Edge (Classic)
* [x ] Microsoft Edge Chromium

**Comment by valadas** [comment]
We had a chat yesterday about this subject in the Technology Advisory Group approvers meeting. A consensus was reached after analyzing multiple possible situations right now in the ecosystem, we reached a consensus that we do not want to introduce a breaking change by changing any file load order and that if there is bad documentation out there, it needs to be fixed in the documentation.

The wiki linked is on the corporate website, but since it is a wiki, you are welcome to edit it. We are consolidating and revamping the documentation and I would suggest updating this page here for having the real community maintained single source of truth https://dnndocs.com/content/tutorials/themes/creating-themes/create-css/index.html#create-a-css-file

**Comment by thabaum** [comment]
Thanks for the update.  Didnt know the meeting was yesterday.  

so instead of having clean CSS files we choose long selectors for longer css files when styling.  That is fine I still say this is odd behavior and I am glad I found out about Page.css and this load order.  Makes more sense to all the issues I am having myself and with vendors...

I still think it is very odd to have page.css load first.   This must be for HTML added to the page with specific classes only.  Which if that is the case who cares about load order...

**Comment by valadas** [comment]
>so instead of having clean CSS files we choose long selectors for longer css files when styling

No, instead of creating a breaking change we prefer to keep the existing behaviour that has always worked fine. CSS specificity is not about the length of selectors, for instance a single id selector will have more weight than 999 classes, in your example you use a bootstrap navbar, bootstrap is notorious for using a lot of classes for everything and !important in many places that are unneeded. If you just add an id to your logo, you can easily restyle it with a single short selector that will override all the classes (well unless there are !important, which is why it is to avoid).

We did not take that decision lightly, we reviewed the PR, analyzed the pros and cons of such change an unanimously agreed that the risks outweigh the benefits.

**Comment by thabaum** [comment]
I addressed two different issues.  I am currently battling it on in dnn docs now :)  The load order is not correctly documented anywhere.  We will address this first.  Then you can see how things may be a bit off from what is expected.

home.css loads before portal.css which should load default priority 100 according to everyone but is missing the load order so I believe that it loads on it's own.  So something is wrong with the method that loads css stylesheets that do not define a load order as default should be 100, but instead I believe it just loads it on the spot same as calling it directly within a file.

I am trying to get some documentation approved, once I believe my directions are followed I used two different selectors now two different examples showing how a page custom stylsheet loads before portal.css loads when it is expect to load after.

This is all my PR's addressed in a couple different solutions.  I think honestly we can move link 417 to line 677 call it good in default.aspx.cs :)

**Comment by bdukes** [comment]
@thabaum the Technical Advisory Group has decided that changing the priority of loading CSS is a breaking change that we will not be making, whether or not the actual load order is "what is expected" or not.  We are not willing to break working CSS, even if it would make the load order easier to work with.  We're stuck with what we have, even if we wish we weren't.  The _only_ next step is updating any documentation that is out-dated or incomplete.

**Comment by thabaum** [comment]
My only question is who is currently using a page.css file that does not want what is happening in that file to load on that page?

**Comment by sleupold** [comment]
it sounds like the only option to solve this is deleting all .css files in the CMS and move over to inline styles to make it behaving as needed.
