### ISSUE TITLE
Host can't login after portal switched to use email instead of usernames

### ISSUE THREAD

**Issue by donker** [dnnsoftware/Dnn.Platform#3658]
## Description of bug
It looks like our logic to log in a user depends on that user being a member of the portal if the portal uses "email as username". This impedes hosts to log in as they are not typically a member of every child portal.

## Steps to reproduce
1. Use an existing site with various accounts
2. Switch the site to use emails instead of usernames (Security)
3. Log out
4. Try to log in as host

## Current behavior
Will not log in host. Neither email not username will work.

## Expected behavior
Logs in host.

## Affected version
* [ ?] 10.0.0 alpha build
* [ ?]  9.5.1 alpha build
* [ ?]  9.5.0 latest supported release
* [x ]  9.4.4 

## Affected browser
n/a

## Analysis
This happens in this bit of code:

https://github.com/dnnsoftware/Dnn.Platform/blob/f6f6ef6dcdf43d185cac2d3bf4dc55bb2ec5e7a8/DNN%20Platform/Website/DesktopModules/AuthenticationServices/DNN/Login.ascx.cs#L255

As you can see we do ``` userByEmail = UserController.GetUserByEmail(PortalId, userName); ``` to find the user. This SPROC is somewhat lacking as it will only find a user if in that portal. IMHO a superuser should be found as well.

**Comment by thabaum** [comment]
I always thought I could I just needed to use the host email address instead of username.  does this allow username for host instead?

Is there a way we can get it so we can use allow both Email or Username for option to login instead of just email or only username.

I am debating using email as username as it seemed to have some odd behaviors in the past.
