### ISSUE TITLE
Improve local build experience with regards to versioning

### ISSUE THREAD

**Issue by donker** [dnnsoftware/Dnn.Platform#3670]
## Git Changed Files

Currently the following files are changed whenever the version of the solution is updated during build: *.dnn, package.json (in various React projects) and solutioninfo.cs. This amounts to 40 odd files that may show up as changed as you're working on a change in the DNN code. Not only is it annoying to the developer as he/she needs to wade through these files to find the ones that contain the "real" changed code, it also poses a risk of accidentally committing some of these files while preparing a PR for the project.

It is an ongoing effort by the build team to improve the experience for developers and ultimately we'd like to have no files pollute your git experience.

## Product versioning on Github

It is imperative that a user who checks out the code tagged version X.Y.Z gets the code that corresponds **exactly** as to how it was when that version was released. Currently this is not yet the case. If you check out v9.5.0 the SolutionInfo.cs and other versioned files point to 9.4.4. For v9.4.4 it is even 9.4.2. Source code packages were deprecated a long time ago in favor of using Git and tags. It is upon us to make this work.

## Presumptions

1. Developers will be unaware of our versioning mechanism (and will have various degrees of knowledge of Git) and need a simple way to control the version they are building.
2. People make mistakes and that's OK. We just need to limit the amount of damage these mistakes can make.

## Potential interventions that could help the above situation

- Create a new CI task that runs after build which commits all changes and tags this commit with the version nr. This would eliminate the situation we have now where the version in code is not what it is on the tag.
- For json and dnn files only inject a version on build and rip those out after build. The downside with this approach (as we've learned from the past) is that if anything goes wrong during build, you are still stuck with all these changed files.
- Build dnn (manifests) dynamically (i.e. upon build) so the version never gets written to disk. This could be done using the mechanism leveraged in the Dnn.CakeUtils project which generates manifests on the basis of a json file. The downside is that this requires quite a bit of work as we need to rewrite the packaging logic as well.

**Comment by valadas** [comment]
>Create a new CI task that runs after build which commits all changes and tags this commit with the version nr. This would eliminate the situation we have now where the version in code is not what it is on the tag.

Yep, we just need to make sure this only runs manually, we could call this a post-release task and I would also like that it updated our issue templates. As discussed we can do some automation to automatically get the latest released version.

>For json and dnn files only inject a version on build and rip those out after build. The downside with this approach (as we've learned from the past) is that if anything goes wrong during build, you are still stuck with all these changed files.

I created backup and restore steps that should run each time the build script is called and the restore runs even if the build fails. The problem is that this is voluntarily skipped if the versioning is done by the settings file. By removing that condition in the setup and teardown steps, it should resolve this. My last PR about it was an issue when a build was done without any changes. It should now work fine no matter what except for that skip condition.

Basically this creates a local commit with the current state called 'backup' and then reverts that commit. It is local only so does not even need an active network connection. It is safer and faster than our previous zip process and covers absolutely all grounds no matter the nature of build scripts changes to bring the user back exactly at the state he was before the build, even if the build fails.

>Build dnn (manifests) dynamically (i.e. upon build) so the version never gets written to disk. This could be done using the mechanism leveraged in the Dnn.CakeUtils project which generates manifests on the basis of a json file. The downside is that this requires quite a bit of work as we need to rewrite the packaging logic as well.

Well, with earlier build scripts we had a process in which if the manifests had versions, they would be locked at that version, if they did not have a version they would get it from the build scripts. Now thanks to @donker we have a list of manifests that should not be auto-versioned vs the others that do get automatically versioned, which means we no longer have to (or not have to) have a version number in the manifests. I think we should just commit the version in that post-build task so that if a developer just builds one module or package or project (ie: not using the build scripts), he gets a proper usable package out of the box.
