### ISSUE TITLE
There was an error retrieving your content. Please check your internet connection

### ISSUE THREAD

**Issue by Diogo-Ameixas** [dnnsoftware/Dnn.Platform#3680]
## Affected version

* [x]  9.5.0 latest supported release

## Affected browser

* [ x] Chrome
* [x ] Firefox
* [x ] Safari
* [x ] Internet Explorer 11
* [x ] Microsoft Edge (Classic)
* [x ] Microsoft Edge Chromium

After updating to version 9.5.0 when trying to view / edit the pages this error appears, how can I solve it?
![2020-04-15 11_35_55-Inicio](https://user-images.githubusercontent.com/56506689/79328057-5d9b9080-7f0d-11ea-8c50-db8e58144a4f.png)
![2020-04-15 11_39_57-Inicio](https://user-images.githubusercontent.com/56506689/79328438-f3cfb680-7f0d-11ea-839a-7585b3ed6549.png)

**Comment by valadas** [comment]
My guess is that something that is required is currently having a empty string. If you go to different pages first and then open the Pages module, does it happen on all pages, if not, maybe compare the pages where it happens and where it does not.

**Comment by Diogo-Ameixas** [comment]
the error is that you are waiting for a value that is not being passed, I cannot understand what is waiting for you to correct it, because the log is not very explicit. It's happening with every page.
It was after upgrading from version 7.0.0 to version 9.5.0. I managed to run all the errors after the upgrade, except this one.

**Comment by Diogo-Ameixas** [comment]
![image](https://user-images.githubusercontent.com/56506689/79487180-c0755080-800f-11ea-9260-e1758bb9dbd9.png)

**Comment by valadas** [comment]
> I cannot understand what is waiting for you to correct it

We cannot fix something if we can't make it happen, first we need to find out what is causing the issue in the first place. Unfortunately it will need some digging around in your instance because it is not a widespread issue. I would believe from the error log, maybe an empty TabPath in the Tabs or something else in the TabUrls tables, maybe the PortalAlias table. Hard to know really.

If I where to guess, maybe an empty portalAlias ? Can you try to do in sql console:
```
SELECT * FROM {databaseOwner}{objectQualifier}PortalAlias
```

And look if you maybe have an empty HTTPAlias in there...

**Comment by sleupold** [comment]
I'd also check for page urls:
SELECT * FROM TabUrls WHERE TabID = 128

**Comment by Diogo-Ameixas** [comment]
Thank you very much Valadas, there was effectively empty HTTPAlias. 
The migration to the new version was completed successfully.
