### ISSUE TITLE
9.6.0 Xcillion Theme responsive menu on mobile devices

### ISSUE THREAD

**Issue by james7342** [dnnsoftware/Dnn.Platform#3732]
## Description of bug
Post upgrade to 9.6.0 responsive menu is broke on mobile devices. The site uses the Xcillion skin/theme.

## Steps to reproduce
1. Have working site with Xcillion them and responsive menu.
2. Upgrade to 9.6.0
3. Login on mobile device or set browser into responsive mode
4. Select menu and notice no menu is presented. 

## Current behavior
No menu is presented

## Expected behavior
Menu present like it was in prior releases. My upgrade was from 9.5.0 but has worked in all prior versions.

## Screenshots
Console Bootstrap Error:
![screenshot_1393](https://user-images.githubusercontent.com/27960723/81087080-20904180-8eae-11ea-92d8-2ff3b2229da0.png)

## Error information
N/A

## Affected version
* [ ] 10.0.0 alpha build
* [X] 9.6.0
* [ ]  9.5.1 alpha build
* [ ]  9.5.0 latest supported release
* [ ]  9.4.4 

## Affected browser
Only tested the browsers noted below.
* [ ] Chrome
* [X] Firefox
* [X] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by bdukes** [comment]
This is due to an incompatibility between Bootstrap and jQuery 3.5.0, which is (at least partially) fixed in jQuery 3.5.1.  Pull request #3729 updates DNN to jQuery 3.5.1, but in the meantime you can install jQuery 3.5.1 from https://ci.appveyor.com/api/buildjobs/c1bvvcw9mn72gtd4/artifacts/_InstallPackages%2Fjquery_3.5.1.zip (the CI build for https://github.com/EngageSoftware/DNN-JavaScript-Libraries/).

**Comment by james7342** [comment]
Thanks. I've restored the site from a pre upgrade backup at this point. Will wait until 9.6.1 or official fixed release. No driving need to move to 9.6.0 at the moment other than trying to stay current.
