### ISSUE TITLE
In DNN v9.6.0 the Web.config is missing telerik libraries 

### ISSUE THREAD

**Issue by rashidbilgrami** [dnnsoftware/Dnn.Platform#3735]
## Description of bug
Once I install the hotcake commerce module I found the bug "~/Telerik.Web.UI.WebResource.axd' is missing in web.config. RadScriptManager requires a HttpHandler registration in web.config" 

## Steps to reproduce
List the precise steps to reproduce the bug:
After installation of HotCakeCommerce module go for following steps 
1. Go to 'Settings'
2. Click on 'HotCakeAdministration'
3. See error

## Current behavior
The site is throwing an error after deployment the module and it working fine with the previous module 

## Expected behavior
Need to work like previous module 

## How to Resolve
Following items are missing under  <handlers> section in web.config 
<add name="Telerik.Web.UI.WebResource" verb="*" path="Telerik.Web.UI.WebResource.axd" type="Telerik.Web.UI.WebResource, Telerik.Web.UI" preCondition="integratedMode" />
      <add name="Telerik.Web.UI.ChartHttpHandler" verb="*" path="ChartImage.axd" type="Telerik.Web.UI.ChartHttpHandler, Telerik.Web.UI, Culture=neutral, PublicKeyToken=121fae78165ba3d4" />

## Affected version
9.6.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by mitchelsellers** [comment]
@rashidbilgrami This is expected behavior for the DNN Platform at this time.

As part of the 9.6.0 installation, the handlers for Telerik were removed as DNN Platform does not need them.  For security purposes these handlers have been removed, you can add them back in if you need to.

The usage of the DNN Platform Telerik functionality has been marked as Obsolete for more than 2+ years.  And will be fully removed, including the installation of the Telerik.Web.Ui.dll in the 910.0 release
