### ISSUE TITLE
After New Site Groups the whole management gets into trouble

### ISSUE THREAD

**Issue by soheilkheiri** [dnnsoftware/Dnn.Platform#3770]
## Description of bug
After New Site Groups the whole management gets into trouble

**Not Working Right Personabar (open/close) button "x" after refresh page.** 

**Problems login into the site.**

**Not Working Management Save Data in ( Pages / Site Settings / User  , etc ...)**

and after **Delete Site Groups**  All the mentioned problems are solved.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Manage > Site Groups > New Site Groups
2. Complete and Save

## Affected version

* [ ] 10.00.00 alpha build
* [X] 09.06.01 release
* [ ] 09.06.00 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by valadas** [comment]
Any errors in the browser console (F12 in most browsers) ?

**Comment by soheilkheiri** [comment]
This is a problem with the server side and the client side is not a problem

**Comment by valadas** [comment]
I don't think the close button has anything in the backend, did you actually check for javascript errors ?

**Comment by valadas** [comment]
Closing this issue due to lack of response. I was not able to reproduce. If you have more details, please open a new issue with a clear step by step from A to Z to make it happen... Thanks

**Comment by ropalko** [comment]
We have a similar problem. We have one main portal and 2 sub portals. A site group is created and both sub portals are listed. One subportal always opens the Persona Bar with open Site Group area. As soon as we remove the affected portal from the site group, the problem no longer occurs. There are no Javascript errors in the console. I can't find anything noticeable in the event log either.

**Comment by yog-it** [comment]
We were experiencing this issue on an instance of DNN where we implemented Site Groups.  Here are steps to reproduce it:

1. From a fresh DNN instance, open Sites and Add Site
2. Add Portal 1 and make it a directory /portal1
4. Open Site Groups, choose the main portal and click New Site Group
5. Make a group that only contains the main portal
6. Browse to Portal 1, open Site Groups and edit the site group that was already created and add Portal 1
7. Close the persona bar and refresh

The site will never stop opening the Site Groups on the persona bar after the page loads while logged in as the host. We tried clearing the browser cache, the site cache and restarting the instance.  The only fix was as mentioned, remove the portal from the group.  If we now add the portal back to the site group from the main portal, the problem is solved.
