### ISSUE TITLE
Deprecation for ExecuteDataSet

### ISSUE THREAD

**Issue by vmasanas** [dnnsoftware/Dnn.Platform#3830]
On the current code for the DataProvider there is an ExecuteDataSet method with this deprecation comment:

[Obsolete("Deprecated in 7.0.0.  This method is unneccessary.  You can get a reader and convert it to a DataSet. Scheduled removal in v10.0.0.")]
public virtual DataSet ExecuteDataSet(string procedureName, params object[] commandParameters);

I think this is wrong and will break many module that might depend on it.

By defintion a DataSet can contain multiple tables so on the current call you will get all result sets from the SP into the dataset. See for example:

CREATE PROC spsample
as
select * from t1
select * from t2
...

So the change from ExecuteDataSet to GetReader is not correct, because you will end up loosing some of the data returned.

I don't see why this method should be deprecated when it has some valid use cases.

**Comment by bdukes** [comment]
You can get multiple result sets by calling [`IDataReader.NextResult()`](https://docs.microsoft.com/en-us/dotnet/api/system.data.idatareader.nextresult?view=netframework-4.8#System_Data_IDataReader_NextResult).  In fact, this is what the implementation of `ExecuteDataSet` does https://github.com/dnnsoftware/Dnn.Platform/blob/56f8b7ff6f78400bbf6f37b5c1a36eae62437ef7/DNN%20Platform/Library/Data/DataProvider.cs#L4354-L4358

The issue I've personally run into is with the deprecation of `ExecuteSQL` https://github.com/dnnsoftware/Dnn.Platform/blob/56f8b7ff6f78400bbf6f37b5c1a36eae62437ef7/DNN%20Platform/Library/Data/DataProvider.cs#L4366-L4367

AFAIK, this is the only method which allows passing parameters into ad hoc SQL (rather than a stored procedure).  Its deprecation message says <q>This will be removed and replaced with named instance support</q>, but I'm not sure what that means and I'm sure it's not on anyone's radar to contribute by DNN 10.

**Comment by mitchelsellers** [comment]
Personally, at this stage of the game, and given that the "workaround" is that you manually do what is there.  I'm almost in favor of removing the Obsolete attribute on both of these methods.

@bdukes any thoughts?

**Comment by bdukes** [comment]
:+1: Works for me

**Comment by valadas** [comment]
It would be nice to document deprecations more as some comments as to why it is deprecated. Say "This method has performance issues and use this better one" or "This would not work if we migrate to xxx", etc.

**Comment by sleupold** [comment]
PR #4259 pending
