### ISSUE TITLE
X-Frame-Options Values Corrupted by MVC Module Pipeline

### ISSUE THREAD

**Issue by mitchelsellers** [dnnsoftware/Dnn.Platform#3842]
## Description of bug
In earlier versions of 9.x additions to the web.config were made to set a default value for the X-Frame-Options header value. However, with this set it is not currently possible for the value to be properly overridden as the code necessary to suppress the automatic addition of X-Frame-Options by the MVC Module pipeline only exists in the Web.Config.

The current step that is missing in 

## Steps to reproduce
Attempt to adjust the value of the X-Frame-Options header and view the resultant value.  It will be a combination of the expected value and a default .NET Value.  This behavior will NOT be noticed on a page with a MVC module on the page.

## Current behavior
X-Frame-Options header cannot be adjusted 

## Expected behavior
X-Frame-Options header value in the web.config should be respected at all times

## Error information
The code exists here: https://github.com/dnnsoftware/Dnn.Platform/blob/cc61549005ab5ea1c66fa91670931642a62893e4/DNN%20Platform/DotNetNuke.Web.Mvc/MvcHttpModule.cs#L56-L77 that disables the default .NET behavior, however, it ONLY executes when a MVC Module is loaded to the pipeline

## Additional context
The existing web.config values should NOT be adjusted.

## Affected version

* [X] 09.x & Later

**Comment by mtrutledge** [comment]
I can take a look at this.

**Comment by mtrutledge** [comment]
I am not sure if this happens for everyone, but my site was missing the following HTTP Module in the web.config:

``
<add name="MVCModules" type="DotNetNuke.Web.Mvc.MvcHttpModule, DotNetNuke.Web.Mvc" preCondition="managedHandler" />
``

Once this was added I stopped getting the extra X-Frame-Options header sent back and was able to manipulate the header through the web.config file as expected. My site was a very early version of Evoq Content and has been upgraded since 2015. If you run into this, double-check for that entry in the web.config file. I can still move the code if we think it is necessary, or we can close this one out.

**Comment by mtrutledge** [comment]
After double-checking a new install and an upgrade, the MVC Http Module is being added to the web.config. I am going to close this issue as if this module exists in the web.config then there is not a problem setting the X-Frame-Option in the web.config.
