### ISSUE TITLE
Access to DependencyProvider in ModuleSearchBase

### ISSUE THREAD

**Issue by dsjak-shie** [dnnsoftware/Dnn.Platform#3892]
## Description of problem
DependencyProvider is currently not accessible in a class that inherits from ModuleSearchBase. We currently generated URLs for search documents using Globals.NavigateURL(), which is deprecated.
We would like to swap Globals.NavigateURL() with NavigationManager.NavigateURL(), but we'd need to have access to DependencyProvider to accomplish this.

## Description of solution
Declare a protected property of IServiceProvider in ModuleSearchBase and instantiate it with a reference to Globals.DependencyProvider in the constructor.

**Comment by bdukes** [comment]
Rather than giving access to `IServiceProvider`, DNN should use the global dependency provider to create the `ModuleSearchBase` implementation and provide its dependencies via constructor injections.

**Comment by dsjak-shie** [comment]
@bdukes could you elaborate some more or provide an example in the codebase where something similar is done? I could take a crack at implementing this if I have some more information / guidance.

**Comment by bdukes** [comment]
I addressed this issue for `SchedulerClient` in #3696, which allows an implementation to add dependency injection.  So, I can now declare a client like this:

```c#
public class MySchedulerClient : SchedulerClient
{
    private readonly INavigationProvider navigationProvider;
    public MySchedulerClient(ScheduleHistoryItem item, INavigationProvider navigationProvider) : base(item)
    {
        this.navigationProvider = navigationProvider;
    }
}
```

And the scheduler knows to fill the `INavigationProvider` (or any other dependency) from the dependency injection container.

It was a little tricky for the `SchedulerClient` since it has that `ScheduleHistoryItem` parameter all of the time, but basically you should be able to find where we're creating the `ModuleSearchBase` instances, create a container scope, and then use that scoped service provider to instantiate the `ModuleSearchBase`, which will automatically fill in its constructor dependencies.

Hope it helps!

**Comment by valadas** [comment]
If I understand correctly the new way of doing it is documented and this needs to be done on the developer end to use DI. I am closing the issue for that reason but if I am wrong, feel free to comment and I will reopen.

**Comment by bdukes** [comment]
We don't yet have support for injecting services in `ModuleSearchBase`, this remains an open issue.

**Comment by bdukes** [comment]
Still a valid issue.  I've started an implementation in 28c53b56b60b40e88745d2f08693b913ea60763d (for #3933), but it's not complete and needs to be adjusted to think about scoping.

**Comment by sleupold** [comment]
still an issue, @bdukes  is working on?

**Comment by bdukes** [comment]
Yes, this is planned for v10
