### ISSUE TITLE
Modify Logo skin control to handle .svg files

### ISSUE THREAD

**Issue by mathisjay** [dnnsoftware/Dnn.Platform#3893]
## Description of problem
Logo control doesn't handle .svg files

## Description of solution
Modify the Logo skin control to handle a .svg as a logo.

**Comment by david-poindexter** [comment]
@mathisjay I am pretty sure SVGs can be used as logo files (though there was a recent bug with them not being able to be uploaded - fixed in 9.6.2), but it would just render them via the `<img>` tag.  I could be wrong though.

**Comment by valadas** [comment]
Just for proper documentation on the actual issue here. I just had a chat with @mathisjay on Slack. As suspected css support is different with a real inline svg and an svg that is loaded in an img tag or an object tag. For instance a couple of popular css properties like fill and stroke can be overridden only when the svg is inline, these are important because many popular svg librarires do not define currentColor for the fill or stroke and for proper support of every possible svg, inline would really be ideal.

Also, some svg files have headers and we would probably need to parse the svg to only grab the svg node and cache that node as a string then just inject the string in a literal control...

I am assigning this to 10.0.0 with high importance to make sure we do it in 10.0.0 where we can afford having breaking changes. I am willing to tackle this.

**Comment by bdukes** [comment]
To make this not a breaking change, we could add a property to the `dnn:Logo` control so you can specify whether to load SVG inline or via an image tag.

**Comment by david-poindexter** [comment]
Good idea @bdukes - and default behavior could be img tag.
