### ISSUE TITLE
TabController.CurrentPage.FullUrl return truncated path

### ISSUE THREAD

**Issue by Scippy** [dnnsoftware/Dnn.Platform#4241]
In a module I'm no more able to use TabController.CurrentPage.FullUrl don't return full path. It seems that it return the full path truncated without apparent meaning.
To fix it I had to work around HttpContext.Current.Request to retrive it.

**Comment by valadas** [comment]
@Scippy Please follow the issue template and provide the affected version and steps to reproduce the issue,

**Comment by Scippy** [comment]
Sorry the missing bur report template.
## Description of bug
n a module I'm no more able to use TabController.CurrentPage.FullUrl don't return full path. It seems that it return the full path truncated without apparent meaning.

## Steps to reproduce
You can simple use `TabController.CurrentPage.FullUrl` in any part of the code of a module

## Current behavior
it return truncated Url without apparent meaning

## Expected behavior
it should must return Full Url

## Affected version
* [X ] 09.07.02 latest supported release

**Comment by valadas** [comment]
FullUrl is used in platform in 22 various places including Console and UrlRewrite, multiple SkinObjects, etc. And it is working fine in those places. Since you are a developer you are well aware that a good start would be very clear steps to reproduce from a clean state as this may depend on some special set of setup circumstances or something, it is not as straighforward and just being obviously broken...

**Comment by valadas** [comment]
Maybe at least an example of the actual full url and what the API returns instead to at least have an example we can go by and maybe write a test to preproduce the issue and fix it from there. An issue this vague will be very hard for anyone to pickup and fix.

**Comment by Scippy** [comment]
I've try to reproduce in a separate block of code and there work fine.
I close because I'm no able to reproduce the issue.
