### ISSUE TITLE
Feature Request - Visible By Host Only

### ISSUE THREAD

**Issue by moorecreative** [dnnsoftware/Dnn.Platform#4343]
## Description of problem
Admin-Level Users don't always see that permissions for modules are visible to admin only. But as Host users, we sometimes want to keep modules on a page but not visible to users. Those admin who quickly glance through and don't realize that the module is admin-only then become confused because of their oversite or misunderstanding.

## Description of solution
How difficult would it be to have an additional permissions level which amounts to "Visible To Host" which would essentially function as today's Visible By Admin... a Host would always be able to see every module, but an Admin role would be possible to not see some modules on a page (the Visible by Admin check box could be unchecked)

## Description of alternatives considered
Alternatives considered? Teaching Admin users to be more aware of system features regarding permissions... that's about the best option. That, or of course, just deleting the module from the page or moving it to another page.

**Comment by sleupold** [comment]
Sorry, but I vote against this feature suggestion, because it violates the permission principles of DNN, where a site admin has full control over his website and its content. Host is not a content permission level, but has additional features beyond the single website.
Module level permissions are intended to be set by any person with edit permission for the page it resides on. 
Modules visible to admins only are by default marked with an appropriate text above (unless host or admin decides to disable this warning)

**Comment by bdukes** [comment]
Regarding difficulty, there are many places in the permissions system which assume that an administrator will always pass a permissions check, so this could definitely be the source of some tricky bugs.

Is this a scenario where the "Visible by Administrators only" banner is being ignored?  Perhaps the design of that notice could be adjusted?

**Comment by mitchelsellers** [comment]
I think that @bdukes is on the right path here.  I think the current design of "Visible by administrators only" is hard for people to associate that the entire content is only visible to that role.  They don't associate the message with the content.

Making things invisible to admins in situations however, I think would be a disastrous undertaking
