### ISSUE TITLE
Error at membershipmodule removed Cookie language

### ISSUE THREAD

**Issue by thienvc** [dnnsoftware/Dnn.Platform#4428]
https://github.com/dnnsoftware/Dnn.Platform/blob/8e19f0ed92322dad9433b14e42a526139c19cb51/DNN%20Platform/HttpModules/Membership/MembershipModule.cs#L160-L163
Need to check NULL condition `user.Profile.PreferredLocale` before calling `SetLanguage`, otherwise it will result in removal of existing Language cookie `response.Cookies.Remove("language")`.
https://github.com/dnnsoftware/Dnn.Platform/blob/ac393962741502e7ebe64763d09ae6d695a8280d/DNN%20Platform/Library/Services/Localization/Localization.cs#L1583-L1591

**Comment by thienvc** [comment]
Oh, it appeared in many places
https://github.com/dnnsoftware/Dnn.Platform/search?q=SetLanguage+PreferredLocale

**Comment by valadas** [comment]
Please try when creating issues to follow the issue template, for instance here the version is important. The user preferred local should never be null and there was a bug with this that got resolved quite recently. That being said, the UI does not allow changing from a value to null. I remember there was a PR to improve/simplify that code and it had to be removed due to duplication of cookies, maybe this is why there is a removal.
