### ISSUE TITLE
 jQuery call locally

### ISSUE THREAD

**Issue by mnouraei** [dnnsoftware/Dnn.Platform#4501]
https://github.com/dnnsoftware/Dnn.Platform/blob/97e12a624147667de66a36d72cad8a170154ddcf/DNN%20Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx.cs#L470

https://github.com/dnnsoftware/Dnn.Platform/blob/97e12a624147667de66a36d72cad8a170154ddcf/DNN%20Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx.cs#L477

Please change the jQuery call locally to make it available on intranet servers

**Comment by valadas** [comment]
One question I wonder is what version of jQuery works here, ideally we should use the one the rest of Dnn uses for consistency if at all possible...

**Comment by mnouraei** [comment]
@valadas 
I used this version
[Jquery.zip](https://github.com/dnnsoftware/Dnn.Platform/files/6115187/Jquery.zip)
jQuery v1.11.1
jQuery UI - v1.10.4
And it worked without a problem

**Comment by mortezakermani** [comment]
Hi Daniel,

I am agree with Mahmoud.

The HTML editor which is used in DNN (CK) calls two JavaScript's from external resource that two following problems occur on the site:

1) In some countries access to google cdn is limited and those two files don't load quickly on the page.

2) In the intranet environment, or machines don't access to the internet, editor does not work as those two external files can not be reached.

So please make the editor use local version of JS instead of hosted versions of them.

**Comment by mnouraei** [comment]
@valadas you can download jQuery v1.11.1 - jQuery UI - v1.10.4 and copy to 
[https://github.com/dnnsoftware/Dnn.Platform/tree/97e12a624147667de66a36d72cad8a170154ddcf/DNN%20Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/js](https://github.com/dnnsoftware/Dnn.Platform/tree/97e12a624147667de66a36d72cad8a170154ddcf/DNN%20Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/js)
Then call these libraries like this
```
jqueryScriptLink.Attributes["src"] = this.ResolveUrl("js/jquery.min.js");
jqueryUiScriptLink.Attributes["src"] = this.ResolveUrl("js/jquery-ui.min.js");
```

**Comment by valadas** [comment]
Yes but if it works and it's possible I would prefer to use the one version already shipped with DNN, I did not dig into this, but would be nicer I think.
