### ISSUE TITLE
 In 09.09.00 latest supported release the HTML editor removes css classes upon saving

### ISSUE THREAD

**Issue by Carolyn-Novak** [dnnsoftware/Dnn.Platform#4553]
I recently upgraded to 9.9 and the HTML editor is removing the CSS classes upon save when using the Rich Text Editor.  I wasn't having this issue before.  
It is happening in all browsers (IE, Firefox, Chrome).  If I switch to Basic Text Box it seems to be OK.
![New Entry](https://user-images.githubusercontent.com/80273806/110349319-9d290a80-8000-11eb-8d43-14f188a29dac.JPG)
![When I open to edit](https://user-images.githubusercontent.com/80273806/110349349-a1edbe80-8000-11eb-9b71-4a15e4db23f0.JPG)

**Comment by valadas** [comment]
This has been discussed in the past in https://github.com/DNN-Connect/CKEditorProvider/issues/102 you will find some information in the link in the comments there, but this is by design of the CKEditor. Another discussion that happened regarding that is the fact that by default for security reasons, if you can't do it with the toolbar then you also can't type it in. This IMO is the purpose of also having other modes than WYSIWYG for those scenarios.

**Comment by Carolyn-Novak** [comment]
Thank you so much!  I saw the other discussion but I thought it was fixed and then happened again.  This is the first time I've had an issue with CKEditor.  You make a good point about if you can't do it with the toolbar then you shouldn't type it in.  Looks like I need to change my workflow.  
Thank you again,
Carolyn

**Comment by valadas** [comment]
Yeah, when I need some more advanced html I usually use the RAW mode and copy-paste to-from VSCode for edits :)

**Comment by Carolyn-Novak** [comment]
That's working great!
