### ISSUE TITLE
Method 'get_AddCachebusterToResourceUris' in type 'DotNetNuke.Entities.Portals.PortalSettings' from assembly 'DotNetNuke, Version=9.5.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

### ISSUE THREAD

**Issue by ravirajmm** [dnnsoftware/Dnn.Platform#4564]

**Comment by valadas** [comment]
This is a very unclear issue, please reopen a new issue and follow the issue template.
We need clear steps to reproduce on a current version in order to troubleshoot this.
My guess is that some module or theme is calling that method on the interface but for some reason the interface is somehow not implemented, but we'll need more details to even try to help.
