### ISSUE TITLE
Redirect_After... setting overwritten

### ISSUE THREAD

**Issue by liffeyd** [dnnsoftware/Dnn.Platform#4566]
## Description of bug
First observe PortalSettings values for Reirect_After... (Login, Logout, Registration) in SSMS
In my initial case these had values of -1

## Steps to reproduce

Go to Site Settings > Site Behavior 
Change the page for "404 Error Page" to any page - "404 Error Page" in my case. In my case the initial value was  None Specified

Click Save

Refresh SSMS query. The values for the 3 Redirect_After... fields will have changed to 0

## Current behavior
Any value in Redirect_After... is overwritten by 0

The stored procedure UpdatePortalSettings is executed once for each Redirect_After  (Login, Logout and Registration) but passes in 0 as the value rather than the correct original value.

exec sp_executesql N';Exec dbo.UpdatePortalSetting @0, @1, @2, @3, @4, @5',N'@0 int,@1 nvarchar(4000),@2 nvarchar(4000),@3 int,@4 nvarchar(4000),@5 int',
@0=0,@1=N'Redirect_AfterLogin',@2=N'0',@3=1,@4=N'en-IE',@5=0

exec sp_executesql N';Exec dbo.UpdatePortalSetting @0, @1, @2, @3, @4, @5',N'@0 int,@1 nvarchar(4000),@2 nvarchar(4000),@3 int,@4 nvarchar(4000),@5 int',
@0=0,@1=N'Redirect_AfterLogout',@2=N'0',@3=1,@4=N'en-IE',@5=0

exec sp_executesql N';Exec dbo.UpdatePortalSetting @0, @1, @2, @3, @4, @5',N'@0 int,@1 nvarchar(4000),@2 nvarchar(4000),@3 int,@4 nvarchar(4000),@5 int',
@0=0,@1=N'Redirect_AfterRegistration',@2=N'0',@3=1,@4=N'en-IE',@5=0

## Expected behavior
Unless the value is changed by the user it should not be overwritten with 0

UpdatePortal in SiteSettings.ascx.cs does not appear to populate the existing values for the three Redirect_After fields.

## Screenshots
N/A

## Error information
N/A

## Additional context
N/A

## Affected version

* [ ] 10.00.00 alpha build
* [X ] 09.09.00 latest supported release

## Affected browser

* [ ] Chrome
* [X] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by sleupold** [comment]
is it an issue of the stored procedure itself or the DNN code calling it?

**Comment by yog-it** [comment]
To reproduce this issue right out-of-the-box, install as new DNN instance.  Add a new page and add an account login module to it.  In the Site Settings change the login page to the new page without changing any other settings and update. Run SQL query `select * from PortalSettings where SettingName like '%redirect%'`.  All 3 default redirect settings now have a value of "0".   The value is from the persona bar PagePicker used by the SiteSettings view.  The TabID of a page is always returned correctly if a specific page is/was selected for any of these settings.  However, if "<None Specified>" (the default) is selected and the PagePicker is never opened (i.e. the list of pages never loads), the value returned to the SiteSettingsController is 0 instead of -1.   

A quick work around to this is open the PagePicker for each settings and manually select "<None Specified>" for each redirect setting.  The null integer is stored instead of "0".

**Comment by yog-it** [comment]
I think this is the same issue as #4578.
