### ISSUE TITLE
UI for Portal Expiration date

### ISSUE THREAD

**Issue by jncraig** [dnnsoftware/Dnn.Platform#4567]
## Description of problem
The UI to manage the PortalExpiry (portal expiration date) was removed in DNN 9.  This was a bad choice.

I have a client with several hundred portals in a DNN installation and they use that to manage the various portals.

## Description of solution
Add the option to set the PortalExpiry date to Site Settings for something

## Description of alternatives considered
It can be managed in SQL, but this is not the way to do it.

## Screenshots
If applicable, provide screenshots to help explain the problem and/or enhancement.

## Additional context
Add any other context about the enhancement that may be helpful with implementation.

## Affected browser
It is NOT a browser issue.

**Comment by sleupold** [comment]
@jncraig 
a) What should happen, after the site expired and the site is called?
1. display site as usual
2. display DNN 404
3. display error message
b) Should Expiry Date be editable by site admins or superusers only (second sounds logical to me)?

**Comment by valadas** [comment]
I _think_ the logic is still all in place to respect the database settings and only the UI was not migrated to the Persona Bar... I think....

**Comment by jeremy-farrance** [comment]
I did a quick test because I was curious... set PortalSettings.ExpiryDate to `2020-12-31 00:00:00.000` and reloaded the app pool, then got the message you see below.

And also verified that the displayed text is where you'd expect, `/App_GlobalResources/SharedResources.resx`.

![image](https://user-images.githubusercontent.com/653301/112382452-dd9fae00-8cb9-11eb-99aa-711e113836d7.png)

**Comment by jeremy-farrance** [comment]
If/when its added back to the (PB) UI, it would be a nice touch if both things were edited in the same place. Basically the two things are joined at the hip, so don't make people suffer Googling to figure out where to find that message.

1. When would you like the Site to expire?
2. What message would you like displayed if the site is visited after the Expiry Date?

**Comment by jncraig** [comment]
@valadas is right.  The functionality doesn't need to be altered.  We just need to have the UI back.

I think that the 3 options proposed by @sleupold have merit.

**Comment by jncraig** [comment]
Perhaps an email or a daily email to administrators (site and host) when a site expires would be helpful.

**Comment by jncraig** [comment]
Please reopen.  It is relevant.

**Comment by david-poindexter** [comment]
It seems there are quite a few ideas going here, but no clear actionable task(s) at this point.  In order for a developer to pick this issue up to work on it, I think it would be nice for them to know exactly what is being proposed before they start developing and potentially miss the mark.

The MVP approach would be to simply resurface the setting for portal expiration date in the UI and leverage the API that is evidently already in place to handle it.  If it needs to be more robust than that, then it may lead to the issue becoming `stale` again.  😉

**Comment by david-poindexter** [comment]
@jeremy-farrance regarding the ability to edit the messaging in UI, this would potentially lead to a much larger discussion and issues.  To my knowledge, this would be a fundamental shift within DNN to allow editing of resource files from anywhere other than the Languages UI (which accommodates multi-lingual).  While the convenience would be appealing for the admin (I totally understand the sentiment here), I personally would not support this approach because it would open I huge can of worms by setting a precedence for it to be done like this elsewhere (for virtually every other localized setting, etc.).  And how would you handle localization in this context.  This would require unnecessary UI bloat to handle appropriately.

**Comment by jncraig** [comment]
All I want is the UI for the ExpiryDate to be added back to the Site Settings or wherever it was!

I agree with Dave that bringing Resource Files into the discussion opens a real can of worms ...
