### ISSUE TITLE
Upgrade from 9.9.1 to 9.10.0-RC1 results in Error on mode=upgrade

### ISSUE THREAD

**Issue by james7342** [dnnsoftware/Dnn.Platform#4742]
## Description of bug
Just tried to upgrade from 9.9.1 to 9.10.0-RC1. After coping files tried to access mode=upgrade URL to start the upgrade process and received the below error.

Server Error in '/' Application.
Could not load file or assembly 'System.Web.Mvc, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.IO.FileLoadException: Could not load file or assembly 'System.Web.Mvc, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Assembly Load Trace: The following information can be helpful to determine why the assembly 'System.Web.Mvc, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' could not be loaded.

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

## Steps to reproduce
1. Copy 9.10.0-RC1 files to root of DNN folder.
2. Access site install URL with the mode=upgrade (http://dnndev.me/install/Install.aspx?mode=upgrade)

## Current behavior
Error presented 

## Expected behavior
Upgrade completes

## Screenshots
![screenshot_2337](https://user-images.githubusercontent.com/27960723/124956894-59a1d580-dfcd-11eb-9c1d-a63e6262a469.png)

## Error information
See above and screen capture provided

## Affected version

* [ ] 10.00.00 alpha build
* [X] 9.10.00-RC1 build
* [ ] 09.09.00 latest supported release

## Affected browser
Don't think it's applicable but checked browser used to start upgrade
* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by david-poindexter** [comment]
@james7342 thanks for reporting this.  Something very similar is happening with clean installs as well.  It appears some key DLLs are missing from the packages.

**Comment by jeremy-farrance** [comment]
Might be this? https://github.com/dnnsoftware/Dnn.Platform/commit/d759f37ec3622e889423e28d7c99fd457bcbe9ad#diff-f5774832f53a20e25cddbbc27b142de671b35ff84b2dde05594d8f6717bf2e6e

**Comment by james7342** [comment]
Is there going to be a new RC build created to resolve this as it seems to be more build process related versus a defect. Impossible to test the release in it's current state.

**Comment by david-poindexter** [comment]
I'm sure there will be a new RC as soon as someone is able to determine the issue, resolve it, submit a pull request, and generate a new build accordingly.

**Comment by jeremy-farrance** [comment]
Can someone add a warning or comment to the RC1 release? I'd hate to think people are spending time testing or doing stuff with it to quickly come to such an undesirable result.

**Comment by david-poindexter** [comment]
Hey guys - the very small team of people that actually contribute to this project are ALL volunteers.  I for one am very thankful for the Release Candidate process they have established.  This issue is proof that it is working!  If people test (like you have done) and report the issues (like you have done) then it will get addressed.  However, we are not going to pull an RC just because it is broken.  That defeats the purpose of the RC process.  We are also not going to start duplicating efforts to update Release Notes for every issue that is identified.  That is the purpose of these `Issues`.  Please be patient in awaiting a new RC.

That said, please know that @bdukes has already submitted a PR to fix this issue, and our very small team of people that actually contribute to this project (once again, ALL volunteers), are testing the build to make sure it is ready for a new RC.  You can follow progress on that PR here:  https://github.com/dnnsoftware/Dnn.Platform/pull/4743

Thanks again for reporting the issue.  Your contribution is much appreciated.  We need more testers like you!

**Comment by james7342** [comment]
@david-poindexter. Completely understand and appreciate everyones hard work in the project. Just thought it's kind of pointless to have a broken RC available for download that doesn't work. Seems like a potential waste of time for testers downloading a broken build without knowing and going through the upgrade process only to have it error. Then have to go search for why to only to find it's a known issue. Thanks for the link to the PR though. I have been looking for one and glad to see Brian is looking into it. Looking forward to testing the new RC once it's available.

**Comment by david-poindexter** [comment]
@james7342 you are presenting valid points, so no worries.  Unfortunately, there is no perfect solution to it all though.  We simply have limited resources and availability.  Typically issues like this are resolved as quickly as possible, so it kinda becomes a moot point.  It just so happens this one lingered for a few days due to lack of availability for these great contributors!  Thanks for your patience and for your participation in testing.  It is so important and appreciated!

**Comment by valadas** [comment]
Ok, there we go guys, happy new testing 😄 A big thanks to testers for testing it out and to @bdukes for taking the time to investigate and fix.

https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.10.0-rc2
