### ISSUE TITLE
Better support for users changing their password

### ISSUE THREAD

**Issue by scottharris625** [dnnsoftware/Dnn.Platform#4750]
I'm running DNN Platform 9.9.1, maintain 30 different portals, and have ~4,000 users.  I often see users struggle with changing their password.  I've updated the error message (in the language resources) so that it identifies the custom password rules we have.  Regardless, some users still have problems and there's little useful information that DNN provides to the user to help them figure out the issue.  It could be a case of them trying a password that fails the rules, or they're using an invalid username, or they're using a password that has been previously used.  Whatever the issue, DNN provides the same basic error message.  This can get aggravating for users. 

Are there ways to alleviate some of these issues?  From a user's perspective, having better error messages would be useful (e.g. sorry that password violates doesn't conform to our password rules, sorry you've used that password recently please try another, sorry that username doesn't exist). 

I could see, though, that a security expert might balk at more in depth error messages because it might help a hacker in some fashion. 

Another approach would be to provide different errors in the EventLog table (within the DNN database).  This way an Admin can see what the issue is.  As it is right now, all of these forms of failed logins result in a LOGIN_FAILURE code.  Perhaps additional values for the LogTypeKey field, or adding more information in the LogProperties field when a failed login occurs.

**Comment by jeremy-farrance** [comment]
I personally consider this to be very important.
 
One quick caveat (and additional enhancement suggestion) to get in there right away; "username doesn't exist" is a security problem. Right now Dnn doesn't do it at all, which is good, but I do think its needed in Intranet situations and should be an option (off by default, able to be turned on per-portal).

**Comment by valadas** [comment]
Reading https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#Authentication_and_Error_Messages and I am thinking that the current behaviour is pretty much the recommended one for security.

I think that to simplify life for users, one could remove all the password special requirements (special characters, numbers, capital letters) and simply increase the password minimum length.

Password complexity is defined by [PossibleCharacters]^Lenght:
The length is exponentially more important for security than the type of characters used. And you have the added benefit of forcing people into some sort of passphrase they will remember instead of a cryptic string of random garbage they will forget in about 1 minute.

We already have a password strength indicator (also a recommendation) and we already display the minimum amount of characters needed to register.

![image](https://user-images.githubusercontent.com/6371568/135949910-0d856662-bfc2-4c9c-938e-73a8d611b56a.png)

Sooo, in my opinion everything here is by design and I would simply recommend increasing the password length in your config.

I am closing this issue for those reasons.
