### ISSUE TITLE
Google Tag Connector Track for Admin Issues

### ISSUE THREAD

**Issue by cklenk** [dnnsoftware/Dnn.Platform#4867]
## Description of bug
When you first set up a Google Tag Manager Connection and enter a GTM id and hit save without checking the track for administrators. GTM will still load for admins. But if you check track for admins, hit save. Reload and go back and uncheck track for admins it finally stops loading GTM for admins.

## Steps to reproduce

1. Go to Settings > Connectors > Google Tag Manager
2. Ensure a tracking code is added
4. Leave change track for admins to false (default)
5. Press save
6. Check dom and see GTM still loads

## Current behavior
GTM is still loading for admins even though track for admins is false (not checked)

## Expected behavior
Expect it to not load GTM if that is not checked.

## Error information
No errors, just does not what one expects.

## Additional context
Wondering if this is related to #2782?

## Affected version

* [ ] 10.00.00 alpha build
* [ ] 09.10.02 release candidate
* [X] 09.10.01 latest supported release

## Affected browser

* [X] Chrome
* [X] Firefox
* [X] Safari
* [ ] Internet Explorer 11
* [X] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by cklenk** [comment]
Still an issue.

Thanks
-Cameron

**Comment by cklenk** [comment]
Can we re-open this one? It's still an issue.

Thanks 
-Cameron

**Comment by Constantine-Ketskalo** [comment]
Just in case someone needs it: I've created a duplicate (didn't find this one in search), where I've described what I've found out in the xml file in settings which seems to be a root cause. So whoever's going to work on it check it out if you need it:
https://github.com/dnnsoftware/Dnn.Platform/issues/5198

P.S. Hope it's going to be fixed sooner then closed automatically for inactivity. ) It's been a long time already...

**Comment by valadas** [comment]
Reopened sir

**Comment by valadas** [comment]
This was fixed in https://github.com/dnnsoftware/Dnn.Platform/pull/5669 Please test v9.12.0 latest rc and report back if you find any issues.
