### ISSUE TITLE
Resource Manager not working with Composite Files enabled

### ISSUE THREAD

**Issue by DNNMonster** [dnnsoftware/Dnn.Platform#4885]
## Description of bug
If you enable the composite files in the server performance settings the Resource Manager module becomes unusable.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to your Server Settings 
2. Click on enable composite files
3. Go to your Global Assets page
4. See missing RM and view the error in the dev window

## Current behavior
Page loads with errors in the dev window and no rendering of the Resource Manager happens.

## Expected behavior
Resource Manager should work with the Composite Files enabled.

## Screenshots
![rm_composite_err](https://user-images.githubusercontent.com/12777553/138579842-e74594aa-6cdf-42d6-b0b8-c2c8a6b03ae8.png)

## Error information
 It's a dnn is not defined js err

## Additional context
Tested on 2 installs with different skins.  It is also manifesting when the RM gets used on other pages.  Maybe a script loading order issue...??

## Affected version

* [ ] 10.00.00 alpha build
* [ X] 09.10.02 release candidate
* [ ] 09.10.01 latest supported release

## Affected browser

* [X ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [X ] Microsoft Edge Chromium

**Comment by mitchelsellers** [comment]
This has been confirmed as an issue starting with DNN Platform 9.10.0.

**Comment by DNNMonster** [comment]
Is the cause of the problem understood?

**Comment by valadas** [comment]
CDF was updated in 9.10.0 and we believe this is caused by that update but exactly what is still not diagnosed (at least for me)

**Comment by DNNMonster** [comment]
Does this line of js look familiar?

`var hasSpace=/\s/var hasSeparator=/(_|-|\.|:)/var hasCamel=/([a-z][A-Z]|[A-Z][a-z])/function toNoCase(string){if(hasSpace.test(string))return string.toLowerCase()`

I can't locate it in DNN's source but if I Google for it, it seems to be part of an analytics.js file... 

This is where I'm seeing the error start.

**Comment by valadas** [comment]
I tried to work on this today but could not make it happen on a local instance, could there be something more needed to trigger this bug from a clean install ?

**Comment by valadas** [comment]
Actually I got it to fail but only with inline editing enabled, I think this might be a side-effect of https://github.com/dnnsoftware/Dnn.Platform/issues/2653

**Comment by DNNMonster** [comment]
I tested a clean install.  I'm pretty sure the issue is still there.  The only thing I did was follow the steps to remove the Digital Assets Manager.  Even with the inline editing disabled I cannot view the Resource Manager if the js files are compressed.  It is ok with the CSS compression but it crashes with the the JS enable
![dnn_rm_err](https://user-images.githubusercontent.com/12777553/140672583-47a3109c-96dc-4837-949a-2ae15a081c25.png)


I found the offending js in DesktopModules\Admin\Dnn.PersonaBar\scripts\exports.  The error seems to be in the persona bar export bundle near line 41064.   I believe there may be something wrong in the regex..   
![dnn_bundle_js_err](https://user-images.githubusercontent.com/12777553/140672911-b9ae2327-116d-4d59-9566-babfd125d92f.png)
 
Even if you disable the Composite files entirely I still am seeing an additional error coming from /node_modules/scheduler/cjs/scheduler.production.min.js.
![dnn_rm_err2](https://user-images.githubusercontent.com/12777553/140674336-73727729-cec8-4323-9073-9d4f60885c51.png)

**Comment by cklenk** [comment]
Hi, I also ran into this today on a dnn 9.10.2 site. 

![image](https://user-images.githubusercontent.com/12185742/146579313-e61ea85a-d0c0-4e8f-8f54-89cc91539cf4.png)

The new resource manager fails to load when composite files are on

**Comment by Tychodewaard** [comment]
This is not just for clean installs, upgraded installs suffer from the same thing.

**Comment by Tychodewaard** [comment]
Still a major issue

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: stale[bot] ***@***.***>
Verzonden: Wednesday, March 30, 2022 7:30:03 AM
Aan: dnnsoftware/Dnn.Platform ***@***.***>
CC: Tycho de Waard ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [dnnsoftware/Dnn.Platform] Resource Manager not working with Composite Files enabled (Issue #4885)


We have detected this issue has not had any activity during the last 90 days. That could mean this issue is no longer relevant and/or nobody has found the necessary time to address the issue. We are trying to keep the list of open issues limited to those issues that are relevant to the majority and to close the ones that have become 'stale' (inactive). If no further activity is detected within the next 14 days, the issue will be closed automatically.
If new comments are are posted and/or a solution (pull request) is submitted for review that references this issue, the issue will not be closed. Closed issues can be reopened at any time in the future. Please remember those participating in this open source project are volunteers trying to help others and creating a better DNN Platform for all. Thank you for your continued involvement and contributions!

**Comment by valadas** [comment]
Work as started on a brand new resource-manager UI, we it gets to a testable point I'll put out some beta or some such so people can get involved in some testing.

**Comment by mortezakermani** [comment]
I could fix this issue by excluding just this single js file (resourceManager-bundle.js) from DNN Composite Files. 

If you have the same issue, [download and extract this file](https://www.benvis.com/download/rm.zip) to the RM directory. or simply [download and install this module](https://www.benvis.com/download/DNNCE_ResourceManager_09.10.02_Install.zip).

**Comment by valadas** [comment]
The resource manager has been completely rewritten in v9.11.0 and no longer has that bundle file which should fix this issue.
