### ISSUE TITLE
Please return back option to edit module files

### ISSUE THREAD

**Issue by ufoloko** [dnnsoftware/Dnn.Platform#4920]
From version 9.8.1 was removed the ModulesCreator module, and now you have a more simple ViewSource to view module files.

In this Component you check if site is running local then allow to edit module files, but not in remote access, maybe for some security reason.

It should be great to have some checkbox settings, maybe on security, to allow edition for module files. 

Additionally, should be great to have at lease codemirror plugin for code edition.

**Comment by valadas** [comment]
It was decided that editing modules is not an essential part of the platform for usage and since very few developers actually used the feature, we separated it into it's own repository to ease maintenance on the platform project. You can find it at https://github.com/DNNCommunity/Dnn.ModuleCreator but that being said, I would not recommend anyone builds modules that way.

**Comment by ufoloko** [comment]
Thanks @valadas for your comments, although I still think can be optional not for build modules, just modify for example resources files or in some cases change references.

Anyway this was a suggestion.
