### ISSUE TITLE
Ability to add security roles to site groups

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#4923]
## Description of problem
Only default security roles follow site groups such as registered (but not administrator).

I would like to assign "Administrators" to a site groups role so a member of this group can manage all sites in a site group.
Also another for Content Managers or Moderators for example which can then be applied to any site allowed in a site group.

## Description of solution
Create an option while editing or creating a security role that enables it as a site group role.

## Description of alternatives considered
Global Role Group, Site Role Group and Site Group Role Group with the option to add administrative powers to a site group site role so they can administrate all sites within a group and administrators of a site can stay the same, extending the functionality of site roles while maintaining what currently exists for functionality.

## Screenshots
![image](https://user-images.githubusercontent.com/13577556/143786113-6e281cbe-149a-4a6f-9e3f-938c4e6a1b32.png)

**Comment by sleupold** [comment]
this sounds great, but, to be honest, given the implementation of site groups and permissions, this would require huge effort with quite a security impact.

**Comment by mitchelsellers** [comment]
I really like this idea on the surface, however, I think this is an example of an item that will need very solid through into the method in which it should be implemented and the ramifications of doing so.

SIte Groups, as they are today, are a very unique beast, this addition ould make things even more craziness.  My largest concern is that knowledge of who/why/how security is applied could be strongly impacted due to the fact that we don't have great visibility into the "other stuff".

**Comment by thabaum** [comment]
I vision a checkbox next to AUTO column for "Site Group Role" that only the "Master Site" can apply towards a group.
