### ISSUE TITLE
Should Crawler be allowed to use Outputcache?

### ISSUE THREAD

**Issue by thienvc** [dnnsoftware/Dnn.Platform#4936]
https://github.com/dnnsoftware/Dnn.Platform/blob/7f8df1689563483a4005c1b686a8ab09ae47f3ca/DNN%20Platform/HttpModules/OutputCaching/OutputCacheModule.cs#L59

Currently OutputCache is not being used by Crawler (ignore if `this._app.Context.Request.Browser.Crawler == true`), which in my opinion is not recommended for the following reasons:
1, It is possible to create 2 different content, the content when viewed by SearchEngine will be newer than the user's content that has been Cached, this violates Google's principle of showing different content to search engines than the normal user;
2, Applying OutputCache to both Crawlers will help Crawlers get content faster, reduce server load and increase search engine evaluation scores.

Should we remove this condition?

**Comment by jeremy-farrance** [comment]
Rather than change or remove, I believe it would make more sense to have this as a Portal-level setting. Let the administrator choose.

**Comment by mitchelsellers** [comment]
One of the key issues would be in incorrect context was some how sent and cached. In a user situation it is cleared but for a crawler it will be a while. Ensuring that the “most accurate” page is provided to crawlers was intentional. 

There are for sure performance gains if we allowed crawlers to see cache. But it could cause cascading other issues potentially. 

I like the idea of an option for this.
