### ISSUE TITLE
Update `UpgradeWizard.aspx`, require an superuser to choose whether to keep Telerik and remain insecure or to remove Telerik, IF, no dependencies are found.  If the user selects to keep Telerik, the remainder of this process remains unchanged.

### ISSUE THREAD

**Issue by david-poindexter** [dnnsoftware/Dnn.Platform#4946]

**Comment by daguiler** [comment]
Hi @mitchelsellers 
I see this issue is assigned to you.
Are you working on it?
I can take it on otherwise.

**Comment by mitchelsellers** [comment]
Go for it. It is appreciated

**Comment by daguiler** [comment]
Hi @mitchelsellers @david-poindexter @valadas @bdukes 

1) Is this UI similar to what you had in mind for this task? Notice the new Security tab after the host log in:

![image](https://user-images.githubusercontent.com/30123437/163904813-327ef201-0568-4d3a-a32e-d7c6ef9e8c69.png)

2) Also please advise on the wording. Is this the message we want to convey?

3) Should we show this tab with an informational message if Telerik is not detected?

4) Should we show this tab with a warning message perhaps if Telerik is detected, but is being used?

Thanks.

**Comment by mitchelsellers** [comment]
I would propose the following messaging

**If Telerik Is Present & Can be Removed**

## Security Alert

We have detected the presence of the previously distributed Telerik developer components.  A Security Bulletin was released in August of 2021 that recommends immediate removal of this component due to the high-level security vulnerabilities present.  You can read more about this on the DNN Security Center - https://dnncommunity.org/security

Your installation does *NOT* appear to be utilizing any of these components, you may elect to have them removed as part f this upgrade to improve the security of your application.

Please note, that selecting "Yes" from below will complete the following steps for you automatically - https://docs.dnncommunity.org/content/getting-started/setup/telerik-removal/index.html.  

Then for the option 2 radio buttons

[ ] Yes, Improve my Security & Remove Telerik Now
[ ] No, Leave My Site Insecure

**If Telerik is Present & Cannot Be Removed**

## Security Alert

We have detected the presence of the previously distributed Telerik Developer Components.  A Security Bulletin was released in August 2021 that recommends immediate removal of this component to the high-level security vulnerabilities present.  You can read more about this on the DNN Security Center - https://dnncommunity.org/security

It is not possible to automatically remove Telerik on your installation due to the following modules:

<show list>

Starting with DNN 10.0.0 it will be mandatory to remove Telerik, please update or replace the above modules ASAP to ensure site integrity.

**If Telerik Already Removed**

The ideal situation would be to not show the tab, but if we have to show it.

## Ready for Future Upgrades

We have confirmed that you have removed Telerik which makes your site ready for DNN 10.0.

**Comment by bdukes** [comment]
Looks good Mitch.

Just to clarify, we don't want a default option for the radio buttons, the user is required to choose to either remove Telerik or remain insecure.

Do we need to say "extensions" instead of "modules", or is it easier to understand with "modules" even if it's not 100% accurate?

What about "Starting with DNN 10.0.0 it will be mandatory to remove Telerik, please update or replace the above modules ASAP <ins>and then follow [the manual Telerik removal steps](https://docs.dnncommunity.org/content/getting-started/setup/telerik-removal/index.html)</ins><del>to ensure site integrity</del>."

**Comment by david-poindexter** [comment]
This is awesome @daguiler.  And great verbiage @mitchelsellers.  @bdukes I am thinking we should follow the more accurate working of "extensions" in this case.  I don't think that will confuse people and it will be technically accurate.

**Comment by daguiler** [comment]
Ok, these are updated screenshots based on the feedback above:

### Present and Used
![telerik-installed-and-used](https://user-images.githubusercontent.com/30123437/164108684-0e8163db-c224-4ed1-a9e0-2efc0285ed36.png)

### Present but Not Used
![telerik-installed-but-not-used](https://user-images.githubusercontent.com/30123437/164108692-8387dbc7-39d6-4085-8a01-0637c98075a4.png)

### Not Present
![telerik-not-installed](https://user-images.githubusercontent.com/30123437/164108700-d1a65c32-f55e-489c-b56f-7711c8960610.png)

**Comment by david-poindexter** [comment]
Wonderful @daguiler - I only noticed one thing.  On the `Not Present` screen, "10.0" should be "10.0.0".

**Comment by daguiler** [comment]
Thanks. I'll take care of it.

**Comment by daguiler** [comment]
Not sure why #5093 didn't close this issue when it was merged
