### ISSUE TITLE
Add new Security Analyzer check for permissions on "Activity Feed" and "User Profile" pages

### ISSUE THREAD

**Issue by david-poindexter** [dnnsoftware/Dnn.Platform#4948]
Add a new check for permissions on the "Activity Feed" and "User Profile" pages.- If User Registration = None or Private and Either of these pages are visible to all users, warn that user profile information is displayed publicly- For all other user registration values, show an informational message if user profiles are public

**Comment by iJungleboy** [comment]
I suggest to keep titles much shorter, as this makes it hard to skim lists of issues.

**Comment by mitchelsellers** [comment]
@iJungleboy This was auto-created from a task list, but you are correct.  I adjusted

**Comment by daguiler** [comment]
I might be able to work on this one too, I will confirm tomorrow.

In the mean time I have the following question:
What happens if the user modifies the default page?

![image](https://user-images.githubusercontent.com/30123437/162099319-c7c4fa38-9a25-4fc2-8430-1ca9fc99bc9f.png)

And if they do, how do we find the new ~/Activity-Feed/My-Profile page?

**Comment by david-poindexter** [comment]
That's great @daguiler ❤️ 

I would think you would find it via the setting for the User Profile page.  Whatever page is configured here would be the page we need to check permissions on.

For the Activity Feed, that is not configurable, so your question is a good one.  Any thoughts on this one @dnnsoftware/approvers ?

**Comment by daguiler** [comment]
Yeah, I guess it's a bit misleading.

The label says "User Profile Page", but it actually lets the user define the default "activity feed" page. This activity feed page is the one we get routed to when we click on the avatar picture, or the user name at the top right corner. That's fine, if the user changes the default activity feed page, I can always find the new one.

My problem is with the actual profile page. How can we determine what the actual profile page is if the activity feed page is not the default one?

Can we assume the TabPath will be //whatever-the-activity-feed-tab-path-is//My-Profile ?

**Comment by daguiler** [comment]
I think I understand this a bit better now.

The "User Profile Page" setting indeed lets the user change the default user profile page.
The problem is that the default user profile page is not a page where we can see the actual user profile properties. Instead, it provides a landing page with the user's activity feed and a set of navigation links that takes you through a number of user profile-related pages.

But users might change this completely, and get rid of the activity feed, and instead design a user profile page that directly shows the user profile properties. Or create even a more complicated set of linked pages.

So maybe we should analyze whatever profile page is selected in the settings, and only analyze //Activity-Feed//My-Profile as a special case if the user profile page is still the default one?

**Comment by daguiler** [comment]
Ok, I have this new audt check implemented already, but I don't really understand it completely.
In particular, I don't understand the link between the portal's registration type and the visibility of the user profile page.

In addition, there are some limitations in how the audit checks work internally, that make it hard to return this "informational message" for Public and Verified registration types.

So to make it really simple, I created [this sheet](https://docs.google.com/spreadsheets/d/10cGjJvPAR-klMCSJpqYrY4EKYU5XCYK28Yw6SXo9VNE/edit?usp=sharing) which mimics the audit checks logic.

Can you guys please fill in the yellow cells for me?

**Comment by valadas** [comment]
> In particular, I don't understand the link between the portal's registration type and the visibility of the user profile page.

- Yeah, my thought exactly, one may want public registration but may not want to display the profiles publicly
- On the flip side, one may have registration disabled (creates users manually) but may want to actually display the profiles publicly intentionally.

Unless I am missing something, one has nothing to do with the other, I was thinking we just warn the pages are public (as a warning only so the host can decide if it was intentional or not)...

**Comment by david-poindexter** [comment]
You guys have excellent points and I tend to agree.  The on-page warning should be solely related to the page permissions being public (visible to "All Users").  Any objections to this approach?

**Comment by mitchelsellers** [comment]
I’m ok making it solely “are profile pages public” as the check
