### ISSUE TITLE
Profile - Update - Error:  Display Name Already In Use

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#4951]
## Description of bug
Provide a clear and concise description of the bug.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to [www.dnncommunity.org](https://www.dnncommunity.org)
2. Create an account if you do not have one
3. Log into account
4. Go to "edit profile"
5. Click "update" button

## Current behavior
Message Error:  Display Name Already In Use
Things get saved
I still use my display name

## Expected behavior
no error message

## Screenshots
![image](https://user-images.githubusercontent.com/13577556/145123394-b90acdaa-0551-43a2-b789-6ef82b87aa5a.png)

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version

* [ ] 10.00.00 alpha build
* [ ] 09.10.02 release candidate
* [ ] 09.10.01 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by valadas** [comment]
I cannot reproduce this on a couple of recent sites. My guess is this is specific to that site and maybe because "required unique display names" was turned on after you created your account and there was already a duplicate. Can you post this in the forums there so an admin can take a look at the display names. Unfortunatelly even though I am an admin there, cloudflare does not like me and I can't access the persona bar on that site.
