### ISSUE TITLE
HTML Editor Non-Functional Post Upgrade of DNN

### ISSUE THREAD

**Issue by mitchelsellers** [dnnsoftware/Dnn.Platform#4989]
## Description of bug
After performing an upgrade of DNN Platform the HTML Editor fails to display, or displays missing icons, until manual steps are taken to update the files/configurations within the editor itself.

## Steps to reproduce
This has been validated on multiple installations, currently using two different starting points for upgrade.

* Start with a working DNN Installation (Validated on 9.6.2 and 9.8.1)
* Upgrade to DNN 9.10.2
* HTML Editor will be broken, the exact state of broken 

## Current behavior
The HTML editor either displays with missing icons and "might" work, or the editor 100% fails to display.  (This will depend on the configuration and settings of the editors.  If a plugin is missing the editor fails to display.  Otherwise it will display sans icons)

You can fix this by going into this folder `/Providers/HtmlEditorProviders/DNNConnect.CKE/js/ckeditor`

And then reviewing these two sub folders; 

Old = 4.5.3
New = 4.15.1

The issue seems to stem from the following discrepancies

* Icons - Completely missing from 4.15.1
* Images - Completely missing from 4.15.1
* Plugins - Some of the plugins in 4.5.3 are missing, which causes failures.  This doesn't impact every installation
* Skins - Come of the skins from 4.5.3 are missing, this can cause issues depending on exact issues.

## Expected behavior
You should be able to upgrade DNN Platform and the HTML Editor should still be functional without manual intervention, especially intervention that requires direct access to the site.

## Error information
You will see multiple errors of failure to load files, or missing images

**Comment by WillStrohl** [comment]
Interesting...  We've recently done about 2 dozen upgrades over the past few weeks and many more since 09.10.02 dropped.  I'm happy that we haven't seen this once so far.  🤞🏽  

It will be interesting to know what the root cause is.  I'm wondering if it's not environmental...?  Maybe something like antivirus, low resources in Azure, or something else environmental? 

Or maybe these environments don't have enough spare resources (e.g., memory) to perform the function completely?  I've seen this cause all kinds of weird issues in some cases, requiring us to raise all of the maximum request/response limits temporarily until after the upgrade is complete.

**Comment by james7342** [comment]
I think I ran into the same thing in the issue that was closed.

https://github.com/dnnsoftware/Dnn.Platform/issues/4536

**Comment by leedavi** [comment]
![image](https://user-images.githubusercontent.com/5583141/151794468-c1985cdd-b3b1-4176-84ea-fa7ff29c13ae.png)

Not sure if this is the same issue?

Fails on v9.9.0, but worked on v9.8.1

**Comment by leedavi** [comment]
Upgrade to v9.10.2 and it works.  
Great!! Thanks everyone.

**Comment by leedavi** [comment]
I've removed my previous comment.  Sorry, this is not the same issue I have had.

**Comment by cklenk** [comment]
We had a weird issue on one of our websites where adding an SSL fixed a ckeditor issue. We were getting CKeditor is not defined console errors and then added an SSL and now it seems to be working. Can't figure out the root cause.

![image](https://user-images.githubusercontent.com/12185742/153081056-b50987c7-8145-4e3f-afee-273f4659a33b.png)

**Comment by WillStrohl** [comment]
> We had a weird issue on one of our websites where adding an SSL fixed a ckeditor issue. We were getting CKeditor is not defined console errors and then added an SSL and now it seems to be working. Can't figure out the root cause. We have no bundling or minification turned on either.
> 
> ![image](https://user-images.githubusercontent.com/12185742/153081056-b50987c7-8145-4e3f-afee-273f4659a33b.png)
> 
> after ssl
> 
> ![image](https://user-images.githubusercontent.com/12185742/153081465-2d4d662c-af1b-457a-8fdc-12f2c63e78cf.png)

This sounds like a separate issue and maybe needs to be logged separately.  With that being said, many frameworks assume that they're going to be deployed in a secure environment these days.  You're better off just having SSL on everything for a multitude of reasons. 

In this case, quite a few things might be a partial or root cause, but I'm guessing applying the SSL certificate cleared out an underlying SSL conflict in the browser that might have prevented a dependant non-secure script from loading.

**Comment by cklenk** [comment]
> 

Totally understand @WillStrohl!! This was on a dev site and not launched yet so that's why we didn't have an ssl on it. But good to know! I can certainly log a new issue for this if you want.

**Comment by WillStrohl** [comment]
No worries, @cklenk ...  Logging a new issue might only be necessary if it's reproducible.  These kinds of things aren't always able to be reproduced.  For example, there's a small chance that this was only environmental, and the SSL update was just coincidental.  No matter, this is all good information!  :)

**Comment by valadas** [comment]
This https://github.com/dnnsoftware/Dnn.Platform/pull/5205 could potentially fix this issue, calling attention to it so it can be tested on next RC...

**Comment by valadas** [comment]
I cannot reproduce this issues, so I am assuming that #5205 fixed this.

**Comment by sawest** [comment]
I just upgraded to 9.11.2 from 9.8.0. I experienced the exact same issue as @cklenk showed above. I had to copy two plugin folders from the 4.5.3 plugin folder to the 4.18.0 plugin folder (newsarticlelinks and iframedialog). After these were copied the editor is now working. It doesn't appear the #5205 fixed this issue.
