### ISSUE TITLE
Multiple Patches I could submit if there is interest in them

### ISSUE THREAD

**Issue by Andy9999** [dnnsoftware/Dnn.Platform#5045]
Hi!

I have made a couple of small changes to the DNN source code regarding the issues below. If there is some interest in having those patches included we could discuss how to enable them (and the default setting):

1. DNN Platform\Library\Framework\AJAX.cs

I have added ", EnableScriptLocalization = false" in line 44. The default setting is EnableScriptLocalization = true and this leads to an attempt to load a localized version of the AJAX library. You should be able to see it in a Browser network trace if you have some module loaded on a page that uses AJAX. With this change in place it will not attempt to localize the file name. To see this problem you may have to enable the CDN for Ajax in order to load it from a Microsoft web server. If you load it from your site you may already have copied the original version of the library file to have the requested file name. Would be interesting to hear others opinion of this.

2. DNN Platform\Website\admin\Skins\Privacy.ascx.cs & Terms.ascx.cs

The rel="nofollow" for the link to privacy and terms should be at least part of the ascx file to configure "rel" without having to recompile DNN. I could add rel="nofollow" to the Privacy.ascx and Terms.ascx files and remove it from the cs file. Would that be sufficient? The default would still be the same and if one doesn't want it to be nofollow one could easily change it. There are mixed opinions on having it set to nofollow (pro and contra). Some say having it nofollow could look kind of shady.

3. DNN Platform\Website\Default.aspx.cs

We don't want to differentiate between en-us and en-en for example, or de-de and de-au so we cut the location off leaving the two letters of the language code in the rendered `<html lang="en">` tag. We are not big enough of a site to have individual pages for each location and language is enough. What are your thoughts? Should this somehow be enabled/disabled? What would be the best way?

If there is any interest I could submit the 3 patches separately.

Best regards & happy DNNing
Andy9999

**Comment by WillStrohl** [comment]
Hello Andy...  This is AWESOME to hear!  Thank you for offering to contribute these back to the core.  I'd recommend creating a separate issue for each (if it doesn't already exist), so that you and others can collaborate on, triage, and test/release each individually based on their states at the end of each release cycle.  Let's see what others say...  Thanks again for being awesome!  :)

**Comment by Andy9999** [comment]
Hello Will, Thank you. I will split it into separate topics as suggested. :)

Best regards & happy DNNing
Andy9999

**Comment by valadas** [comment]
I don't see (at leat on that issue) a stale problem, a comment is good to unstale an issue in between the period of time of the first stalebot comment about it being closed soon if not active and the final comment when the issue gets closed due to lack of anyone moving the subject forward. That being said, human will reopen commented closed issues at any sign of interest in handling a closed issue.

**Comment by bdukes** [comment]
I reopened #4559 yesterday after this comment
