### ISSUE TITLE
Add Support for Content-Security-Policy: script-src to not require unsafe-inline 

### ISSUE THREAD

**Issue by radun2** [dnnsoftware/Dnn.Platform#5075]
## Description of problem
I would like to create a CSP that doesn't include unsafe-inline: (eg: Content-Security-Policy: script-src 'unsafe-inline'). If set differently will not allow for starters Persona Bar to work and this is a block to enter edit mode and so on. DNN basically needs inline scripts to work and if asked to not have inline scripts it will break. 

## Description of solution
Use nonce on the tag scripts that are added by DNN for its functionality. https://content-security-policy.com/nonce/

## Description of alternatives considered
Use sha256-... on tag scripts that are added by DNN for its functionality. https://content-security-policy.com/hash/

## Screenshots
Not applicable 

## Additional context
Disallowing inline styles and inline scripts is one of the biggest security wins CSP provides.  I expect the attack tools to adapt to weak CSPs, but it will mean a lot of common exploits are immediately off the cards, or harder.

## Affected browser

* [ X] Chrome
* [ X] Firefox
* [ X] Safari
* [ X] Internet Explorer
* [ X] Edge

**Comment by radun2** [comment]
Also maybe this library would be of help for this feature request?
https://github.com/NWebsec/NWebsec

**Comment by mitchelsellers** [comment]
This is being discussed in issue #4850 and is a much larger impact change for the platform than it may seem due to third-party modules and other factors.

**Comment by obujeiromhginsurance** [comment]
This is still a security issue, I have not found any solution to this inline script that comes with DNN's login button

<a id="dnn_ctr_Login_Login_DNN_cmdLogin" title="Login" class="dnnPrimaryAction dnnDisabledAction" href="javascript:__doPostBack('dnn$ctr$Login$Login_DNN$cmdLogin','')">Login</a>

Tried nonce and unsafe-hashes and hash, no solution.

Problem login
Was not able to solve this without adding unsafe-inline
ERROR
Refused to run the JavaScript URL because it violates the following Content Security Policy directive: "script-src 'self'

Based on DNN's answer this is definitely a product to be completely replaced.
