### ISSUE TITLE
When manifest is missing referenced file, exception is thrown instead of helpful error message

### ISSUE THREAD

**Issue by bdukes** [dnnsoftware/Dnn.Platform#5096]
## Description of bug
When a module package is uploaded to the installer, if the `<releaseNotes>` or `<license>` element uses the `src` attribute to point to a file that is not in the package, an exception is throw and the user gets no feedback about the issue.

## Steps to reproduce
1. Upload the package [Example_install.zip](https://github.com/dnnsoftware/Dnn.Platform/files/8534120/Example_install.zip)

## Current behavior
Generic error (see screenshot below)

## Expected behavior
Helpful error

## Screenshots
![Upload error with response YSOD](https://user-images.githubusercontent.com/59507/164527522-e2fa0b1f-a1fb-45b2-b0c3-15a8b358ca96.png)

## Error information
<detail>
<summary>The system cannot find the file specified.</summary>
<pre>
[PathNotFoundException: The system cannot find the file specified.]
   SchwabenCode.QuickIO.Internal.InternalQuickIOCommon.NativeExceptionMapping(String path, Int32 errorCode) +272
   SchwabenCode.QuickIO.QuickIOFile.OpenFileStream(QuickIOPathInfo pathInfo, FileAccess fileAccess, FileMode fileOption, FileShare shareMode, Int32 buffer) +92
   SchwabenCode.QuickIO.QuickIOFile.OpenText(QuickIOPathInfo pathInfo) +34
   DotNetNuke.Common.Utilities.FileSystemUtils.ReadFile(String filePath) in D:\a\1\s\DNN Platform\Library\Common\Utilities\FileSystemUtils.cs:165
   DotNetNuke.Services.Installer.Installers.PackageInstaller.ReadTextFromFile(String source) in D:\a\1\s\DNN Platform\Library\Services\Installer\Installers\PackageInstaller.cs:581
   DotNetNuke.Services.Installer.Installers.PackageInstaller.ReadManifest(XPathNavigator manifestNav) in D:\a\1\s\DNN Platform\Library\Services\Installer\Installers\PackageInstaller.cs:210
   DotNetNuke.Services.Installer.Installers.PackageInstaller..ctor(String packageManifest, InstallerInfo info) in D:\a\1\s\DNN Platform\Library\Services\Installer\Installers\PackageInstaller.cs:84
   DotNetNuke.Services.Installer.Installer.ProcessPackages(XPathNavigator rootNav) in D:\a\1\s\DNN Platform\Library\Services\Installer\Installer.cs:483
   DotNetNuke.Services.Installer.Installer.ReadManifest(Boolean deleteTemp) in D:\a\1\s\DNN Platform\Library\Services\Installer\Installer.cs:347
   Dnn.PersonaBar.Extensions.Components.InstallController.GetInstaller(Stream stream, String fileName, Int32 portalId, String legacySkin, Boolean isPortalPackage) in D:\a\1\s\Dnn.AdminExperience\Dnn.PersonaBar.Extensions\Components\Extensions\InstallController.cs:181
   Dnn.PersonaBar.Extensions.Components.InstallController.ParsePackage(PortalSettings portalSettings, UserInfo user, String filePath, Stream stream) in D:\a\1\s\Dnn.AdminExperience\Dnn.PersonaBar.Extensions\Components\Extensions\InstallController.cs:37
   Dnn.PersonaBar.Extensions.Services.<>c__DisplayClass42_1.<UploadFileAction>b__1(Object <p0>) in D:\a\1\s\Dnn.AdminExperience\Dnn.PersonaBar.Extensions\Services\ExtensionsController.cs:1436
   System.Web.Util.SynchronizationHelper.SafeWrapCallback(Action action) +118
</pre>
</detail>

**Comment by WillStrohl** [comment]
I wanted to try to see what EVS reports about this, because it might be a way to pull in some existing code/logic from the [EVS repo](https://github.com/dnnsoftware/Dnn.EVS).  However, it looks like I won't be able to do that.  😦 

![image](https://user-images.githubusercontent.com/938023/164530402-ea6f4d6d-2cfb-444b-876a-ddd38eeecde0.png)

![image](https://user-images.githubusercontent.com/938023/164530492-72517052-19d4-46df-b289-a9b4cbfbab06.png)

**Comment by ohine** [comment]
> I wanted to try to see what EVS reports about this, because it might be a way to pull in some existing code/logic from the [EVS repo](https://github.com/dnnsoftware/Dnn.EVS). However, it looks like I won't be able to do that. 😦

I was in the process of porting over EVS to our community dotnetfoundation account when I was expelled from the group which handles such tasks. As always, I'd be happy to resume that work, but I'd need that access restored. I highly doubt that would happen, but either way, I'm offering it because it's been 3 years now and nobody has stepped up to do the work that I had planned out in the roadmap for the build team I started but was disbanded from.
