### ISSUE TITLE
Update SharpZipLib to version 1.3.3+

### ISSUE THREAD

**Issue by schotman** [dnnsoftware/Dnn.Platform#5186]
## Description of problem
The current 0.86 stems from 2011 and has issues with non-US Windows, particularly it throws an error on "1 is not a supported code page" when updating certain modules.

## Description of solution
Update SharpZipLib to version 1.3.3+
this version also has an MIT license

**Comment by sleupold** [comment]
this has already been accomplished for DNN 9.11.0

**Comment by brentil** [comment]
> this has already been accomplished for DNN 9.11.0

What is the time table for this?  I reported the Critical CVE that is in SharpZipLib and known CVEs in other components to the DNN security team in both Nov 2021 and Mar 2022 and both times was told it was known and was coming in the next release.  It's been 8+ months since I first reported and there's been no new release to correct these known vulnerabilities.

**Comment by bdukes** [comment]
Please direct security questions to security@dnnsoftware.com
