### ISSUE TITLE
Upgrade to v9.11.0-rc2 may delete DLLs from DNN-Extensions like 2sxc with Imageflow

### ISSUE THREAD

**Issue by BeniFreitag** [dnnsoftware/Dnn.Platform#5266]
## Description of bug
The Upgrade Wizard deletes DLLs from extensions, so the whole DNN application may not work after the upgrade completed.

## Steps to reproduce
1. Install DNN 9.6.0 with 2sxc 13 (or newer). It will place these files into the bin-folder: Imageflow.Net.dll, Imazen.Common.dll, Imazen.HybridCache.dll and Imageflow (entiry folder)
2. Unzip the DNN Upgrade Package
3. Run the Upgrade Wizard
4. When the Upgrade Wizard completed, the DNN-Application will not start anymore

## Current behavior
DNN application does not start anymore. Error because of missing DLLs.

## Expected behavior
DNN upgrade should not delete DLLs from DNN-Extensions.

## Error information
Error when the Upgrade Wizard completed:
`Could not load file or assembly 'Imazen.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.`

## Additional context
2sxc ships with Imageflow (till version 12) and/or Imazen (version 13+). The installation places additional DLLs into the bin folder. They're own assemblies and not shared with other extensions.

## Affected version

* [x] 09.11.00 release candidate 2

## Affected browser

* [x] Chrome

**Comment by david-poindexter** [comment]
[DNN 9.11.0 RC 3](https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.11.0-rc3) is now out.  I am not sure if this is still an issue there or not, but you may want to try that to confirm or deny the existence of the issue.

**Comment by valadas** [comment]
I don't know of any change in 9.11.0 that could cause this. I may be wrong but nothing pops to mind. Before trying another upgrade can you ensure that your install/modules folder has no other .zip files my guess here is that maybe there was some stray 2sxc version of an older or newer version in there that triggered those deletions maybe...

**Comment by BeniFreitag** [comment]
The DLLs are deleted after the Upgrade Wizard has completed, after I click _Visit Website_. It seems there's something in the application startup. [I recorded the behavior here](https://www.screencast.com/t/eRXzFC0gxdz).

The test was made with DNN 09.06.01 and 2sxc 14.07.04. I used the Upgrade Package from [DNN 9.11.0 RC 3](https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.11.0-rc3)

@tvatavuk please review whether this is caused by code in [2sxc](https://github.com/2sic/2sxc) or [DNN](https://github.com/dnnsoftware/Dnn.Platform). Thanks.

**Comment by tvatavuk** [comment]
On 13th sec of Your screenscast something DELETED `bin/Imageflow` folder, almost like [DEL] key was pressed, but it remain mystery to me what code is causing that Imageflow folder is deleted 🧐.

[DNN-imageflow](https://github.com/2sic/dnn-imageflow) is installed as part of 2sxc 13LTS+. There is code, that is executed on startup that will replace native dll's when is necessary and when this native dll's are not locked:
1. when file exists `bin\win-x64\native\imageflow.dll.pending` than delete `bin\win-x64\native\imageflow.dll`
1. when file exists `bin\win-x86\native\imageflow.dll.pending` than delete `bin\win-x86\native\imageflow.dll`

https://github.com/2sic/dnn-imageflow/blob/8cf9e21fb5779d1779295a6621799cbb779ba281/UpgradeUtil.cs#L59

After reviewing this code, I can not see how this code in expected flow can delete `bin\Imazen.Common.dll` or any of its [dependencies](https://www.nuget.org/packages/Imazen.Common/0.5.10#dependencies-body-tab) as was reported by next exception from your screencast.

![image](https://user-images.githubusercontent.com/2724850/188497968-56d05a35-3e40-4da8-87cb-ee02e7ec8336.png)

I was trying to reproduce this issues, but instead I got https://github.com/dnnsoftware/Dnn.Platform/issues/5260. I think that one happens because some new dnn code do not expect and handle native dll's. 

![image](https://user-images.githubusercontent.com/2724850/188499961-3f3a3e3f-49f7-4f53-af44-b6600c17dc4d.png)

As workaround I temporary renamed:
- `bin\runtimes\win-x64\native\imageflow.dll` -> `imageflow.dll.bak` 
- `bin\runtimes\win-x86\native\imageflow.dll` -> `imageflow.dll.bak`

... so I could finish all upgrade steps. 

In last step, only 4 dll where removed.

![image](https://user-images.githubusercontent.com/2724850/188500274-67daa7d1-4ab9-41e5-b956-fd2ad07697bc.png)

On last screen before I clicked Visit Website, I renamed back native dll's from `imageflow.dll.bak` to `imageflow.dll` and all was OK.

![image](https://user-images.githubusercontent.com/2724850/188499975-34d325e4-4c43-4673-b0e9-2d290d0d44bb.png).

At the end I could not reproduce exact steps from this issue, with reported exception.

To be on safe side, I also did review of https://github.com/2sic/2sxc/blob/master/Src/Dnn/ToSic.Sxc.Dnn/DnnPackageBuilder/2sic_2SexyContent.dnn but could not see anything that will remove bin/Imageflow.

**Comment by valadas** [comment]
An RC3 should be coming soon, but can you try the build artifact (when the build finishes) here https://dev.azure.com/dotnet/DNN/_build/results?buildId=77695&view=results to see if fixing #5260 also fixes this issue.

**Comment by valadas** [comment]
Ok, here is RC4 if you can re-test https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.11.0-rc4

Not that there was any change specific to this, but it's odd that it is the same files that were reported for #5260 so who knows, maybe it fixes this issue too...

**Comment by BeniFreitag** [comment]
I just tested the Upgrade to RC4. #5260 is fixed, but this issue is still there. [I created another screencast](https://www.screencast.com/t/odPalsGb), at 1:17 multiple files get deleted.

@tvatavuk I just sent you a backup of the website used in this screencast, before I extracted the DNN-Upgrade package.

**Comment by tvatavuk** [comment]
@BeniFreitag I noticed that on your DNN 9.6.1, uninstall of **DNN Security HotFix 2017.1** v1.0.1 extension with checked **delete files** will remove all that 3rd party dll's Your reported and break dnn site at the end. 

![image](https://user-images.githubusercontent.com/2724850/188666755-38b79f72-edd0-46a1-a46a-e201eb60abd5.png)

![image](https://user-images.githubusercontent.com/2724850/188666681-d1afaf43-0a4d-49bb-9666-480660953122.png)

This happens as side effect of telerik uninstall, that is part of DNN 9.11.0 rc04 upgrade.
https://github.com/dnnsoftware/Dnn.Platform/blob/e0b483e06c4c0a26ed3c6b27598c05436b0db3a5/DNN%20Platform/DotNetNuke.Maintenance/Telerik/Removal/TelerikUninstaller.cs#L31

Several workarounds are possible, but non looks right.

I still have to find details, why this happens and/or what should be done better with 2sxc/dnn-imageflow installation to not be affected by this.

**Comment by valadas** [comment]
Oh, something just came to mind. In the Assemblies database table you should see which Package registered the DLL dependency. Then in the Packages table you can find the name for that PackageId.

Is it possible that something got wrong in any of those two tables producing this issue ?

**Comment by tvatavuk** [comment]
Dnn-imageflow that is installed as part of 2sxc module create Resources.zip.manifest during installation with list of dlls from Resources.zip. I looks the same file is used during DNNSecurityHotFix20171 uninstall file delete, and that breaks existing dnn-imageflow install and dnn.

I will update dnn-imageflow to use different manifest file, to avoid same in future.

**Comment by BeniFreitag** [comment]
Just tested another upgrade to DNN 9.11.00 RC5. The issue does not occur anymore. Thanks @donker, @tvatavuk and @valadas.
