### ISSUE TITLE
Set the desired "Start time" of a scheduled task

### ISSUE THREAD

**Issue by rodrigoratan** [dnnsoftware/Dnn.Platform#5424]
## Description of problem
I have some long running tasks that I must run after midnight but due to some factors even if I manually start it at the desired time it will drift everyday

We should have the ability to set the 'desired' next start time for a scheduled task

## Description of solution
We can set the Frequency of any scheduled task and also the start date and time, but we can not specify the 'desired' next start time

I know that due the nature of the way scheduled tasks work on DNN/ASP.Net webforms is somewhat impossible to determine when your task is going to run, but if I have an Daily recurrence and run the task now, it will try to run tomorrow on the same time

Would be nice to have how to set the desired Start time, not just the Next Start, but the time when it will run every day (whenever possible)

Does that make sense? I would like to try implement it myself (with help if possible) but first I want to make sure this requirement is useful not only for me

**Comment by bdukes** [comment]
This is a common issue we run into, I'd definitely support this feature getting implemented.

Implementing it as a desired start time seems like it would only work for tasks that run once a day (or, I suppose, less often, e.g. once a week). Would it make sense to potentially have a list of times if you wanted it to run two or three times a day? Or just an option to base the schedule on the start time instead of the end time, so that it's always e.g. 24 hours from the preferred start time?

**Comment by mitchelsellers** [comment]
I've been looking at this, and discussing options for years, and implementation of a "always run at ___ time" operation is something that not only requires code-changes in the platform, but it also requires configuration within the hosting environments.

If your application follows default behaviors and shuts down due to inactivity, you are not able to have a job run if the site is sleeping.  Then when it wakes up, it handles over-due items

You can change this configuration, however, then you might introduce other issues as the sites refreshing/restarting can be helpful for other issues that might be hidden by the regular application restarts.

For DNN 10.x or 11.x, I would love to integrate something such as HangFire (with permission) or similar that has robust accounting for timed, delayed, or otherwise background tasks.

**Comment by rodrigoratan** [comment]
@mitchelsellers I'm aware that the desiredStartTime would not be respected if the site is shutdown, but it's better than me having to wait for midnight (in my case) just to run it manually to have the nextStart set to the next day at the same time

I think the implementation should only set the [desired]NextStart field and if the site is awake at that time, it would run. If if only awakes 1hour later, it will check if any tasks are due and run, but it should not affect the nextStart of the next day

**Comment by mitchelsellers** [comment]
Ok, @rodrigoratan so really just a scheduled "next run".  Everything after that time would follow other scheduled situations?

If so, would a "Run at ____" be a better option?  So rather than "Run Now" it would be run this at midnight

**Comment by rodrigoratan** [comment]
@mitchelsellers yes! 

Its's nice to still have the "Run now" option when you want to test (for whatever reason), 

And also have a (new) option to "Run at ____" and then it would run at this desired time, and the next day it would try to run at the same time and so on like it's already

For my use case scenario (having to wait just to have an scheduled task run daily at the same time) I think it would suffice

I have not yet looked into the C# code, but in the database there's the "NextStart" in the ScheduleHistory table, is it used as a settings or is just for login?  There's also the "ScheduleStartDate" that I guess is used for the first run

**Comment by rodrigoratan** [comment]
as @bdukes pointed out, it is best to base the schedule on the start time instead of the end time, so that it's always e.g. 24 hours from the preferred start time

**Comment by rodrigoratan** [comment]
The point is, even if we cannot trust on the website to be awake, we should at least have the option to set the desired start time, and if (currentTime => desiredStartTime && !hasntRun) then it should run

*hasntRun = did not run since last successful run

**Comment by rodrigoratan** [comment]
![image](https://user-images.githubusercontent.com/964066/205759842-2644bb12-f727-449e-9292-4780c42dae89.png)

That also may not be necessary, the next start is based on the previous start, not the previous end
