### ISSUE TITLE
Update Profile throw error 503 - Causing website down

### ISSUE THREAD

**Issue by erw13n** [dnnsoftware/Dnn.Platform#5509]
## Description of bug
Update Profile on DNN 9.11 seems not working.
Error return 503 Service Unavailable.

Test on Upgrade version and Fresh installation, also the Alpha version

Not happen on 9.10

## Steps to reproduce
List the precise steps to reproduce the bug:
1. From Personal Bar, Go to `Users`
2. Choose any user and click on `User Profile`
3. Update any field and press Update
4. It have never ending loading
5. If open on Localhost, it will ask for Debugging
6. If keep pressing Cancel Debugging, it will bring the website Down with error 503 Service Unavailable
7. Refresh the page will make the website down.

## Screenshots
![image](https://user-images.githubusercontent.com/792847/215574672-1778be11-ef11-4952-b904-df047ae7556e.png)

![image](https://user-images.githubusercontent.com/792847/215575397-64c6a1ae-3c2b-43ab-bc0e-15d024e01a99.png)

## Affected version

* [x] 09.11.00 Alpha
* [x] 09.11.00 Stable

**Comment by valadas** [comment]
Fixed in #5508 

Please try the latest build (this has been done this weekend)
https://artprodwus21.artifacts.visualstudio.com/Ad394b248-b709-4c8a-9adc-6ed9de8c8163/9defc7c7-d48d-4a8b-9f46-fd11ba3c5aad/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RvdG5ldC9wcm9qZWN0SWQvOWRlZmM3YzctZDQ4ZC00YThiLTlmNDYtZmQxMWJhM2M1YWFkL2J1aWxkSWQvODY1NzgvYXJ0aWZhY3ROYW1lL0FydGlmYWN0czE1/content?format=zip

If it's still and issue, let me know and I'll re-open this issue...

**Comment by erw13n** [comment]
OK, I'll test it.

**Comment by erw13n** [comment]
Confirmed, it's works like a charm.
Thank you.
