### ISSUE TITLE
[Bug]: Unknown server tag 'dnn:ACTIONS' on fresh install 9.13.3

### ISSUE THREAD

**Issue by frontier777** [dnnsoftware/Dnn.Platform#6067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I unzipped from DNN_Platform_9.13.3_Install.zip
Created a new VS2022 solution.
Added an existing web site project.
When I run/build I get the following related errors.

The file '/DesktopModules/DDRMenu/Actions.ascx' does not exist.
Unknown server tag 'dnn:ACTIONS'.

The error is generated from file \admin\Menus\DNNActions\DDRActionsMenu.ascx

The install zip file doesn't include the folder /DesktopModules/DDRMenu at all.

### Steps to reproduce?

Step as explained above.

### Current Behavior

Error in fully up to date Visual Studio 2022 (17.10.1).

### Expected Behavior

To run and see the install page.

### Affected Versions

9.13.3 (latest release)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bdukes** [comment]
What are you trying to do? It's not typically necessary/useful to create a new solution which includes the DNN website.

If you're trying to make changes to the DNN Platform itself, following the instructions in https://github.com/dnnsoftware/Dnn.Platform/blob/develop/.github/BUILD.md.

If you're just trying to setup a website, you don't need Visual Studio. There are installation instructions at https://docs.dnncommunity.org/content/tutorials/server/setup/administrators-setup-overview/index.html.

If you're trying to develop extensions for a DNN site, there are a variety of models. An overview and links to documentation are available in @david-poindexter's recent blog post, https://dnncommunity.org/blogs/Post/18693/Developing-Extensions-in-DNN-A-Beginner-s-Guide.

Hope it helps!

**Comment by mitchelsellers** [comment]
Many years ago the DNN solution became pre-compiled, this most likely is why you are seeing issues.  More specifically the DNN Platform source code is NOT compatible with the Web Site Project (WSP) format that was popular in early .NET Framework days.

The _Install.zip that is downloadable as an installation artifact is what is needed to actually run DNN  Platform and is already precompiled and does not have any csproj or solution files as it is designed for running at the time.

If you are looking to build DNN you will need to interact with the source code download that is available, as that will contain the .sln file and other assets.

**Comment by mitchelsellers** [comment]
@frontier777 the installer is NOT an installer to setup a development environment, it is an installation to setup an actual running instance of DNN Platform.

If you want to compile/debug the DNN Solution you should be utilizing the source.

The artifacts included in the installer are release compiled already.

**Comment by mitchelsellers** [comment]
> Do you not agree that, as it is, out of the box, it contains compile errors - my point is, it doesn't (shouldn't) need to be that way. Or should at least be noted in the install guide.

No, I do not believe that we have a compilation error out of the box.  The install package is NEVER intended to be compiled, it is ALREADY compiled.  The install process moves/places files as needed for first time use.  At least this is my $0.02, I understand that some people have done this before, but it isn't intended this way and the results may very well be unexpected since the source isn't all there.

> After the installer has run, you can use it the way I describe - of course you can, or the site would be broken. And frankly there is no more natural or more direct way to develop modules on this platform, or any other .NET platform for that matter.

I'll let others chime in here, 2000+ modules deep, we do NOT develop locally with a Visual Studio opened copy of DNN as I'm primarily working in CI/CD environments and otherwise, so I do NOT attempt this process.  Maybe others have a better suggestion.

**Comment by valadas** [comment]
Well, my 2 cents here, the install zip is not the source code. The field has changed a lot since DNN started and it now involves more advances install/upgrade steps. From a developer perspective we now have nuget packages which was not the case early on. What most closely ressembles your scenario would be to:
1: Install a local instance using that install zip
2: Clone this repository and setup the settings file (as documented in https://github.com/dnnsoftware/Dnn.Platform/blob/develop/.github/BUILD.md
