### ISSUE TITLE
[Bug]: v9.6.1 use of https://www.myget.org/F/dnn-software-public

### ISSUE THREAD

**Issue by zieglerjm** [dnnsoftware/Dnn.Platform#6131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Looks like the [www.myget.org](https://www.myget.org/F/dnn-software-public) subscription is dead.  How do we get the packages?

### Steps to reproduce?

Build v9.6.1 on a NEW PC.

### Affected Versions

9.13.3 (latest release)

### What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bdukes** [comment]
Yes, we don't use that resource anymore and the community never managed that resource. It looks like [we removed that in 9.10.1](https://github.com/dnnsoftware/Dnn.Platform/commit/1a25bfe48b7f6fcc5ea7650bdf8e301d15bba3f0). You may be able to replicate that change in 9.6.1 if you really need to compile that version instead of upgrading. Hope it helps!
