### ISSUE TITLE
[Bug]: Stupid cms not start site afer install all dependencies and run powershell script

### ISSUE THREAD

**Issue by ednsinf** [dnnsoftware/Dnn.Platform#6142]
Stupid cms not start site afer install all dependencies and run powershell script

Linha 50:                 // first call GetProviderPath - this insures that the Database is Initialised correctly
Linha 51:                 // and also generates the appropriate error message if it cannot be initialised correctly
Linha 52:                 string strMessage = DataProvider.Instance().GetProviderPath();
Linha 53: 
Linha 54:                 // get current database version from DB

Arquivo de Origem: C:\Users\xxx\Downloads\Dnn.Platform-9.13.4\DNN Platform\Library\Application\ApplicationStatusInfo.cs    Linha: 52

Rastreamento de Pilha:

[NullReferenceException: Referência de objeto não definida para uma instância de um objeto.]
   DotNetNuke.Application.ApplicationStatusInfo.get_Status() in C:\Users\xxx\Downloads\Dnn.Platform-9.13.4\DNN Platform\Library\Application\ApplicationStatusInfo.cs:52
   DotNetNuke.Common.Initialize.Init(HttpApplication app) in C:\Users\xxx\Downloads\Dnn.Platform-9.13.4\DNN Platform\Library\Common\Initialize.cs:44
   DotNetNuke.Web.Common.Internal.DotNetNukeHttpApplication.Application_BeginRequest(Object sender, EventArgs e) in C:\Users\xxx\Downloads\Dnn.Platform-9.13.4\DNN Platform\DotNetNuke.Web\Common\DotNetNukeHttpApplication.cs:231
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +136
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +171
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +92

**Comment by jeremy-farrance** [comment]
I just redeployed DNN Platform via Git Clone and opened the .sln in Visual Studio 2022.

Here is my VS setup / workloads / installation details:
![image](https://github.com/user-attachments/assets/8a29329b-7ce3-4a1f-9304-20a7f66e79e0)

I've already followed the instructions here.
https://github.com/dnnsoftware/Dnn.Platform/blob/develop/.github/BUILD.md

I've ensured I am running a suitable version of Node, VS is in Debug/Any CPU: 
![image](https://github.com/user-attachments/assets/a82c345f-c53a-4b58-90e1-00f577e23c79)

Before running build I also reviewed this old Quick Start Step by Step to make sure my machine had all the modern versions of things mentioned here: https://github.com/dnnsoftware/Dnn.Platform/discussions/4950

I carefully configured my `settings.local.json` so the build would go to my local working copy of DNN. In other words, this is where the build would "build into."
 
I ran build, on my machine, this took a long time (over 4 mins) as you can see:
![image](https://github.com/user-attachments/assets/6d57d881-0cfb-450a-bc7c-755662f22662)

To prove my build work I went to the working site and logged in. Since I built 9.13.04 I still needed to prove I was running the version I had just built/compiled, so I went to build and checked the date-times of the DLLs:
![image](https://github.com/user-attachments/assets/43e68bc0-dbb7-4f88-88f4-97e5389f6e45)

This is a very large project. Expecting it to "just work" is not reasonable. Times change, versions of the tools and frameworks change constantly. If you really want to do this, step one is deciding to work through to the finish line. Step 2 is to be humble and get some help. My suggestion is you drop the attitude, don't lead with "stupid CMS" and consider reaching out via the forums on  DNNCommunity.org or join the DNN Community on Discord. Ask good questions, show your work and effort and you will easily get the help you need to get to the finish line.

**Comment by valadas** [comment]
@ednsinf Please adjust your language and stop removing all the issue templates.
